/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NexxaTrade API
 * API documentation for NexxaTrade
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Def13,
  Def14,
  Def15,
  Def16,
  Def17,
  Def18,
  Def19,
  PatchApiMembershipPlansTierBody,
  PostApiMembershipPlansBody
} from '../generated.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List membership tiers
 */
export const getApiMembershipTiers = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def14>(
      {url: `/api/membership/tiers`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiMembershipTiersQueryKey = () => {
    return [
    `/api/membership/tiers`
    ] as const;
    }

    
export const getGetApiMembershipTiersQueryOptions = <TData = Awaited<ReturnType<typeof getApiMembershipTiers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipTiers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMembershipTiersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMembershipTiers>>> = ({ signal }) => getApiMembershipTiers(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipTiers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMembershipTiersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMembershipTiers>>>
export type GetApiMembershipTiersQueryError = unknown


export function useGetApiMembershipTiers<TData = Awaited<ReturnType<typeof getApiMembershipTiers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipTiers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMembershipTiers>>,
          TError,
          Awaited<ReturnType<typeof getApiMembershipTiers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMembershipTiers<TData = Awaited<ReturnType<typeof getApiMembershipTiers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipTiers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMembershipTiers>>,
          TError,
          Awaited<ReturnType<typeof getApiMembershipTiers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMembershipTiers<TData = Awaited<ReturnType<typeof getApiMembershipTiers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipTiers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List membership tiers
 */

export function useGetApiMembershipTiers<TData = Awaited<ReturnType<typeof getApiMembershipTiers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipTiers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMembershipTiersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a membership plan
 */
export const postApiMembershipPlans = (
    postApiMembershipPlansBody: PostApiMembershipPlansBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def13>(
      {url: `/api/membership/plans`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiMembershipPlansBody, signal
    },
      options);
    }
  


export const getPostApiMembershipPlansMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipPlans>>, TError,{data: PostApiMembershipPlansBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipPlans>>, TError,{data: PostApiMembershipPlansBody}, TContext> => {

const mutationKey = ['postApiMembershipPlans'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiMembershipPlans>>, {data: PostApiMembershipPlansBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiMembershipPlans(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiMembershipPlansMutationResult = NonNullable<Awaited<ReturnType<typeof postApiMembershipPlans>>>
    export type PostApiMembershipPlansMutationBody = PostApiMembershipPlansBody
    export type PostApiMembershipPlansMutationError = unknown

    /**
 * @summary Create a membership plan
 */
export const usePostApiMembershipPlans = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipPlans>>, TError,{data: PostApiMembershipPlansBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiMembershipPlans>>,
        TError,
        {data: PostApiMembershipPlansBody},
        TContext
      > => {

      const mutationOptions = getPostApiMembershipPlansMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update a membership plan
 */
export const patchApiMembershipPlansTier = (
    tier: string,
    patchApiMembershipPlansTierBody: PatchApiMembershipPlansTierBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<Def13>(
      {url: `/api/membership/plans/${tier}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchApiMembershipPlansTierBody
    },
      options);
    }
  


export const getPatchApiMembershipPlansTierMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiMembershipPlansTier>>, TError,{tier: string;data: PatchApiMembershipPlansTierBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiMembershipPlansTier>>, TError,{tier: string;data: PatchApiMembershipPlansTierBody}, TContext> => {

const mutationKey = ['patchApiMembershipPlansTier'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiMembershipPlansTier>>, {tier: string;data: PatchApiMembershipPlansTierBody}> = (props) => {
          const {tier,data} = props ?? {};

          return  patchApiMembershipPlansTier(tier,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiMembershipPlansTierMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiMembershipPlansTier>>>
    export type PatchApiMembershipPlansTierMutationBody = PatchApiMembershipPlansTierBody
    export type PatchApiMembershipPlansTierMutationError = unknown

    /**
 * @summary Update a membership plan
 */
export const usePatchApiMembershipPlansTier = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiMembershipPlansTier>>, TError,{tier: string;data: PatchApiMembershipPlansTierBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiMembershipPlansTier>>,
        TError,
        {tier: string;data: PatchApiMembershipPlansTierBody},
        TContext
      > => {

      const mutationOptions = getPatchApiMembershipPlansTierMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get membership state for a user
 */
export const getApiMembershipUsersUserId = (
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def15>(
      {url: `/api/membership/users/${userId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiMembershipUsersUserIdQueryKey = (userId?: string,) => {
    return [
    `/api/membership/users/${userId}`
    ] as const;
    }

    
export const getGetApiMembershipUsersUserIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiMembershipUsersUserId>>, TError = unknown>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipUsersUserId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMembershipUsersUserIdQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMembershipUsersUserId>>> = ({ signal }) => getApiMembershipUsersUserId(userId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipUsersUserId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMembershipUsersUserIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMembershipUsersUserId>>>
export type GetApiMembershipUsersUserIdQueryError = unknown


export function useGetApiMembershipUsersUserId<TData = Awaited<ReturnType<typeof getApiMembershipUsersUserId>>, TError = unknown>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipUsersUserId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMembershipUsersUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiMembershipUsersUserId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMembershipUsersUserId<TData = Awaited<ReturnType<typeof getApiMembershipUsersUserId>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipUsersUserId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMembershipUsersUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiMembershipUsersUserId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMembershipUsersUserId<TData = Awaited<ReturnType<typeof getApiMembershipUsersUserId>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipUsersUserId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get membership state for a user
 */

export function useGetApiMembershipUsersUserId<TData = Awaited<ReturnType<typeof getApiMembershipUsersUserId>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMembershipUsersUserId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMembershipUsersUserIdQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Activate a membership after payment confirmation
 */
export const postApiMembershipActivate = (
    def16: Def16,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def17>(
      {url: `/api/membership/activate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: def16, signal
    },
      options);
    }
  


export const getPostApiMembershipActivateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipActivate>>, TError,{data: Def16}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipActivate>>, TError,{data: Def16}, TContext> => {

const mutationKey = ['postApiMembershipActivate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiMembershipActivate>>, {data: Def16}> = (props) => {
          const {data} = props ?? {};

          return  postApiMembershipActivate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiMembershipActivateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiMembershipActivate>>>
    export type PostApiMembershipActivateMutationBody = Def16
    export type PostApiMembershipActivateMutationError = unknown

    /**
 * @summary Activate a membership after payment confirmation
 */
export const usePostApiMembershipActivate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipActivate>>, TError,{data: Def16}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiMembershipActivate>>,
        TError,
        {data: Def16},
        TContext
      > => {

      const mutationOptions = getPostApiMembershipActivateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Expire memberships that are past due
 */
export const postApiMembershipExpire = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def18>(
      {url: `/api/membership/expire`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiMembershipExpireMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipExpire>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipExpire>>, TError,void, TContext> => {

const mutationKey = ['postApiMembershipExpire'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiMembershipExpire>>, void> = () => {
          

          return  postApiMembershipExpire(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiMembershipExpireMutationResult = NonNullable<Awaited<ReturnType<typeof postApiMembershipExpire>>>
    
    export type PostApiMembershipExpireMutationError = unknown

    /**
 * @summary Expire memberships that are past due
 */
export const usePostApiMembershipExpire = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipExpire>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiMembershipExpire>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiMembershipExpireMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Compress inactive users and mark accounts deleted
 */
export const postApiMembershipCompress = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def19>(
      {url: `/api/membership/compress`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiMembershipCompressMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipCompress>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipCompress>>, TError,void, TContext> => {

const mutationKey = ['postApiMembershipCompress'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiMembershipCompress>>, void> = () => {
          

          return  postApiMembershipCompress(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiMembershipCompressMutationResult = NonNullable<Awaited<ReturnType<typeof postApiMembershipCompress>>>
    
    export type PostApiMembershipCompressMutationError = unknown

    /**
 * @summary Compress inactive users and mark accounts deleted
 */
export const usePostApiMembershipCompress = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMembershipCompress>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiMembershipCompress>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiMembershipCompressMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    