/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NexxaTrade API
 * API documentation for NexxaTrade
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Def10,
  Def9,
  DeleteApiWalletDestinationsId200,
  GetApiWalletDestinations200,
  GetApiWalletTransactions200,
  PostApiWalletDestinationsBody
} from '../generated.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get wallet summary for the current user
 */
export const getApiWalletSummary = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def9>(
      {url: `/api/wallet/summary`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiWalletSummaryQueryKey = () => {
    return [
    `/api/wallet/summary`
    ] as const;
    }

    
export const getGetApiWalletSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getApiWalletSummary>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWalletSummaryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWalletSummary>>> = ({ signal }) => getApiWalletSummary(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWalletSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWalletSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWalletSummary>>>
export type GetApiWalletSummaryQueryError = unknown


export function useGetApiWalletSummary<TData = Awaited<ReturnType<typeof getApiWalletSummary>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWalletSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiWalletSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWalletSummary<TData = Awaited<ReturnType<typeof getApiWalletSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWalletSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiWalletSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWalletSummary<TData = Awaited<ReturnType<typeof getApiWalletSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get wallet summary for the current user
 */

export function useGetApiWalletSummary<TData = Awaited<ReturnType<typeof getApiWalletSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWalletSummaryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List saved withdrawal destinations for the current user
 */
export const getApiWalletDestinations = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiWalletDestinations200>(
      {url: `/api/wallet/destinations`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiWalletDestinationsQueryKey = () => {
    return [
    `/api/wallet/destinations`
    ] as const;
    }

    
export const getGetApiWalletDestinationsQueryOptions = <TData = Awaited<ReturnType<typeof getApiWalletDestinations>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletDestinations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWalletDestinationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWalletDestinations>>> = ({ signal }) => getApiWalletDestinations(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWalletDestinations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWalletDestinationsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWalletDestinations>>>
export type GetApiWalletDestinationsQueryError = unknown


export function useGetApiWalletDestinations<TData = Awaited<ReturnType<typeof getApiWalletDestinations>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletDestinations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWalletDestinations>>,
          TError,
          Awaited<ReturnType<typeof getApiWalletDestinations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWalletDestinations<TData = Awaited<ReturnType<typeof getApiWalletDestinations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletDestinations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWalletDestinations>>,
          TError,
          Awaited<ReturnType<typeof getApiWalletDestinations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWalletDestinations<TData = Awaited<ReturnType<typeof getApiWalletDestinations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletDestinations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List saved withdrawal destinations for the current user
 */

export function useGetApiWalletDestinations<TData = Awaited<ReturnType<typeof getApiWalletDestinations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletDestinations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWalletDestinationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a saved withdrawal destination
 */
export const postApiWalletDestinations = (
    postApiWalletDestinationsBody: PostApiWalletDestinationsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def10>(
      {url: `/api/wallet/destinations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiWalletDestinationsBody, signal
    },
      options);
    }
  


export const getPostApiWalletDestinationsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWalletDestinations>>, TError,{data: PostApiWalletDestinationsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiWalletDestinations>>, TError,{data: PostApiWalletDestinationsBody}, TContext> => {

const mutationKey = ['postApiWalletDestinations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWalletDestinations>>, {data: PostApiWalletDestinationsBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiWalletDestinations(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiWalletDestinationsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWalletDestinations>>>
    export type PostApiWalletDestinationsMutationBody = PostApiWalletDestinationsBody
    export type PostApiWalletDestinationsMutationError = unknown

    /**
 * @summary Create a saved withdrawal destination
 */
export const usePostApiWalletDestinations = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWalletDestinations>>, TError,{data: PostApiWalletDestinationsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWalletDestinations>>,
        TError,
        {data: PostApiWalletDestinationsBody},
        TContext
      > => {

      const mutationOptions = getPostApiWalletDestinationsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a saved withdrawal destination
 */
export const deleteApiWalletDestinationsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteApiWalletDestinationsId200>(
      {url: `/api/wallet/destinations/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiWalletDestinationsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWalletDestinationsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiWalletDestinationsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiWalletDestinationsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiWalletDestinationsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiWalletDestinationsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiWalletDestinationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiWalletDestinationsId>>>
    
    export type DeleteApiWalletDestinationsIdMutationError = unknown

    /**
 * @summary Delete a saved withdrawal destination
 */
export const useDeleteApiWalletDestinationsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiWalletDestinationsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiWalletDestinationsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiWalletDestinationsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Set a saved withdrawal destination as default
 */
export const postApiWalletDestinationsIdDefault = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def10>(
      {url: `/api/wallet/destinations/${id}/default`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiWalletDestinationsIdDefaultMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWalletDestinationsIdDefault>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiWalletDestinationsIdDefault>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiWalletDestinationsIdDefault'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWalletDestinationsIdDefault>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiWalletDestinationsIdDefault(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiWalletDestinationsIdDefaultMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWalletDestinationsIdDefault>>>
    
    export type PostApiWalletDestinationsIdDefaultMutationError = unknown

    /**
 * @summary Set a saved withdrawal destination as default
 */
export const usePostApiWalletDestinationsIdDefault = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWalletDestinationsIdDefault>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWalletDestinationsIdDefault>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiWalletDestinationsIdDefaultMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List wallet transactions for the current user
 */
export const getApiWalletTransactions = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiWalletTransactions200>(
      {url: `/api/wallet/transactions`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiWalletTransactionsQueryKey = () => {
    return [
    `/api/wallet/transactions`
    ] as const;
    }

    
export const getGetApiWalletTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiWalletTransactions>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWalletTransactionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWalletTransactions>>> = ({ signal }) => getApiWalletTransactions(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWalletTransactions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWalletTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWalletTransactions>>>
export type GetApiWalletTransactionsQueryError = unknown


export function useGetApiWalletTransactions<TData = Awaited<ReturnType<typeof getApiWalletTransactions>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletTransactions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWalletTransactions>>,
          TError,
          Awaited<ReturnType<typeof getApiWalletTransactions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWalletTransactions<TData = Awaited<ReturnType<typeof getApiWalletTransactions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletTransactions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWalletTransactions>>,
          TError,
          Awaited<ReturnType<typeof getApiWalletTransactions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWalletTransactions<TData = Awaited<ReturnType<typeof getApiWalletTransactions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List wallet transactions for the current user
 */

export function useGetApiWalletTransactions<TData = Awaited<ReturnType<typeof getApiWalletTransactions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWalletTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWalletTransactionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




