/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NexxaTrade API
 * API documentation for NexxaTrade
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Def13,
  GetApiAdminWithdrawals200,
  GetApiAdminWithdrawalsParams,
  GetApiWithdrawals200,
  PostApiAdminWithdrawalsIdFailedBody,
  PostApiAdminWithdrawalsIdPaidBody,
  PostApiAdminWithdrawalsIdRejectBody,
  PostApiWithdrawalsBody
} from '../generated.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List withdrawal requests for the current user
 */
export const getApiWithdrawals = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiWithdrawals200>(
      {url: `/api/withdrawals`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiWithdrawalsQueryKey = () => {
    return [
    `/api/withdrawals`
    ] as const;
    }

    
export const getGetApiWithdrawalsQueryOptions = <TData = Awaited<ReturnType<typeof getApiWithdrawals>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWithdrawalsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWithdrawals>>> = ({ signal }) => getApiWithdrawals(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWithdrawals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWithdrawalsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWithdrawals>>>
export type GetApiWithdrawalsQueryError = unknown


export function useGetApiWithdrawals<TData = Awaited<ReturnType<typeof getApiWithdrawals>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWithdrawals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWithdrawals>>,
          TError,
          Awaited<ReturnType<typeof getApiWithdrawals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWithdrawals<TData = Awaited<ReturnType<typeof getApiWithdrawals>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWithdrawals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWithdrawals>>,
          TError,
          Awaited<ReturnType<typeof getApiWithdrawals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWithdrawals<TData = Awaited<ReturnType<typeof getApiWithdrawals>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List withdrawal requests for the current user
 */

export function useGetApiWithdrawals<TData = Awaited<ReturnType<typeof getApiWithdrawals>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWithdrawalsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a withdrawal request
 */
export const postApiWithdrawals = (
    postApiWithdrawalsBody: PostApiWithdrawalsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def13>(
      {url: `/api/withdrawals`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiWithdrawalsBody, signal
    },
      options);
    }
  


export const getPostApiWithdrawalsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWithdrawals>>, TError,{data: PostApiWithdrawalsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiWithdrawals>>, TError,{data: PostApiWithdrawalsBody}, TContext> => {

const mutationKey = ['postApiWithdrawals'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWithdrawals>>, {data: PostApiWithdrawalsBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiWithdrawals(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiWithdrawalsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWithdrawals>>>
    export type PostApiWithdrawalsMutationBody = PostApiWithdrawalsBody
    export type PostApiWithdrawalsMutationError = unknown

    /**
 * @summary Create a withdrawal request
 */
export const usePostApiWithdrawals = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWithdrawals>>, TError,{data: PostApiWithdrawalsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWithdrawals>>,
        TError,
        {data: PostApiWithdrawalsBody},
        TContext
      > => {

      const mutationOptions = getPostApiWithdrawalsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Cancel a pending withdrawal request
 */
export const postApiWithdrawalsIdCancel = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def13>(
      {url: `/api/withdrawals/${id}/cancel`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiWithdrawalsIdCancelMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWithdrawalsIdCancel>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiWithdrawalsIdCancel>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiWithdrawalsIdCancel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWithdrawalsIdCancel>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiWithdrawalsIdCancel(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiWithdrawalsIdCancelMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWithdrawalsIdCancel>>>
    
    export type PostApiWithdrawalsIdCancelMutationError = unknown

    /**
 * @summary Cancel a pending withdrawal request
 */
export const usePostApiWithdrawalsIdCancel = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWithdrawalsIdCancel>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWithdrawalsIdCancel>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiWithdrawalsIdCancelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List withdrawal requests (admin)
 */
export const getApiAdminWithdrawals = (
    params?: GetApiAdminWithdrawalsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiAdminWithdrawals200>(
      {url: `/api/admin/withdrawals`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiAdminWithdrawalsQueryKey = (params?: GetApiAdminWithdrawalsParams,) => {
    return [
    `/api/admin/withdrawals`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAdminWithdrawalsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminWithdrawals>>, TError = unknown>(params?: GetApiAdminWithdrawalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminWithdrawalsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminWithdrawals>>> = ({ signal }) => getApiAdminWithdrawals(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminWithdrawals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminWithdrawalsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminWithdrawals>>>
export type GetApiAdminWithdrawalsQueryError = unknown


export function useGetApiAdminWithdrawals<TData = Awaited<ReturnType<typeof getApiAdminWithdrawals>>, TError = unknown>(
 params: undefined |  GetApiAdminWithdrawalsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminWithdrawals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminWithdrawals>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminWithdrawals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminWithdrawals<TData = Awaited<ReturnType<typeof getApiAdminWithdrawals>>, TError = unknown>(
 params?: GetApiAdminWithdrawalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminWithdrawals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminWithdrawals>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminWithdrawals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminWithdrawals<TData = Awaited<ReturnType<typeof getApiAdminWithdrawals>>, TError = unknown>(
 params?: GetApiAdminWithdrawalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List withdrawal requests (admin)
 */

export function useGetApiAdminWithdrawals<TData = Awaited<ReturnType<typeof getApiAdminWithdrawals>>, TError = unknown>(
 params?: GetApiAdminWithdrawalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminWithdrawalsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Approve a withdrawal request (admin)
 */
export const postApiAdminWithdrawalsIdApprove = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def13>(
      {url: `/api/admin/withdrawals/${id}/approve`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiAdminWithdrawalsIdApproveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdApprove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdApprove>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiAdminWithdrawalsIdApprove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdApprove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminWithdrawalsIdApprove(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminWithdrawalsIdApproveMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdApprove>>>
    
    export type PostApiAdminWithdrawalsIdApproveMutationError = unknown

    /**
 * @summary Approve a withdrawal request (admin)
 */
export const usePostApiAdminWithdrawalsIdApprove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdApprove>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminWithdrawalsIdApprove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiAdminWithdrawalsIdApproveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Reject a withdrawal request (admin)
 */
export const postApiAdminWithdrawalsIdReject = (
    id: string,
    postApiAdminWithdrawalsIdRejectBody: PostApiAdminWithdrawalsIdRejectBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def13>(
      {url: `/api/admin/withdrawals/${id}/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAdminWithdrawalsIdRejectBody, signal
    },
      options);
    }
  


export const getPostApiAdminWithdrawalsIdRejectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdReject>>, TError,{id: string;data: PostApiAdminWithdrawalsIdRejectBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdReject>>, TError,{id: string;data: PostApiAdminWithdrawalsIdRejectBody}, TContext> => {

const mutationKey = ['postApiAdminWithdrawalsIdReject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdReject>>, {id: string;data: PostApiAdminWithdrawalsIdRejectBody}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiAdminWithdrawalsIdReject(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminWithdrawalsIdRejectMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdReject>>>
    export type PostApiAdminWithdrawalsIdRejectMutationBody = PostApiAdminWithdrawalsIdRejectBody
    export type PostApiAdminWithdrawalsIdRejectMutationError = unknown

    /**
 * @summary Reject a withdrawal request (admin)
 */
export const usePostApiAdminWithdrawalsIdReject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdReject>>, TError,{id: string;data: PostApiAdminWithdrawalsIdRejectBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminWithdrawalsIdReject>>,
        TError,
        {id: string;data: PostApiAdminWithdrawalsIdRejectBody},
        TContext
      > => {

      const mutationOptions = getPostApiAdminWithdrawalsIdRejectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Mark a withdrawal as processing (admin)
 */
export const postApiAdminWithdrawalsIdProcessing = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def13>(
      {url: `/api/admin/withdrawals/${id}/processing`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiAdminWithdrawalsIdProcessingMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdProcessing>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdProcessing>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiAdminWithdrawalsIdProcessing'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdProcessing>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminWithdrawalsIdProcessing(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminWithdrawalsIdProcessingMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdProcessing>>>
    
    export type PostApiAdminWithdrawalsIdProcessingMutationError = unknown

    /**
 * @summary Mark a withdrawal as processing (admin)
 */
export const usePostApiAdminWithdrawalsIdProcessing = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdProcessing>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminWithdrawalsIdProcessing>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiAdminWithdrawalsIdProcessingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Mark a withdrawal as paid (admin)
 */
export const postApiAdminWithdrawalsIdPaid = (
    id: string,
    postApiAdminWithdrawalsIdPaidBody: PostApiAdminWithdrawalsIdPaidBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def13>(
      {url: `/api/admin/withdrawals/${id}/paid`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAdminWithdrawalsIdPaidBody, signal
    },
      options);
    }
  


export const getPostApiAdminWithdrawalsIdPaidMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPaid>>, TError,{id: string;data: PostApiAdminWithdrawalsIdPaidBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPaid>>, TError,{id: string;data: PostApiAdminWithdrawalsIdPaidBody}, TContext> => {

const mutationKey = ['postApiAdminWithdrawalsIdPaid'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPaid>>, {id: string;data: PostApiAdminWithdrawalsIdPaidBody}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiAdminWithdrawalsIdPaid(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminWithdrawalsIdPaidMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPaid>>>
    export type PostApiAdminWithdrawalsIdPaidMutationBody = PostApiAdminWithdrawalsIdPaidBody
    export type PostApiAdminWithdrawalsIdPaidMutationError = unknown

    /**
 * @summary Mark a withdrawal as paid (admin)
 */
export const usePostApiAdminWithdrawalsIdPaid = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPaid>>, TError,{id: string;data: PostApiAdminWithdrawalsIdPaidBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPaid>>,
        TError,
        {id: string;data: PostApiAdminWithdrawalsIdPaidBody},
        TContext
      > => {

      const mutationOptions = getPostApiAdminWithdrawalsIdPaidMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Mark a withdrawal as failed (admin)
 */
export const postApiAdminWithdrawalsIdFailed = (
    id: string,
    postApiAdminWithdrawalsIdFailedBody: PostApiAdminWithdrawalsIdFailedBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def13>(
      {url: `/api/admin/withdrawals/${id}/failed`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAdminWithdrawalsIdFailedBody, signal
    },
      options);
    }
  


export const getPostApiAdminWithdrawalsIdFailedMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdFailed>>, TError,{id: string;data: PostApiAdminWithdrawalsIdFailedBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdFailed>>, TError,{id: string;data: PostApiAdminWithdrawalsIdFailedBody}, TContext> => {

const mutationKey = ['postApiAdminWithdrawalsIdFailed'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdFailed>>, {id: string;data: PostApiAdminWithdrawalsIdFailedBody}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiAdminWithdrawalsIdFailed(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminWithdrawalsIdFailedMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdFailed>>>
    export type PostApiAdminWithdrawalsIdFailedMutationBody = PostApiAdminWithdrawalsIdFailedBody
    export type PostApiAdminWithdrawalsIdFailedMutationError = unknown

    /**
 * @summary Mark a withdrawal as failed (admin)
 */
export const usePostApiAdminWithdrawalsIdFailed = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdFailed>>, TError,{id: string;data: PostApiAdminWithdrawalsIdFailedBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminWithdrawalsIdFailed>>,
        TError,
        {id: string;data: PostApiAdminWithdrawalsIdFailedBody},
        TContext
      > => {

      const mutationOptions = getPostApiAdminWithdrawalsIdFailedMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Trigger a payout via reserve (admin)
 */
export const postApiAdminWithdrawalsIdPayout = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def13>(
      {url: `/api/admin/withdrawals/${id}/payout`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiAdminWithdrawalsIdPayoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPayout>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPayout>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiAdminWithdrawalsIdPayout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPayout>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminWithdrawalsIdPayout(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminWithdrawalsIdPayoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPayout>>>
    
    export type PostApiAdminWithdrawalsIdPayoutMutationError = unknown

    /**
 * @summary Trigger a payout via reserve (admin)
 */
export const usePostApiAdminWithdrawalsIdPayout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPayout>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminWithdrawalsIdPayout>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiAdminWithdrawalsIdPayoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    