/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Better Auth
 * API Reference for your Better Auth Instance
 * OpenAPI spec version: 1.1.0
 */
export interface User {
  id?: string;
  name: string;
  email: string;
  readonly emailVerified?: boolean;
  image?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Session {
  id?: string;
  expiresAt: string;
  token: string;
  createdAt: string;
  updatedAt: string;
  ipAddress?: string;
  userAgent?: string;
  userId: string;
}

export interface Account {
  id?: string;
  accountId: string;
  providerId: string;
  userId: string;
  accessToken?: string;
  refreshToken?: string;
  idToken?: string;
  accessTokenExpiresAt?: string;
  refreshTokenExpiresAt?: string;
  scope?: string;
  password?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Verification {
  id?: string;
  identifier: string;
  value: string;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Callback URL to redirect to after the user has signed in
 */
export type SocialSignInBodyCallbackURL = string | null;

export type SocialSignInBodyNewUserCallbackURL = string | null;

/**
 * Callback URL to redirect to if an error happens
 */
export type SocialSignInBodyErrorCallbackURL = string | null;

/**
 * Disable automatic redirection to the provider. Useful for handling the redirection yourself
 */
export type SocialSignInBodyDisableRedirect = boolean | null;

/**
 * Nonce used to generate the token
 */
export type SocialSignInBodyIdTokenAnyOfNonce = string | null;

/**
 * Access token from the provider
 */
export type SocialSignInBodyIdTokenAnyOfAccessToken = string | null;

/**
 * Refresh token from the provider
 */
export type SocialSignInBodyIdTokenAnyOfRefreshToken = string | null;

/**
 * Expiry date of the token
 */
export type SocialSignInBodyIdTokenAnyOfExpiresAt = number | null;

export type SocialSignInBodyIdTokenAnyOf = {
  /** ID token from the provider */
  token: string;
  /** Nonce used to generate the token */
  nonce?: SocialSignInBodyIdTokenAnyOfNonce;
  /** Access token from the provider */
  accessToken?: SocialSignInBodyIdTokenAnyOfAccessToken;
  /** Refresh token from the provider */
  refreshToken?: SocialSignInBodyIdTokenAnyOfRefreshToken;
  /** Expiry date of the token */
  expiresAt?: SocialSignInBodyIdTokenAnyOfExpiresAt;
};

export type SocialSignInBodyIdToken = SocialSignInBodyIdTokenAnyOf | null;

/**
 * Array of scopes to request from the provider. This will override the default scopes passed.
 */
export type SocialSignInBodyScopes = unknown[] | null;

/**
 * Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider
 */
export type SocialSignInBodyRequestSignUp = boolean | null;

/**
 * The login hint to use for the authorization code request
 */
export type SocialSignInBodyLoginHint = string | null;

export type SocialSignInBodyAdditionalData = string | null;

export type SocialSignInBody = {
  /** Callback URL to redirect to after the user has signed in */
  callbackURL?: SocialSignInBodyCallbackURL;
  newUserCallbackURL?: SocialSignInBodyNewUserCallbackURL;
  /** Callback URL to redirect to if an error happens */
  errorCallbackURL?: SocialSignInBodyErrorCallbackURL;
  provider: string;
  /** Disable automatic redirection to the provider. Useful for handling the redirection yourself */
  disableRedirect?: SocialSignInBodyDisableRedirect;
  idToken?: SocialSignInBodyIdToken;
  /** Array of scopes to request from the provider. This will override the default scopes passed. */
  scopes?: SocialSignInBodyScopes;
  /** Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider */
  requestSignUp?: SocialSignInBodyRequestSignUp;
  /** The login hint to use for the authorization code request */
  loginHint?: SocialSignInBodyLoginHint;
  additionalData?: SocialSignInBodyAdditionalData;
};

/**
 * Session response when idToken is provided
 */
export type SocialSignIn200 = {
  token: string;
  user: User;
  url?: string;
  redirect: boolean;
};

export type SocialSignIn400 = {
  message: string;
};

export type SocialSignIn401 = {
  message: string;
};

export type SocialSignIn403 = {
  message?: string;
};

export type SocialSignIn404 = {
  message?: string;
};

export type SocialSignIn429 = {
  message?: string;
};

export type SocialSignIn500 = {
  message?: string;
};

/**
 * @nullable
 */
export type GetSession200 = {
  session: Session;
  user: User;
} | null;

export type GetSession400 = {
  message: string;
};

export type GetSession401 = {
  message: string;
};

export type GetSession403 = {
  message?: string;
};

export type GetSession404 = {
  message?: string;
};

export type GetSession429 = {
  message?: string;
};

export type GetSession500 = {
  message?: string;
};

export type SignOutBody = { [key: string]: unknown };

export type SignOut200 = {
  success?: boolean;
};

export type SignOut400 = {
  message: string;
};

export type SignOut401 = {
  message: string;
};

export type SignOut403 = {
  message?: string;
};

export type SignOut404 = {
  message?: string;
};

export type SignOut429 = {
  message?: string;
};

export type SignOut500 = {
  message?: string;
};

export type SignUpWithEmailAndPasswordBody = {
  /** The name of the user */
  name: string;
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
  /** The profile image URL of the user */
  image?: string;
  /** The URL to use for email verification callback */
  callbackURL?: string;
  /** If this is false, the session will not be remembered. Default is `true`. */
  rememberMe?: boolean;
};

export type SignUpWithEmailAndPassword200User = {
  /** The unique identifier of the user */
  id: string;
  /** The email address of the user */
  email: string;
  /** The name of the user */
  name: string;
  /**
   * The profile image URL of the user
   * @nullable
   */
  image?: string | null;
  /** Whether the email has been verified */
  emailVerified: boolean;
  /** When the user was created */
  createdAt: string;
  /** When the user was last updated */
  updatedAt: string;
};

export type SignUpWithEmailAndPassword200 = {
  /**
   * Authentication token for the session
   * @nullable
   */
  token?: string | null;
  user: SignUpWithEmailAndPassword200User;
};

export type SignUpWithEmailAndPassword400 = {
  message: string;
};

export type SignUpWithEmailAndPassword401 = {
  message: string;
};

export type SignUpWithEmailAndPassword403 = {
  message?: string;
};

export type SignUpWithEmailAndPassword404 = {
  message?: string;
};

export type SignUpWithEmailAndPassword422 = {
  message?: string;
};

export type SignUpWithEmailAndPassword429 = {
  message?: string;
};

export type SignUpWithEmailAndPassword500 = {
  message?: string;
};

/**
 * Callback URL to use as a redirect for email verification
 */
export type SignInEmailBodyCallbackURL = string | null;

export type SignInEmailBodyRememberMe = string | null;

export type SignInEmailBody = {
  /** Email of the user */
  email: string;
  /** Password of the user */
  password: string;
  /** Callback URL to use as a redirect for email verification */
  callbackURL?: SignInEmailBodyCallbackURL;
  rememberMe?: SignInEmailBodyRememberMe;
};

/**
 * Session response when idToken is provided
 */
export type SignInEmail200 = {
  redirect: boolean;
  /** Session token */
  token: string;
  /** @nullable */
  url?: string | null;
  user: User;
};

export type SignInEmail400 = {
  message: string;
};

export type SignInEmail401 = {
  message: string;
};

export type SignInEmail403 = {
  message?: string;
};

export type SignInEmail404 = {
  message?: string;
};

export type SignInEmail429 = {
  message?: string;
};

export type SignInEmail500 = {
  message?: string;
};

/**
 * The token to reset the password
 */
export type ResetPasswordBodyToken = string | null;

export type ResetPasswordBody = {
  /** The new password to set */
  newPassword: string;
  /** The token to reset the password */
  token?: ResetPasswordBodyToken;
};

export type ResetPassword200 = {
  status?: boolean;
};

export type ResetPassword400 = {
  message: string;
};

export type ResetPassword401 = {
  message: string;
};

export type ResetPassword403 = {
  message?: string;
};

export type ResetPassword404 = {
  message?: string;
};

export type ResetPassword429 = {
  message?: string;
};

export type ResetPassword500 = {
  message?: string;
};

export type GetVerifyEmailParams = {
/**
 * The token to verify the email
 */
token: string;
/**
 * The URL to redirect to after email verification
 */
callbackURL?: string;
};

export type GetVerifyEmail200 = {
  user: User;
  /** Indicates if the email was verified successfully */
  status: boolean;
};

export type GetVerifyEmail400 = {
  message: string;
};

export type GetVerifyEmail401 = {
  message: string;
};

export type GetVerifyEmail403 = {
  message?: string;
};

export type GetVerifyEmail404 = {
  message?: string;
};

export type GetVerifyEmail429 = {
  message?: string;
};

export type GetVerifyEmail500 = {
  message?: string;
};

export type SendVerificationEmailBody = {
  /** The email to send the verification email to */
  email: string;
  /**
   * The URL to use for email verification callback
   * @nullable
   */
  callbackURL?: string | null;
};

export type SendVerificationEmail200 = {
  /** Indicates if the email was sent successfully */
  status?: boolean;
};

export type SendVerificationEmail400 = {
  /** Error message */
  message?: string;
};

export type SendVerificationEmail401 = {
  message: string;
};

export type SendVerificationEmail403 = {
  message?: string;
};

export type SendVerificationEmail404 = {
  message?: string;
};

export type SendVerificationEmail429 = {
  message?: string;
};

export type SendVerificationEmail500 = {
  message?: string;
};

/**
 * The URL to redirect to after email verification
 */
export type ChangeEmailBodyCallbackURL = string | null;

export type ChangeEmailBody = {
  /** The new email address to set must be a valid email address */
  newEmail: string;
  /** The URL to redirect to after email verification */
  callbackURL?: ChangeEmailBodyCallbackURL;
};

/**
 * Status message of the email change process
 * @nullable
 */
export type ChangeEmail200Message = typeof ChangeEmail200Message[keyof typeof ChangeEmail200Message] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeEmail200Message = {
  Email_updated: 'Email updated',
  Verification_email_sent: 'Verification email sent',
} as const;

export type ChangeEmail200 = {
  user?: User;
  /** Indicates if the request was successful */
  status: boolean;
  /**
   * Status message of the email change process
   * @nullable
   */
  message?: ChangeEmail200Message;
};

export type ChangeEmail400 = {
  message: string;
};

export type ChangeEmail401 = {
  message: string;
};

export type ChangeEmail403 = {
  message?: string;
};

export type ChangeEmail404 = {
  message?: string;
};

export type ChangeEmail422 = {
  message?: string;
};

export type ChangeEmail429 = {
  message?: string;
};

export type ChangeEmail500 = {
  message?: string;
};

/**
 * Must be a boolean value
 */
export type ChangePasswordBodyRevokeOtherSessions = boolean | null;

export type ChangePasswordBody = {
  /** The new password to set */
  newPassword: string;
  /** The current password is required */
  currentPassword: string;
  /** Must be a boolean value */
  revokeOtherSessions?: ChangePasswordBodyRevokeOtherSessions;
};

export type ChangePassword200User = {
  /** The unique identifier of the user */
  id: string;
  /** The email address of the user */
  email: string;
  /** The name of the user */
  name: string;
  /**
   * The profile image URL of the user
   * @nullable
   */
  image?: string | null;
  /** Whether the email has been verified */
  emailVerified: boolean;
  /** When the user was created */
  createdAt: string;
  /** When the user was last updated */
  updatedAt: string;
};

export type ChangePassword200 = {
  /**
   * New session token if other sessions were revoked
   * @nullable
   */
  token?: string | null;
  user: ChangePassword200User;
};

export type ChangePassword400 = {
  message: string;
};

export type ChangePassword401 = {
  message: string;
};

export type ChangePassword403 = {
  message?: string;
};

export type ChangePassword404 = {
  message?: string;
};

export type ChangePassword429 = {
  message?: string;
};

export type ChangePassword500 = {
  message?: string;
};

export type UpdateUserBody = {
  /** The name of the user */
  name?: string;
  /**
   * The image of the user
   * @nullable
   */
  image?: string | null;
};

export type UpdateUser200 = {
  user?: User;
};

export type UpdateUser400 = {
  message: string;
};

export type UpdateUser401 = {
  message: string;
};

export type UpdateUser403 = {
  message?: string;
};

export type UpdateUser404 = {
  message?: string;
};

export type UpdateUser429 = {
  message?: string;
};

export type UpdateUser500 = {
  message?: string;
};

export type DeleteUserBody = {
  /** The callback URL to redirect to after the user is deleted */
  callbackURL?: string;
  /** The user's password. Required if session is not fresh */
  password?: string;
  /** The deletion verification token */
  token?: string;
};

/**
 * Status message of the deletion process
 */
export type DeleteUser200Message = typeof DeleteUser200Message[keyof typeof DeleteUser200Message];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteUser200Message = {
  User_deleted: 'User deleted',
  Verification_email_sent: 'Verification email sent',
} as const;

export type DeleteUser200 = {
  /** Indicates if the operation was successful */
  success: boolean;
  /** Status message of the deletion process */
  message: DeleteUser200Message;
};

export type DeleteUser400 = {
  message: string;
};

export type DeleteUser401 = {
  message: string;
};

export type DeleteUser403 = {
  message?: string;
};

export type DeleteUser404 = {
  message?: string;
};

export type DeleteUser429 = {
  message?: string;
};

export type DeleteUser500 = {
  message?: string;
};

/**
 * The URL to redirect the user to reset their password. If the token isn't valid or expired, it'll be redirected with a query parameter `?error=INVALID_TOKEN`. If the token is valid, it'll be redirected with a query parameter `?token=VALID_TOKEN
 */
export type RequestPasswordResetBodyRedirectTo = string | null;

export type RequestPasswordResetBody = {
  /** The email address of the user to send a password reset email to */
  email: string;
  /** The URL to redirect the user to reset their password. If the token isn't valid or expired, it'll be redirected with a query parameter `?error=INVALID_TOKEN`. If the token is valid, it'll be redirected with a query parameter `?token=VALID_TOKEN */
  redirectTo?: RequestPasswordResetBodyRedirectTo;
};

export type RequestPasswordReset200 = {
  status?: boolean;
  message?: string;
};

export type RequestPasswordReset400 = {
  message: string;
};

export type RequestPasswordReset401 = {
  message: string;
};

export type RequestPasswordReset403 = {
  message?: string;
};

export type RequestPasswordReset404 = {
  message?: string;
};

export type RequestPasswordReset429 = {
  message?: string;
};

export type RequestPasswordReset500 = {
  message?: string;
};

export type ResetPasswordCallbackParams = {
/**
 * The URL to redirect the user to reset their password
 */
callbackURL: string;
};

export type ResetPasswordCallback200 = {
  token?: string;
};

export type ResetPasswordCallback400 = {
  message: string;
};

export type ResetPasswordCallback401 = {
  message: string;
};

export type ResetPasswordCallback403 = {
  message?: string;
};

export type ResetPasswordCallback404 = {
  message?: string;
};

export type ResetPasswordCallback429 = {
  message?: string;
};

export type ResetPasswordCallback500 = {
  message?: string;
};

export type ListUserSessions400 = {
  message: string;
};

export type ListUserSessions401 = {
  message: string;
};

export type ListUserSessions403 = {
  message?: string;
};

export type ListUserSessions404 = {
  message?: string;
};

export type ListUserSessions429 = {
  message?: string;
};

export type ListUserSessions500 = {
  message?: string;
};

export type PostRevokeSessionBody = {
  /** The token to revoke */
  token: string;
};

export type PostRevokeSession200 = {
  /** Indicates if the session was revoked successfully */
  status: boolean;
};

export type PostRevokeSession400 = {
  message: string;
};

export type PostRevokeSession401 = {
  message: string;
};

export type PostRevokeSession403 = {
  message?: string;
};

export type PostRevokeSession404 = {
  message?: string;
};

export type PostRevokeSession429 = {
  message?: string;
};

export type PostRevokeSession500 = {
  message?: string;
};

export type PostRevokeSessionsBody = { [key: string]: unknown };

export type PostRevokeSessions200 = {
  /** Indicates if all sessions were revoked successfully */
  status: boolean;
};

export type PostRevokeSessions400 = {
  message: string;
};

export type PostRevokeSessions401 = {
  message: string;
};

export type PostRevokeSessions403 = {
  message?: string;
};

export type PostRevokeSessions404 = {
  message?: string;
};

export type PostRevokeSessions429 = {
  message?: string;
};

export type PostRevokeSessions500 = {
  message?: string;
};

export type PostRevokeOtherSessionsBody = { [key: string]: unknown };

export type PostRevokeOtherSessions200 = {
  /** Indicates if all other sessions were revoked successfully */
  status: boolean;
};

export type PostRevokeOtherSessions400 = {
  message: string;
};

export type PostRevokeOtherSessions401 = {
  message: string;
};

export type PostRevokeOtherSessions403 = {
  message?: string;
};

export type PostRevokeOtherSessions404 = {
  message?: string;
};

export type PostRevokeOtherSessions429 = {
  message?: string;
};

export type PostRevokeOtherSessions500 = {
  message?: string;
};

/**
 * The URL to redirect to after the user has signed in
 */
export type LinkSocialAccountBodyCallbackURL = string | null;

export type LinkSocialAccountBodyIdTokenAnyOfNonce = string | null;

export type LinkSocialAccountBodyIdTokenAnyOfAccessToken = string | null;

export type LinkSocialAccountBodyIdTokenAnyOfRefreshToken = string | null;

export type LinkSocialAccountBodyIdTokenAnyOfScopes = unknown[] | null;

export type LinkSocialAccountBodyIdTokenAnyOf = {
  token: string;
  nonce?: LinkSocialAccountBodyIdTokenAnyOfNonce;
  accessToken?: LinkSocialAccountBodyIdTokenAnyOfAccessToken;
  refreshToken?: LinkSocialAccountBodyIdTokenAnyOfRefreshToken;
  scopes?: LinkSocialAccountBodyIdTokenAnyOfScopes;
};

export type LinkSocialAccountBodyIdToken = LinkSocialAccountBodyIdTokenAnyOf | null;

export type LinkSocialAccountBodyRequestSignUp = boolean | null;

/**
 * Additional scopes to request from the provider
 */
export type LinkSocialAccountBodyScopes = unknown[] | null;

/**
 * The URL to redirect to if there is an error during the link process
 */
export type LinkSocialAccountBodyErrorCallbackURL = string | null;

/**
 * Disable automatic redirection to the provider. Useful for handling the redirection yourself
 */
export type LinkSocialAccountBodyDisableRedirect = boolean | null;

export type LinkSocialAccountBodyAdditionalData = string | null;

export type LinkSocialAccountBody = {
  /** The URL to redirect to after the user has signed in */
  callbackURL?: LinkSocialAccountBodyCallbackURL;
  provider: string;
  idToken?: LinkSocialAccountBodyIdToken;
  requestSignUp?: LinkSocialAccountBodyRequestSignUp;
  /** Additional scopes to request from the provider */
  scopes?: LinkSocialAccountBodyScopes;
  /** The URL to redirect to if there is an error during the link process */
  errorCallbackURL?: LinkSocialAccountBodyErrorCallbackURL;
  /** Disable automatic redirection to the provider. Useful for handling the redirection yourself */
  disableRedirect?: LinkSocialAccountBodyDisableRedirect;
  additionalData?: LinkSocialAccountBodyAdditionalData;
};

export type LinkSocialAccount200 = {
  /** The authorization URL to redirect the user to */
  url?: string;
  /** Indicates if the user should be redirected to the authorization URL */
  redirect: boolean;
  status?: boolean;
};

export type LinkSocialAccount400 = {
  message: string;
};

export type LinkSocialAccount401 = {
  message: string;
};

export type LinkSocialAccount403 = {
  message?: string;
};

export type LinkSocialAccount404 = {
  message?: string;
};

export type LinkSocialAccount429 = {
  message?: string;
};

export type LinkSocialAccount500 = {
  message?: string;
};

export type ListUserAccounts200Item = {
  id: string;
  providerId: string;
  createdAt: string;
  updatedAt: string;
  accountId: string;
  userId: string;
  scopes: string[];
};

export type ListUserAccounts400 = {
  message: string;
};

export type ListUserAccounts401 = {
  message: string;
};

export type ListUserAccounts403 = {
  message?: string;
};

export type ListUserAccounts404 = {
  message?: string;
};

export type ListUserAccounts429 = {
  message?: string;
};

export type ListUserAccounts500 = {
  message?: string;
};

export type GetDeleteUserCallbackParams = {
/**
 * The token to verify the deletion request
 */
token?: string;
/**
 * The URL to redirect to after deletion
 */
callbackURL?: string | null;
};

/**
 * Confirmation message
 */
export type GetDeleteUserCallback200Message = typeof GetDeleteUserCallback200Message[keyof typeof GetDeleteUserCallback200Message];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetDeleteUserCallback200Message = {
  User_deleted: 'User deleted',
} as const;

export type GetDeleteUserCallback200 = {
  /** Indicates if the deletion was successful */
  success: boolean;
  /** Confirmation message */
  message: GetDeleteUserCallback200Message;
};

export type GetDeleteUserCallback400 = {
  message: string;
};

export type GetDeleteUserCallback401 = {
  message: string;
};

export type GetDeleteUserCallback403 = {
  message?: string;
};

export type GetDeleteUserCallback404 = {
  message?: string;
};

export type GetDeleteUserCallback429 = {
  message?: string;
};

export type GetDeleteUserCallback500 = {
  message?: string;
};

export type PostUnlinkAccountBodyAccountId = string | null;

export type PostUnlinkAccountBody = {
  providerId: string;
  accountId?: PostUnlinkAccountBodyAccountId;
};

export type PostUnlinkAccount200 = {
  status?: boolean;
};

export type PostUnlinkAccount400 = {
  message: string;
};

export type PostUnlinkAccount401 = {
  message: string;
};

export type PostUnlinkAccount403 = {
  message?: string;
};

export type PostUnlinkAccount404 = {
  message?: string;
};

export type PostUnlinkAccount429 = {
  message?: string;
};

export type PostUnlinkAccount500 = {
  message?: string;
};

/**
 * The account ID associated with the refresh token
 */
export type PostRefreshTokenBodyAccountId = string | null;

/**
 * The user ID associated with the account
 */
export type PostRefreshTokenBodyUserId = string | null;

export type PostRefreshTokenBody = {
  /** The provider ID for the OAuth provider */
  providerId: string;
  /** The account ID associated with the refresh token */
  accountId?: PostRefreshTokenBodyAccountId;
  /** The user ID associated with the account */
  userId?: PostRefreshTokenBodyUserId;
};

export type PostRefreshToken200 = {
  tokenType?: string;
  idToken?: string;
  accessToken?: string;
  refreshToken?: string;
  accessTokenExpiresAt?: string;
  refreshTokenExpiresAt?: string;
};

export type PostRefreshToken401 = {
  message: string;
};

export type PostRefreshToken403 = {
  message?: string;
};

export type PostRefreshToken404 = {
  message?: string;
};

export type PostRefreshToken429 = {
  message?: string;
};

export type PostRefreshToken500 = {
  message?: string;
};

/**
 * The account ID associated with the refresh token
 */
export type PostGetAccessTokenBodyAccountId = string | null;

/**
 * The user ID associated with the account
 */
export type PostGetAccessTokenBodyUserId = string | null;

export type PostGetAccessTokenBody = {
  /** The provider ID for the OAuth provider */
  providerId: string;
  /** The account ID associated with the refresh token */
  accountId?: PostGetAccessTokenBodyAccountId;
  /** The user ID associated with the account */
  userId?: PostGetAccessTokenBodyUserId;
};

export type PostGetAccessToken200 = {
  tokenType?: string;
  idToken?: string;
  accessToken?: string;
  refreshToken?: string;
  accessTokenExpiresAt?: string;
  refreshTokenExpiresAt?: string;
};

export type PostGetAccessToken401 = {
  message: string;
};

export type PostGetAccessToken403 = {
  message?: string;
};

export type PostGetAccessToken404 = {
  message?: string;
};

export type PostGetAccessToken429 = {
  message?: string;
};

export type PostGetAccessToken500 = {
  message?: string;
};

export type GetAccountInfo200User = {
  id: string;
  name?: string;
  email?: string;
  image?: string;
  emailVerified: boolean;
};

export type GetAccountInfo200Data = { [key: string]: unknown };

export type GetAccountInfo200 = {
  user: GetAccountInfo200User;
  data: GetAccountInfo200Data;
};

export type GetAccountInfo400 = {
  message: string;
};

export type GetAccountInfo401 = {
  message: string;
};

export type GetAccountInfo403 = {
  message?: string;
};

export type GetAccountInfo404 = {
  message?: string;
};

export type GetAccountInfo429 = {
  message?: string;
};

export type GetAccountInfo500 = {
  message?: string;
};

export type GetOk200 = {
  /** Indicates if the API is working */
  ok: boolean;
};

export type GetOk400 = {
  message: string;
};

export type GetOk401 = {
  message: string;
};

export type GetOk403 = {
  message?: string;
};

export type GetOk404 = {
  message?: string;
};

export type GetOk429 = {
  message?: string;
};

export type GetOk500 = {
  message?: string;
};

export type GetError400 = {
  message: string;
};

export type GetError401 = {
  message: string;
};

export type GetError403 = {
  message?: string;
};

export type GetError404 = {
  message?: string;
};

export type GetError429 = {
  message?: string;
};

export type GetError500 = {
  message?: string;
};

