/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NexxaTrade API
 * API documentation for NexxaTrade
 * OpenAPI spec version: 1.0.0
 */
export type Def0 = typeof Def0[keyof typeof Def0];


export const Def0 = {
  admin: 'admin',
  guest: 'guest',
  subscriber: 'subscriber',
  networker: 'networker',
} as const;

export type Def1 = typeof Def1[keyof typeof Def1];


export const Def1 = {
  trial_weekly: 'trial_weekly',
  annual: 'annual',
  lifetime: 'lifetime',
} as const;

export type Def2 = typeof Def2[keyof typeof Def2];


export const Def2 = {
  active: 'active',
  inactive: 'inactive',
  deleted: 'deleted',
} as const;

export type Def3 = typeof Def3[keyof typeof Def3];


export const Def3 = {
  pending: 'pending',
  confirmed: 'confirmed',
  failed: 'failed',
} as const;

export interface Def4 {
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  /** @nullable */
  image?: string | null;
  role: Def0;
  membershipStatus: Def2;
  membershipTier?: Def1;
  /** @nullable */
  membershipExpiresAt?: string | null;
  createdAt: string;
  updatedAt: string;
  membership?: Def5;
  referral?: Def9;
}

export interface Def5 {
  userId: string;
  tier: Def1;
  status: Def2;
  startsAt: string;
  /** @nullable */
  activatedAt?: string | null;
  /** @nullable */
  expiresAt?: string | null;
  /** @nullable */
  inactiveAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Def6 {
  id: string;
  userId: string;
  fromStatus?: Def2;
  toStatus: Def2;
  /** @nullable */
  reason?: string | null;
  createdAt: string;
}

export interface Def7 {
  id: string;
  userId: string;
  tier: Def1;
  status: Def3;
  amountUsdCents: number;
  /** @nullable */
  chain?: string | null;
  /** @nullable */
  txHash?: string | null;
  /** @nullable */
  fromAddress?: string | null;
  /** @nullable */
  toAddress?: string | null;
  createdAt: string;
  /** @nullable */
  confirmedAt?: string | null;
}

export interface Def8 {
  id: string;
  paymentId: string;
  fromUserId: string;
  toUserId: string;
  level: number;
  amountUsdCents: number;
  createdAt: string;
}

export interface Def9 {
  userId: string;
  /** @nullable */
  sponsorId?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Def10 {
  id: string;
  expiresAt: string;
  token: string;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  ipAddress?: string | null;
  /** @nullable */
  userAgent?: string | null;
  userId: string;
}

export interface Def11 {
  id: string;
  accountId: string;
  providerId: string;
  userId: string;
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  /** @nullable */
  idToken?: string | null;
  /** @nullable */
  accessTokenExpiresAt?: string | null;
  /** @nullable */
  refreshTokenExpiresAt?: string | null;
  /** @nullable */
  scope?: string | null;
  /** @nullable */
  password?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Def12 {
  id: string;
  identifier: string;
  value: string;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Def13 {
  tier: Def1;
  priceUsdCents: number;
  /** @nullable */
  durationDays?: number | null;
}

export interface Def14 {
  tiers: Def13[];
}

export interface Def15 {
  userId: string;
  status: Def2;
  tier?: Def1;
  /** @nullable */
  expiresAt?: string | null;
  /** @nullable */
  inactiveAt?: string | null;
  /** @nullable */
  activatedAt?: string | null;
}

export interface Def16 {
  userId: string;
  tier: Def1;
  amountUsdCents: number;
  paymentId?: string;
  txHash?: string;
  chain?: string;
  fromAddress?: string;
  toAddress?: string;
  reason?: string;
}

export interface Def17 {
  paymentId: string;
  status: Def2;
  commissionsCreated: number;
  /** @nullable */
  expiresAt?: string | null;
}

export interface Def18 {
  expiredCount: number;
}

export interface Def19 {
  compressedCount: number;
}

export type UserRole = typeof UserRole[keyof typeof UserRole];


export const UserRole = {
  admin: 'admin',
  guest: 'guest',
  subscriber: 'subscriber',
  networker: 'networker',
} as const;

export interface User {
  id?: string;
  name: string;
  email: string;
  readonly emailVerified?: boolean;
  image?: string;
  createdAt: string;
  updatedAt: string;
  readonly role?: UserRole;
  readonly banned?: boolean;
  readonly banReason?: string;
  readonly banExpires?: string;
  readonly twoFactorEnabled?: boolean;
  readonly membershipStatus?: string;
  readonly membershipTier?: string;
  readonly membershipExpiresAt?: string;
}

export interface Session {
  id?: string;
  expiresAt: string;
  token: string;
  createdAt: string;
  updatedAt: string;
  ipAddress?: string;
  userAgent?: string;
  userId: string;
  impersonatedBy?: string;
}

export interface Account {
  id?: string;
  accountId: string;
  providerId: string;
  userId: string;
  accessToken?: string;
  refreshToken?: string;
  idToken?: string;
  accessTokenExpiresAt?: string;
  refreshTokenExpiresAt?: string;
  scope?: string;
  password?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Verification {
  id?: string;
  identifier: string;
  value: string;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface TwoFactor {
  id?: string;
  secret: string;
  backupCodes: string;
  userId: string;
}

export type GetHealth200 = {
  ok?: boolean;
  timestamp?: string;
};

export type GetHealthReady200 = {
  ok?: boolean;
  timestamp?: string;
  database?: string;
  error?: string;
};

export type PostApiAuthChangeEmailOtpBody = {
  newEmail: string;
};

export type PostApiAuthChangeEmailOtp200 = {
  message?: string;
};

export type PostApiAuthTwoFactorDisableBody = {
  /** User password */
  password: string;
};

export type PostApiAuthTwoFactorDisable200 = {
  status?: boolean;
};

export type PostApiAuthTwoFactorDisable400 = {
  message: string;
};

export type PostApiAuthTwoFactorDisable401 = {
  message: string;
};

export type PostApiAuthTwoFactorDisable403 = {
  message?: string;
};

export type PostApiAuthTwoFactorDisable404 = {
  message?: string;
};

export type PostApiAuthTwoFactorDisable429 = {
  message?: string;
};

export type PostApiAuthTwoFactorDisable500 = {
  message?: string;
};

export type PostApiAuthVerifyChangeEmailOtpBody = {
  newEmail: string;
  otpCode: string;
};

export type PostApiAuthVerifyChangeEmailOtp200 = {
  message?: string;
};

export type GetApiAuthApiDocsOpenapiJson200 = { [key: string]: unknown };

export type ListUserSessions400 = {
  message: string;
};

export type ListUserSessions401 = {
  message: string;
};

export type ListUserSessions403 = {
  message?: string;
};

export type ListUserSessions404 = {
  message?: string;
};

export type ListUserSessions429 = {
  message?: string;
};

export type ListUserSessions500 = {
  message?: string;
};

/**
 * @nullable
 */
export type SocialSignInBodyIdToken = {
  /** ID token from the provider */
  token: string;
  /**
   * Nonce used to generate the token
   * @nullable
   */
  nonce?: string | null;
  /**
   * Access token from the provider
   * @nullable
   */
  accessToken?: string | null;
  /**
   * Refresh token from the provider
   * @nullable
   */
  refreshToken?: string | null;
  /**
   * Expiry date of the token
   * @nullable
   */
  expiresAt?: number | null;
} | null;

export type SocialSignInBody = {
  /**
   * Callback URL to redirect to after the user has signed in
   * @nullable
   */
  callbackURL?: string | null;
  /** @nullable */
  newUserCallbackURL?: string | null;
  /**
   * Callback URL to redirect to if an error happens
   * @nullable
   */
  errorCallbackURL?: string | null;
  provider: string;
  /**
   * Disable automatic redirection to the provider. Useful for handling the redirection yourself
   * @nullable
   */
  disableRedirect?: boolean | null;
  /** @nullable */
  idToken?: SocialSignInBodyIdToken;
  /**
   * Array of scopes to request from the provider. This will override the default scopes passed.
   * @nullable
   */
  scopes?: unknown[] | null;
  /**
   * Explicitly request sign-up. Useful when disableImplicitSignUp is true for this provider
   * @nullable
   */
  requestSignUp?: boolean | null;
  /**
   * The login hint to use for the authorization code request
   * @nullable
   */
  loginHint?: string | null;
  /** @nullable */
  additionalData?: string | null;
};

/**
 * Session response when idToken is provided
 */
export type SocialSignIn200 = {
  token: string;
  user: User;
  url?: string;
  redirect: boolean;
};

export type SocialSignIn400 = {
  message: string;
};

export type SocialSignIn401 = {
  message: string;
};

export type SocialSignIn403 = {
  message?: string;
};

export type SocialSignIn404 = {
  message?: string;
};

export type SocialSignIn429 = {
  message?: string;
};

export type SocialSignIn500 = {
  message?: string;
};

/**
 * @nullable
 */
export type GetSession200 = {
  session: Session;
  user: User;
} | null;

export type GetSession400 = {
  message: string;
};

export type GetSession401 = {
  message: string;
};

export type GetSession403 = {
  message?: string;
};

export type GetSession404 = {
  message?: string;
};

export type GetSession429 = {
  message?: string;
};

export type GetSession500 = {
  message?: string;
};

export type SignOutBody = { [key: string]: unknown };

export type SignOut200 = {
  success?: boolean;
};

export type SignOut400 = {
  message: string;
};

export type SignOut401 = {
  message: string;
};

export type SignOut403 = {
  message?: string;
};

export type SignOut404 = {
  message?: string;
};

export type SignOut429 = {
  message?: string;
};

export type SignOut500 = {
  message?: string;
};

export type SignUpWithEmailAndPasswordBody = {
  /** The name of the user */
  name: string;
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
  /** The profile image URL of the user */
  image?: string;
  /** The URL to use for email verification callback */
  callbackURL?: string;
  /** If this is false, the session will not be remembered. Default is `true`. */
  rememberMe?: boolean;
};

export type SignUpWithEmailAndPassword200User = {
  /** The unique identifier of the user */
  id: string;
  /** The email address of the user */
  email: string;
  /** The name of the user */
  name: string;
  /**
   * The profile image URL of the user
   * @nullable
   */
  image?: string | null;
  /** Whether the email has been verified */
  emailVerified: boolean;
  /** When the user was created */
  createdAt: string;
  /** When the user was last updated */
  updatedAt: string;
};

export type SignUpWithEmailAndPassword200 = {
  /**
   * Authentication token for the session
   * @nullable
   */
  token?: string | null;
  user: SignUpWithEmailAndPassword200User;
};

export type SignUpWithEmailAndPassword400 = {
  message: string;
};

export type SignUpWithEmailAndPassword401 = {
  message: string;
};

export type SignUpWithEmailAndPassword403 = {
  message?: string;
};

export type SignUpWithEmailAndPassword404 = {
  message?: string;
};

export type SignUpWithEmailAndPassword422 = {
  message?: string;
};

export type SignUpWithEmailAndPassword429 = {
  message?: string;
};

export type SignUpWithEmailAndPassword500 = {
  message?: string;
};

export type SignInEmailBody = {
  /** Email of the user */
  email: string;
  /** Password of the user */
  password: string;
  /**
   * Callback URL to use as a redirect for email verification
   * @nullable
   */
  callbackURL?: string | null;
  /** @nullable */
  rememberMe?: string | null;
};

/**
 * Session response when idToken is provided
 */
export type SignInEmail200 = {
  redirect: boolean;
  /** Session token */
  token: string;
  /** @nullable */
  url?: string | null;
  user: User;
};

export type SignInEmail400 = {
  message: string;
};

export type SignInEmail401 = {
  message: string;
};

export type SignInEmail403 = {
  message?: string;
};

export type SignInEmail404 = {
  message?: string;
};

export type SignInEmail429 = {
  message?: string;
};

export type SignInEmail500 = {
  message?: string;
};

export type ResetPasswordBody = {
  /** The new password to set */
  newPassword: string;
  /**
   * The token to reset the password
   * @nullable
   */
  token?: string | null;
};

export type ResetPassword200 = {
  status?: boolean;
};

export type ResetPassword400 = {
  message: string;
};

export type ResetPassword401 = {
  message: string;
};

export type ResetPassword403 = {
  message?: string;
};

export type ResetPassword404 = {
  message?: string;
};

export type ResetPassword429 = {
  message?: string;
};

export type ResetPassword500 = {
  message?: string;
};

export type GetApiAuthVerifyEmailParams = {
/**
 * The token to verify the email
 */
token: string;
/**
 * The URL to redirect to after email verification
 */
callbackURL?: string;
};

export type GetApiAuthVerifyEmail200 = {
  user: User;
  /** Indicates if the email was verified successfully */
  status: boolean;
};

export type GetApiAuthVerifyEmail400 = {
  message: string;
};

export type GetApiAuthVerifyEmail401 = {
  message: string;
};

export type GetApiAuthVerifyEmail403 = {
  message?: string;
};

export type GetApiAuthVerifyEmail404 = {
  message?: string;
};

export type GetApiAuthVerifyEmail429 = {
  message?: string;
};

export type GetApiAuthVerifyEmail500 = {
  message?: string;
};

export type SendVerificationEmailBody = {
  /** The email to send the verification email to */
  email: string;
  /**
   * The URL to use for email verification callback
   * @nullable
   */
  callbackURL?: string | null;
};

export type SendVerificationEmail200 = {
  /** Indicates if the email was sent successfully */
  status?: boolean;
};

export type SendVerificationEmail400 = {
  /** Error message */
  message?: string;
};

export type SendVerificationEmail401 = {
  message: string;
};

export type SendVerificationEmail403 = {
  message?: string;
};

export type SendVerificationEmail404 = {
  message?: string;
};

export type SendVerificationEmail429 = {
  message?: string;
};

export type SendVerificationEmail500 = {
  message?: string;
};

export type ChangeEmailBody = {
  /** The new email address to set must be a valid email address */
  newEmail: string;
  /**
   * The URL to redirect to after email verification
   * @nullable
   */
  callbackURL?: string | null;
};

/**
 * Status message of the email change process
 * @nullable
 */
export type ChangeEmail200Message = typeof ChangeEmail200Message[keyof typeof ChangeEmail200Message] | null;


export const ChangeEmail200Message = {
  Email_updated: 'Email updated',
  Verification_email_sent: 'Verification email sent',
} as const;

export type ChangeEmail200 = {
  user?: User;
  /** Indicates if the request was successful */
  status: boolean;
  /**
   * Status message of the email change process
   * @nullable
   */
  message?: ChangeEmail200Message;
};

export type ChangeEmail400 = {
  message: string;
};

export type ChangeEmail401 = {
  message: string;
};

export type ChangeEmail403 = {
  message?: string;
};

export type ChangeEmail404 = {
  message?: string;
};

export type ChangeEmail422 = {
  message?: string;
};

export type ChangeEmail429 = {
  message?: string;
};

export type ChangeEmail500 = {
  message?: string;
};

export type ChangePasswordBody = {
  /** The new password to set */
  newPassword: string;
  /** The current password is required */
  currentPassword: string;
  /**
   * Must be a boolean value
   * @nullable
   */
  revokeOtherSessions?: boolean | null;
};

export type ChangePassword200User = {
  /** The unique identifier of the user */
  id: string;
  /** The email address of the user */
  email: string;
  /** The name of the user */
  name: string;
  /**
   * The profile image URL of the user
   * @nullable
   */
  image?: string | null;
  /** Whether the email has been verified */
  emailVerified: boolean;
  /** When the user was created */
  createdAt: string;
  /** When the user was last updated */
  updatedAt: string;
};

export type ChangePassword200 = {
  /**
   * New session token if other sessions were revoked
   * @nullable
   */
  token?: string | null;
  user: ChangePassword200User;
};

export type ChangePassword400 = {
  message: string;
};

export type ChangePassword401 = {
  message: string;
};

export type ChangePassword403 = {
  message?: string;
};

export type ChangePassword404 = {
  message?: string;
};

export type ChangePassword429 = {
  message?: string;
};

export type ChangePassword500 = {
  message?: string;
};

export type UpdateUserBody = {
  /** The name of the user */
  name?: string;
  /**
   * The image of the user
   * @nullable
   */
  image?: string | null;
};

export type UpdateUser200 = {
  user?: User;
};

export type UpdateUser400 = {
  message: string;
};

export type UpdateUser401 = {
  message: string;
};

export type UpdateUser403 = {
  message?: string;
};

export type UpdateUser404 = {
  message?: string;
};

export type UpdateUser429 = {
  message?: string;
};

export type UpdateUser500 = {
  message?: string;
};

export type DeleteUserBody = {
  /** The callback URL to redirect to after the user is deleted */
  callbackURL?: string;
  /** The user's password. Required if session is not fresh */
  password?: string;
  /** The deletion verification token */
  token?: string;
};

/**
 * Status message of the deletion process
 */
export type DeleteUser200Message = typeof DeleteUser200Message[keyof typeof DeleteUser200Message];


export const DeleteUser200Message = {
  User_deleted: 'User deleted',
  Verification_email_sent: 'Verification email sent',
} as const;

export type DeleteUser200 = {
  /** Indicates if the operation was successful */
  success: boolean;
  /** Status message of the deletion process */
  message: DeleteUser200Message;
};

export type DeleteUser400 = {
  message: string;
};

export type DeleteUser401 = {
  message: string;
};

export type DeleteUser403 = {
  message?: string;
};

export type DeleteUser404 = {
  message?: string;
};

export type DeleteUser429 = {
  message?: string;
};

export type DeleteUser500 = {
  message?: string;
};

export type RequestPasswordResetBody = {
  /** The email address of the user to send a password reset email to */
  email: string;
  /**
   * The URL to redirect the user to reset their password. If the token isn't valid or expired, it'll be redirected with a query parameter `?error=INVALID_TOKEN`. If the token is valid, it'll be redirected with a query parameter `?token=VALID_TOKEN
   * @nullable
   */
  redirectTo?: string | null;
};

export type RequestPasswordReset200 = {
  status?: boolean;
  message?: string;
};

export type RequestPasswordReset400 = {
  message: string;
};

export type RequestPasswordReset401 = {
  message: string;
};

export type RequestPasswordReset403 = {
  message?: string;
};

export type RequestPasswordReset404 = {
  message?: string;
};

export type RequestPasswordReset429 = {
  message?: string;
};

export type RequestPasswordReset500 = {
  message?: string;
};

export type ResetPasswordCallbackParams = {
/**
 * The URL to redirect the user to reset their password
 */
callbackURL: string;
};

export type ResetPasswordCallback200 = {
  token?: string;
};

export type ResetPasswordCallback400 = {
  message: string;
};

export type ResetPasswordCallback401 = {
  message: string;
};

export type ResetPasswordCallback403 = {
  message?: string;
};

export type ResetPasswordCallback404 = {
  message?: string;
};

export type ResetPasswordCallback429 = {
  message?: string;
};

export type ResetPasswordCallback500 = {
  message?: string;
};

export type PostApiAuthRevokeSessionBody = {
  /** The token to revoke */
  token: string;
};

export type PostApiAuthRevokeSession200 = {
  /** Indicates if the session was revoked successfully */
  status: boolean;
};

export type PostApiAuthRevokeSession400 = {
  message: string;
};

export type PostApiAuthRevokeSession401 = {
  message: string;
};

export type PostApiAuthRevokeSession403 = {
  message?: string;
};

export type PostApiAuthRevokeSession404 = {
  message?: string;
};

export type PostApiAuthRevokeSession429 = {
  message?: string;
};

export type PostApiAuthRevokeSession500 = {
  message?: string;
};

export type PostApiAuthRevokeSessionsBody = { [key: string]: unknown };

export type PostApiAuthRevokeSessions200 = {
  /** Indicates if all sessions were revoked successfully */
  status: boolean;
};

export type PostApiAuthRevokeSessions400 = {
  message: string;
};

export type PostApiAuthRevokeSessions401 = {
  message: string;
};

export type PostApiAuthRevokeSessions403 = {
  message?: string;
};

export type PostApiAuthRevokeSessions404 = {
  message?: string;
};

export type PostApiAuthRevokeSessions429 = {
  message?: string;
};

export type PostApiAuthRevokeSessions500 = {
  message?: string;
};

export type PostApiAuthRevokeOtherSessionsBody = { [key: string]: unknown };

export type PostApiAuthRevokeOtherSessions200 = {
  /** Indicates if all other sessions were revoked successfully */
  status: boolean;
};

export type PostApiAuthRevokeOtherSessions400 = {
  message: string;
};

export type PostApiAuthRevokeOtherSessions401 = {
  message: string;
};

export type PostApiAuthRevokeOtherSessions403 = {
  message?: string;
};

export type PostApiAuthRevokeOtherSessions404 = {
  message?: string;
};

export type PostApiAuthRevokeOtherSessions429 = {
  message?: string;
};

export type PostApiAuthRevokeOtherSessions500 = {
  message?: string;
};

/**
 * @nullable
 */
export type LinkSocialAccountBodyIdToken = {
  token: string;
  /** @nullable */
  nonce?: string | null;
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  /** @nullable */
  scopes?: unknown[] | null;
} | null;

export type LinkSocialAccountBody = {
  /**
   * The URL to redirect to after the user has signed in
   * @nullable
   */
  callbackURL?: string | null;
  provider: string;
  /** @nullable */
  idToken?: LinkSocialAccountBodyIdToken;
  /** @nullable */
  requestSignUp?: boolean | null;
  /**
   * Additional scopes to request from the provider
   * @nullable
   */
  scopes?: unknown[] | null;
  /**
   * The URL to redirect to if there is an error during the link process
   * @nullable
   */
  errorCallbackURL?: string | null;
  /**
   * Disable automatic redirection to the provider. Useful for handling the redirection yourself
   * @nullable
   */
  disableRedirect?: boolean | null;
  /** @nullable */
  additionalData?: string | null;
};

export type LinkSocialAccount200 = {
  /** The authorization URL to redirect the user to */
  url?: string;
  /** Indicates if the user should be redirected to the authorization URL */
  redirect: boolean;
  status?: boolean;
};

export type LinkSocialAccount400 = {
  message: string;
};

export type LinkSocialAccount401 = {
  message: string;
};

export type LinkSocialAccount403 = {
  message?: string;
};

export type LinkSocialAccount404 = {
  message?: string;
};

export type LinkSocialAccount429 = {
  message?: string;
};

export type LinkSocialAccount500 = {
  message?: string;
};

export type ListUserAccounts200Item = {
  id: string;
  providerId: string;
  createdAt: string;
  updatedAt: string;
  accountId: string;
  userId: string;
  scopes: string[];
};

export type ListUserAccounts400 = {
  message: string;
};

export type ListUserAccounts401 = {
  message: string;
};

export type ListUserAccounts403 = {
  message?: string;
};

export type ListUserAccounts404 = {
  message?: string;
};

export type ListUserAccounts429 = {
  message?: string;
};

export type ListUserAccounts500 = {
  message?: string;
};

export type GetApiAuthDeleteUserCallbackParams = {
/**
 * The token to verify the deletion request
 */
token?: string;
/**
 * The URL to redirect to after deletion
 * @nullable
 */
callbackURL?: string | null;
};

/**
 * Confirmation message
 */
export type GetApiAuthDeleteUserCallback200Message = typeof GetApiAuthDeleteUserCallback200Message[keyof typeof GetApiAuthDeleteUserCallback200Message];


export const GetApiAuthDeleteUserCallback200Message = {
  User_deleted: 'User deleted',
} as const;

export type GetApiAuthDeleteUserCallback200 = {
  /** Indicates if the deletion was successful */
  success: boolean;
  /** Confirmation message */
  message: GetApiAuthDeleteUserCallback200Message;
};

export type GetApiAuthDeleteUserCallback400 = {
  message: string;
};

export type GetApiAuthDeleteUserCallback401 = {
  message: string;
};

export type GetApiAuthDeleteUserCallback403 = {
  message?: string;
};

export type GetApiAuthDeleteUserCallback404 = {
  message?: string;
};

export type GetApiAuthDeleteUserCallback429 = {
  message?: string;
};

export type GetApiAuthDeleteUserCallback500 = {
  message?: string;
};

export type PostApiAuthUnlinkAccountBody = {
  providerId: string;
  /** @nullable */
  accountId?: string | null;
};

export type PostApiAuthUnlinkAccount200 = {
  status?: boolean;
};

export type PostApiAuthUnlinkAccount400 = {
  message: string;
};

export type PostApiAuthUnlinkAccount401 = {
  message: string;
};

export type PostApiAuthUnlinkAccount403 = {
  message?: string;
};

export type PostApiAuthUnlinkAccount404 = {
  message?: string;
};

export type PostApiAuthUnlinkAccount429 = {
  message?: string;
};

export type PostApiAuthUnlinkAccount500 = {
  message?: string;
};

export type PostApiAuthRefreshTokenBody = {
  /** The provider ID for the OAuth provider */
  providerId: string;
  /**
   * The account ID associated with the refresh token
   * @nullable
   */
  accountId?: string | null;
  /**
   * The user ID associated with the account
   * @nullable
   */
  userId?: string | null;
};

export type PostApiAuthRefreshToken200 = {
  tokenType?: string;
  idToken?: string;
  accessToken?: string;
  refreshToken?: string;
  accessTokenExpiresAt?: string;
  refreshTokenExpiresAt?: string;
};

export type PostApiAuthRefreshToken401 = {
  message: string;
};

export type PostApiAuthRefreshToken403 = {
  message?: string;
};

export type PostApiAuthRefreshToken404 = {
  message?: string;
};

export type PostApiAuthRefreshToken429 = {
  message?: string;
};

export type PostApiAuthRefreshToken500 = {
  message?: string;
};

export type PostApiAuthGetAccessTokenBody = {
  /** The provider ID for the OAuth provider */
  providerId: string;
  /**
   * The account ID associated with the refresh token
   * @nullable
   */
  accountId?: string | null;
  /**
   * The user ID associated with the account
   * @nullable
   */
  userId?: string | null;
};

export type PostApiAuthGetAccessToken200 = {
  tokenType?: string;
  idToken?: string;
  accessToken?: string;
  refreshToken?: string;
  accessTokenExpiresAt?: string;
  refreshTokenExpiresAt?: string;
};

export type PostApiAuthGetAccessToken401 = {
  message: string;
};

export type PostApiAuthGetAccessToken403 = {
  message?: string;
};

export type PostApiAuthGetAccessToken404 = {
  message?: string;
};

export type PostApiAuthGetAccessToken429 = {
  message?: string;
};

export type PostApiAuthGetAccessToken500 = {
  message?: string;
};

export type GetApiAuthAccountInfo200User = {
  id: string;
  name?: string;
  email?: string;
  image?: string;
  emailVerified: boolean;
};

export type GetApiAuthAccountInfo200Data = { [key: string]: unknown };

export type GetApiAuthAccountInfo200 = {
  user: GetApiAuthAccountInfo200User;
  data: GetApiAuthAccountInfo200Data;
};

export type GetApiAuthAccountInfo400 = {
  message: string;
};

export type GetApiAuthAccountInfo401 = {
  message: string;
};

export type GetApiAuthAccountInfo403 = {
  message?: string;
};

export type GetApiAuthAccountInfo404 = {
  message?: string;
};

export type GetApiAuthAccountInfo429 = {
  message?: string;
};

export type GetApiAuthAccountInfo500 = {
  message?: string;
};

export type GetApiAuthOk200 = {
  /** Indicates if the API is working */
  ok: boolean;
};

export type GetApiAuthOk400 = {
  message: string;
};

export type GetApiAuthOk401 = {
  message: string;
};

export type GetApiAuthOk403 = {
  message?: string;
};

export type GetApiAuthOk404 = {
  message?: string;
};

export type GetApiAuthOk429 = {
  message?: string;
};

export type GetApiAuthOk500 = {
  message?: string;
};

export type GetApiAuthError400 = {
  message: string;
};

export type GetApiAuthError401 = {
  message: string;
};

export type GetApiAuthError403 = {
  message?: string;
};

export type GetApiAuthError404 = {
  message?: string;
};

export type GetApiAuthError429 = {
  message?: string;
};

export type GetApiAuthError500 = {
  message?: string;
};

export type SetUserRoleBody = {
  /** The user id */
  userId: string;
  /** The role to set, this can be a string or an array of strings. Eg: `admin` or `[admin, user]` */
  role: string;
};

export type SetUserRole200 = {
  user?: User;
};

export type SetUserRole400 = {
  message: string;
};

export type SetUserRole401 = {
  message: string;
};

export type SetUserRole403 = {
  message?: string;
};

export type SetUserRole404 = {
  message?: string;
};

export type SetUserRole429 = {
  message?: string;
};

export type SetUserRole500 = {
  message?: string;
};

export type GetUserParams = {
/**
 * The id of the User
 */
id?: string;
};

export type GetUser200 = {
  user?: User;
};

export type GetUser400 = {
  message: string;
};

export type GetUser401 = {
  message: string;
};

export type GetUser403 = {
  message?: string;
};

export type GetUser404 = {
  message?: string;
};

export type GetUser429 = {
  message?: string;
};

export type GetUser500 = {
  message?: string;
};

export type CreateUserBody = {
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
  /** The name of the user */
  name: string;
  /** @nullable */
  role?: string | null;
  /** @nullable */
  data?: string | null;
};

export type CreateUser200 = {
  user?: User;
};

export type CreateUser400 = {
  message: string;
};

export type CreateUser401 = {
  message: string;
};

export type CreateUser403 = {
  message?: string;
};

export type CreateUser404 = {
  message?: string;
};

export type CreateUser429 = {
  message?: string;
};

export type CreateUser500 = {
  message?: string;
};

export type UpdateUserPostApiAuthAdminUpdateUserBody = {
  /** The user id */
  userId: string;
  /** The user data to update */
  data: string;
};

export type UpdateUserPostApiAuthAdminUpdateUser200 = {
  user?: User;
};

export type UpdateUserPostApiAuthAdminUpdateUser400 = {
  message: string;
};

export type UpdateUserPostApiAuthAdminUpdateUser401 = {
  message: string;
};

export type UpdateUserPostApiAuthAdminUpdateUser403 = {
  message?: string;
};

export type UpdateUserPostApiAuthAdminUpdateUser404 = {
  message?: string;
};

export type UpdateUserPostApiAuthAdminUpdateUser429 = {
  message?: string;
};

export type UpdateUserPostApiAuthAdminUpdateUser500 = {
  message?: string;
};

export type ListUsersParams = {
/**
 * @nullable
 */
searchValue?: string | null;
/**
 * The field to search in, defaults to email. Can be `email` or `name`. Eg: "name"
 * @nullable
 */
searchField?: string | null;
/**
 * The operator to use for the search. Can be `contains`, `starts_with` or `ends_with`. Eg: "contains"
 * @nullable
 */
searchOperator?: string | null;
/**
 * @nullable
 */
limit?: string | null;
/**
 * @nullable
 */
offset?: string | null;
/**
 * The field to sort by
 * @nullable
 */
sortBy?: string | null;
/**
 * The direction to sort by
 * @nullable
 */
sortDirection?: string | null;
/**
 * The field to filter by
 * @nullable
 */
filterField?: string | null;
/**
 * @nullable
 */
filterValue?: string | null;
/**
 * The operator to use for the filter
 * @nullable
 */
filterOperator?: string | null;
};

export type ListUsers200 = {
  users: User[];
  total: number;
  limit?: number;
  offset?: number;
};

export type ListUsers400 = {
  message: string;
};

export type ListUsers401 = {
  message: string;
};

export type ListUsers403 = {
  message?: string;
};

export type ListUsers404 = {
  message?: string;
};

export type ListUsers429 = {
  message?: string;
};

export type ListUsers500 = {
  message?: string;
};

export type ListUserSessionsPostApiAuthAdminListUserSessionsBody = {
  /** The user id */
  userId: string;
};

export type ListUserSessionsPostApiAuthAdminListUserSessions200 = {
  sessions?: Session[];
};

export type ListUserSessionsPostApiAuthAdminListUserSessions400 = {
  message: string;
};

export type ListUserSessionsPostApiAuthAdminListUserSessions401 = {
  message: string;
};

export type ListUserSessionsPostApiAuthAdminListUserSessions403 = {
  message?: string;
};

export type ListUserSessionsPostApiAuthAdminListUserSessions404 = {
  message?: string;
};

export type ListUserSessionsPostApiAuthAdminListUserSessions429 = {
  message?: string;
};

export type ListUserSessionsPostApiAuthAdminListUserSessions500 = {
  message?: string;
};

export type UnbanUserBody = {
  /** The user id */
  userId: string;
};

export type UnbanUser200 = {
  user?: User;
};

export type UnbanUser400 = {
  message: string;
};

export type UnbanUser401 = {
  message: string;
};

export type UnbanUser403 = {
  message?: string;
};

export type UnbanUser404 = {
  message?: string;
};

export type UnbanUser429 = {
  message?: string;
};

export type UnbanUser500 = {
  message?: string;
};

export type BanUserBody = {
  /** The user id */
  userId: string;
  /**
   * The reason for the ban
   * @nullable
   */
  banReason?: string | null;
  /**
   * The number of seconds until the ban expires
   * @nullable
   */
  banExpiresIn?: number | null;
};

export type BanUser200 = {
  user?: User;
};

export type BanUser400 = {
  message: string;
};

export type BanUser401 = {
  message: string;
};

export type BanUser403 = {
  message?: string;
};

export type BanUser404 = {
  message?: string;
};

export type BanUser429 = {
  message?: string;
};

export type BanUser500 = {
  message?: string;
};

export type ImpersonateUserBody = {
  /** The user id */
  userId: string;
};

export type ImpersonateUser200 = {
  session?: Session;
  user?: User;
};

export type ImpersonateUser400 = {
  message: string;
};

export type ImpersonateUser401 = {
  message: string;
};

export type ImpersonateUser403 = {
  message?: string;
};

export type ImpersonateUser404 = {
  message?: string;
};

export type ImpersonateUser429 = {
  message?: string;
};

export type ImpersonateUser500 = {
  message?: string;
};

export type PostApiAuthAdminStopImpersonating400 = {
  message: string;
};

export type PostApiAuthAdminStopImpersonating401 = {
  message: string;
};

export type PostApiAuthAdminStopImpersonating403 = {
  message?: string;
};

export type PostApiAuthAdminStopImpersonating404 = {
  message?: string;
};

export type PostApiAuthAdminStopImpersonating429 = {
  message?: string;
};

export type PostApiAuthAdminStopImpersonating500 = {
  message?: string;
};

export type RevokeUserSessionBody = {
  /** The session token */
  sessionToken: string;
};

export type RevokeUserSession200 = {
  success?: boolean;
};

export type RevokeUserSession400 = {
  message: string;
};

export type RevokeUserSession401 = {
  message: string;
};

export type RevokeUserSession403 = {
  message?: string;
};

export type RevokeUserSession404 = {
  message?: string;
};

export type RevokeUserSession429 = {
  message?: string;
};

export type RevokeUserSession500 = {
  message?: string;
};

export type RevokeUserSessionsBody = {
  /** The user id */
  userId: string;
};

export type RevokeUserSessions200 = {
  success?: boolean;
};

export type RevokeUserSessions400 = {
  message: string;
};

export type RevokeUserSessions401 = {
  message: string;
};

export type RevokeUserSessions403 = {
  message?: string;
};

export type RevokeUserSessions404 = {
  message?: string;
};

export type RevokeUserSessions429 = {
  message?: string;
};

export type RevokeUserSessions500 = {
  message?: string;
};

export type RemoveUserBody = {
  /** The user id */
  userId: string;
};

export type RemoveUser200 = {
  success?: boolean;
};

export type RemoveUser400 = {
  message: string;
};

export type RemoveUser401 = {
  message: string;
};

export type RemoveUser403 = {
  message?: string;
};

export type RemoveUser404 = {
  message?: string;
};

export type RemoveUser429 = {
  message?: string;
};

export type RemoveUser500 = {
  message?: string;
};

export type SetUserPasswordBody = {
  /** The new password */
  newPassword: string;
  /** The user id */
  userId: string;
};

export type SetUserPassword200 = {
  status?: boolean;
};

export type SetUserPassword400 = {
  message: string;
};

export type SetUserPassword401 = {
  message: string;
};

export type SetUserPassword403 = {
  message?: string;
};

export type SetUserPassword404 = {
  message?: string;
};

export type SetUserPassword429 = {
  message?: string;
};

export type SetUserPassword500 = {
  message?: string;
};

/**
 * The permission to check
 * @deprecated
 */
export type PostApiAuthAdminHasPermissionBodyPermission = { [key: string]: unknown };

/**
 * The permission to check
 */
export type PostApiAuthAdminHasPermissionBodyPermissions = { [key: string]: unknown };

export type PostApiAuthAdminHasPermissionBody = {
  /**
   * The permission to check
   * @deprecated
   */
  permission?: PostApiAuthAdminHasPermissionBodyPermission;
  /** The permission to check */
  permissions: PostApiAuthAdminHasPermissionBodyPermissions;
};

export type PostApiAuthAdminHasPermission200 = {
  error?: string;
  success: boolean;
};

export type PostApiAuthAdminHasPermission400 = {
  message: string;
};

export type PostApiAuthAdminHasPermission401 = {
  message: string;
};

export type PostApiAuthAdminHasPermission403 = {
  message?: string;
};

export type PostApiAuthAdminHasPermission404 = {
  message?: string;
};

export type PostApiAuthAdminHasPermission429 = {
  message?: string;
};

export type PostApiAuthAdminHasPermission500 = {
  message?: string;
};

export type PostApiAuthTwoFactorGetTotpUriBody = {
  /** User password */
  password: string;
};

export type PostApiAuthTwoFactorGetTotpUri200 = {
  totpURI?: string;
};

export type PostApiAuthTwoFactorGetTotpUri400 = {
  message: string;
};

export type PostApiAuthTwoFactorGetTotpUri401 = {
  message: string;
};

export type PostApiAuthTwoFactorGetTotpUri403 = {
  message?: string;
};

export type PostApiAuthTwoFactorGetTotpUri404 = {
  message?: string;
};

export type PostApiAuthTwoFactorGetTotpUri429 = {
  message?: string;
};

export type PostApiAuthTwoFactorGetTotpUri500 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyTotpBody = {
  /** The otp code to verify. Eg: "012345" */
  code: string;
  /**
   * If true, the device will be trusted for 30 days. It'll be refreshed on every sign in request within this time. Eg: true
   * @nullable
   */
  trustDevice?: boolean | null;
};

export type PostApiAuthTwoFactorVerifyTotp200 = {
  status?: boolean;
};

export type PostApiAuthTwoFactorVerifyTotp400 = {
  message: string;
};

export type PostApiAuthTwoFactorVerifyTotp401 = {
  message: string;
};

export type PostApiAuthTwoFactorVerifyTotp403 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyTotp404 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyTotp429 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyTotp500 = {
  message?: string;
};

export type PostApiAuthTwoFactorSendOtp200 = {
  status?: boolean;
};

export type PostApiAuthTwoFactorSendOtp400 = {
  message: string;
};

export type PostApiAuthTwoFactorSendOtp401 = {
  message: string;
};

export type PostApiAuthTwoFactorSendOtp403 = {
  message?: string;
};

export type PostApiAuthTwoFactorSendOtp404 = {
  message?: string;
};

export type PostApiAuthTwoFactorSendOtp429 = {
  message?: string;
};

export type PostApiAuthTwoFactorSendOtp500 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyOtpBody = {
  /** The otp code to verify. Eg: "012345" */
  code: string;
  /** @nullable */
  trustDevice?: boolean | null;
};

/**
 * The authenticated user object
 */
export type PostApiAuthTwoFactorVerifyOtp200User = {
  /** Unique identifier of the user */
  id: string;
  /**
   * User's email address
   * @nullable
   */
  email?: string | null;
  /**
   * Whether the email is verified
   * @nullable
   */
  emailVerified?: boolean | null;
  /**
   * User's name
   * @nullable
   */
  name?: string | null;
  /**
   * User's profile image URL
   * @nullable
   */
  image?: string | null;
  /** Timestamp when the user was created */
  createdAt: string;
  /** Timestamp when the user was last updated */
  updatedAt: string;
};

export type PostApiAuthTwoFactorVerifyOtp200 = {
  /** Session token for the authenticated session */
  token: string;
  /** The authenticated user object */
  user: PostApiAuthTwoFactorVerifyOtp200User;
};

export type PostApiAuthTwoFactorVerifyOtp400 = {
  message: string;
};

export type PostApiAuthTwoFactorVerifyOtp401 = {
  message: string;
};

export type PostApiAuthTwoFactorVerifyOtp403 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyOtp404 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyOtp429 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyOtp500 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyBackupCodeBody = {
  /** A backup code to verify. Eg: "123456" */
  code: string;
  /**
   * If true, the session cookie will not be set.
   * @nullable
   */
  disableSession?: boolean | null;
  /**
   * If true, the device will be trusted for 30 days. It'll be refreshed on every sign in request within this time. Eg: true
   * @nullable
   */
  trustDevice?: boolean | null;
};

/**
 * The authenticated user object with two-factor details
 */
export type PostApiAuthTwoFactorVerifyBackupCode200User = {
  /** Unique identifier of the user */
  id: string;
  /**
   * User's email address
   * @nullable
   */
  email?: string | null;
  /**
   * Whether the email is verified
   * @nullable
   */
  emailVerified?: boolean | null;
  /**
   * User's name
   * @nullable
   */
  name?: string | null;
  /**
   * User's profile image URL
   * @nullable
   */
  image?: string | null;
  /** Whether two-factor authentication is enabled for the user */
  twoFactorEnabled: boolean;
  /** Timestamp when the user was created */
  createdAt: string;
  /** Timestamp when the user was last updated */
  updatedAt: string;
};

/**
 * The current session object, included unless disableSession is true
 */
export type PostApiAuthTwoFactorVerifyBackupCode200Session = {
  /** Session token */
  token: string;
  /** ID of the user associated with the session */
  userId: string;
  /** Timestamp when the session was created */
  createdAt: string;
  /** Timestamp when the session expires */
  expiresAt: string;
};

export type PostApiAuthTwoFactorVerifyBackupCode200 = {
  /** The authenticated user object with two-factor details */
  user: PostApiAuthTwoFactorVerifyBackupCode200User;
  /** The current session object, included unless disableSession is true */
  session: PostApiAuthTwoFactorVerifyBackupCode200Session;
};

export type PostApiAuthTwoFactorVerifyBackupCode400 = {
  message: string;
};

export type PostApiAuthTwoFactorVerifyBackupCode401 = {
  message: string;
};

export type PostApiAuthTwoFactorVerifyBackupCode403 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyBackupCode404 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyBackupCode429 = {
  message?: string;
};

export type PostApiAuthTwoFactorVerifyBackupCode500 = {
  message?: string;
};

export type PostApiAuthTwoFactorGenerateBackupCodesBody = {
  /** The users password. */
  password: string;
};

export type PostApiAuthTwoFactorGenerateBackupCodes200 = {
  /** Indicates if the backup codes were generated successfully */
  status: boolean;
  /** Array of generated backup codes in plain text */
  backupCodes: string[];
};

export type PostApiAuthTwoFactorGenerateBackupCodes400 = {
  message: string;
};

export type PostApiAuthTwoFactorGenerateBackupCodes401 = {
  message: string;
};

export type PostApiAuthTwoFactorGenerateBackupCodes403 = {
  message?: string;
};

export type PostApiAuthTwoFactorGenerateBackupCodes404 = {
  message?: string;
};

export type PostApiAuthTwoFactorGenerateBackupCodes429 = {
  message?: string;
};

export type PostApiAuthTwoFactorGenerateBackupCodes500 = {
  message?: string;
};

export type PostApiAuthTwoFactorEnableBody = {
  /** User password */
  password: string;
  /**
   * Custom issuer for the TOTP URI
   * @nullable
   */
  issuer?: string | null;
};

export type PostApiAuthTwoFactorEnable200 = {
  /** TOTP URI */
  totpURI?: string;
  /** Backup codes */
  backupCodes?: string[];
};

export type PostApiAuthTwoFactorEnable400 = {
  message: string;
};

export type PostApiAuthTwoFactorEnable401 = {
  message: string;
};

export type PostApiAuthTwoFactorEnable403 = {
  message?: string;
};

export type PostApiAuthTwoFactorEnable404 = {
  message?: string;
};

export type PostApiAuthTwoFactorEnable429 = {
  message?: string;
};

export type PostApiAuthTwoFactorEnable500 = {
  message?: string;
};
