import { env } from "../../config/env";

export const WITHDRAWAL_MIN_USD_CENTS = env.WITHDRAWAL_MIN_USD_CENTS;
export const WITHDRAWAL_MAX_USD_CENTS = env.WITHDRAWAL_MAX_USD_CENTS;
export const WITHDRAWAL_DAILY_LIMIT_USD_CENTS = env.WITHDRAWAL_DAILY_LIMIT_USD_CENTS;
export const WITHDRAWAL_REQUIRES_2FA = env.WITHDRAWAL_REQUIRES_2FA;
export const WITHDRAWAL_CURRENCY = "USD" as const;
