/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NexxaTrade API
 * API documentation for NexxaTrade
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiReferralsStats200,
  GetApiReferralsTeam200,
  GetApiReferralsTeamParams
} from '../generated.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get referral stats for the current user
 */
export const getApiReferralsStats = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiReferralsStats200>(
      {url: `/api/referrals/stats`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiReferralsStatsQueryKey = () => {
    return [
    `/api/referrals/stats`
    ] as const;
    }

    
export const getGetApiReferralsStatsQueryOptions = <TData = Awaited<ReturnType<typeof getApiReferralsStats>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiReferralsStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiReferralsStats>>> = ({ signal }) => getApiReferralsStats(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiReferralsStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiReferralsStats>>>
export type GetApiReferralsStatsQueryError = unknown


export function useGetApiReferralsStats<TData = Awaited<ReturnType<typeof getApiReferralsStats>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReferralsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiReferralsStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReferralsStats<TData = Awaited<ReturnType<typeof getApiReferralsStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReferralsStats>>,
          TError,
          Awaited<ReturnType<typeof getApiReferralsStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReferralsStats<TData = Awaited<ReturnType<typeof getApiReferralsStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get referral stats for the current user
 */

export function useGetApiReferralsStats<TData = Awaited<ReturnType<typeof getApiReferralsStats>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiReferralsStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List referral team members with pagination
 */
export const getApiReferralsTeam = (
    params?: GetApiReferralsTeamParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiReferralsTeam200>(
      {url: `/api/referrals/team`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiReferralsTeamQueryKey = (params?: GetApiReferralsTeamParams,) => {
    return [
    `/api/referrals/team`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiReferralsTeamQueryOptions = <TData = Awaited<ReturnType<typeof getApiReferralsTeam>>, TError = unknown>(params?: GetApiReferralsTeamParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiReferralsTeamQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiReferralsTeam>>> = ({ signal }) => getApiReferralsTeam(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsTeam>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiReferralsTeamQueryResult = NonNullable<Awaited<ReturnType<typeof getApiReferralsTeam>>>
export type GetApiReferralsTeamQueryError = unknown


export function useGetApiReferralsTeam<TData = Awaited<ReturnType<typeof getApiReferralsTeam>>, TError = unknown>(
 params: undefined |  GetApiReferralsTeamParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsTeam>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReferralsTeam>>,
          TError,
          Awaited<ReturnType<typeof getApiReferralsTeam>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReferralsTeam<TData = Awaited<ReturnType<typeof getApiReferralsTeam>>, TError = unknown>(
 params?: GetApiReferralsTeamParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsTeam>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReferralsTeam>>,
          TError,
          Awaited<ReturnType<typeof getApiReferralsTeam>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReferralsTeam<TData = Awaited<ReturnType<typeof getApiReferralsTeam>>, TError = unknown>(
 params?: GetApiReferralsTeamParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List referral team members with pagination
 */

export function useGetApiReferralsTeam<TData = Awaited<ReturnType<typeof getApiReferralsTeam>>, TError = unknown>(
 params?: GetApiReferralsTeamParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReferralsTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiReferralsTeamQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




