/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NexxaTrade API
 * API documentation for NexxaTrade
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Def28,
  Def29,
  Def34,
  Def35,
  Def36,
  Def37,
  Def38,
  Def39,
  GetApiSignalsChannelsChannelIdMessagesParams
} from '../generated.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List signal channels
 */
export const getApiSignalsChannels = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def28>(
      {url: `/api/signals/channels`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiSignalsChannelsQueryKey = () => {
    return [
    `/api/signals/channels`
    ] as const;
    }

    
export const getGetApiSignalsChannelsQueryOptions = <TData = Awaited<ReturnType<typeof getApiSignalsChannels>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSignalsChannelsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSignalsChannels>>> = ({ signal }) => getApiSignalsChannels(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSignalsChannelsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSignalsChannels>>>
export type GetApiSignalsChannelsQueryError = unknown


export function useGetApiSignalsChannels<TData = Awaited<ReturnType<typeof getApiSignalsChannels>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSignalsChannels>>,
          TError,
          Awaited<ReturnType<typeof getApiSignalsChannels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSignalsChannels<TData = Awaited<ReturnType<typeof getApiSignalsChannels>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSignalsChannels>>,
          TError,
          Awaited<ReturnType<typeof getApiSignalsChannels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSignalsChannels<TData = Awaited<ReturnType<typeof getApiSignalsChannels>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List signal channels
 */

export function useGetApiSignalsChannels<TData = Awaited<ReturnType<typeof getApiSignalsChannels>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannels>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSignalsChannelsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List signal messages
 */
export const getApiSignalsChannelsChannelIdMessages = (
    channelId: string,
    params?: GetApiSignalsChannelsChannelIdMessagesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def29>(
      {url: `/api/signals/channels/${channelId}/messages`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiSignalsChannelsChannelIdMessagesQueryKey = (channelId?: string,
    params?: GetApiSignalsChannelsChannelIdMessagesParams,) => {
    return [
    `/api/signals/channels/${channelId}/messages`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiSignalsChannelsChannelIdMessagesQueryOptions = <TData = Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>, TError = unknown>(channelId: string,
    params?: GetApiSignalsChannelsChannelIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSignalsChannelsChannelIdMessagesQueryKey(channelId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>> = ({ signal }) => getApiSignalsChannelsChannelIdMessages(channelId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(channelId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSignalsChannelsChannelIdMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>>
export type GetApiSignalsChannelsChannelIdMessagesQueryError = unknown


export function useGetApiSignalsChannelsChannelIdMessages<TData = Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>, TError = unknown>(
 channelId: string,
    params: undefined |  GetApiSignalsChannelsChannelIdMessagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>,
          TError,
          Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSignalsChannelsChannelIdMessages<TData = Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>, TError = unknown>(
 channelId: string,
    params?: GetApiSignalsChannelsChannelIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>,
          TError,
          Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSignalsChannelsChannelIdMessages<TData = Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>, TError = unknown>(
 channelId: string,
    params?: GetApiSignalsChannelsChannelIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List signal messages
 */

export function useGetApiSignalsChannelsChannelIdMessages<TData = Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>, TError = unknown>(
 channelId: string,
    params?: GetApiSignalsChannelsChannelIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSignalsChannelsChannelIdMessages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSignalsChannelsChannelIdMessagesQueryOptions(channelId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Ingest signal message
 */
export const postApiSignalsIngest = (
    def34: Def34,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def35>(
      {url: `/api/signals/ingest`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: def34, signal
    },
      options);
    }
  


export const getPostApiSignalsIngestMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSignalsIngest>>, TError,{data: Def34}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSignalsIngest>>, TError,{data: Def34}, TContext> => {

const mutationKey = ['postApiSignalsIngest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSignalsIngest>>, {data: Def34}> = (props) => {
          const {data} = props ?? {};

          return  postApiSignalsIngest(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSignalsIngestMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSignalsIngest>>>
    export type PostApiSignalsIngestMutationBody = Def34
    export type PostApiSignalsIngestMutationError = unknown

    /**
 * @summary Ingest signal message
 */
export const usePostApiSignalsIngest = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSignalsIngest>>, TError,{data: Def34}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSignalsIngest>>,
        TError,
        {data: Def34},
        TContext
      > => {

      const mutationOptions = getPostApiSignalsIngestMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Edit signal message
 */
export const postApiSignalsEdit = (
    def36: Def36,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def37>(
      {url: `/api/signals/edit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: def36, signal
    },
      options);
    }
  


export const getPostApiSignalsEditMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSignalsEdit>>, TError,{data: Def36}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSignalsEdit>>, TError,{data: Def36}, TContext> => {

const mutationKey = ['postApiSignalsEdit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSignalsEdit>>, {data: Def36}> = (props) => {
          const {data} = props ?? {};

          return  postApiSignalsEdit(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSignalsEditMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSignalsEdit>>>
    export type PostApiSignalsEditMutationBody = Def36
    export type PostApiSignalsEditMutationError = unknown

    /**
 * @summary Edit signal message
 */
export const usePostApiSignalsEdit = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSignalsEdit>>, TError,{data: Def36}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSignalsEdit>>,
        TError,
        {data: Def36},
        TContext
      > => {

      const mutationOptions = getPostApiSignalsEditMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete signal messages
 */
export const postApiSignalsDelete = (
    def38: Def38,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Def39>(
      {url: `/api/signals/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: def38, signal
    },
      options);
    }
  


export const getPostApiSignalsDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSignalsDelete>>, TError,{data: Def38}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSignalsDelete>>, TError,{data: Def38}, TContext> => {

const mutationKey = ['postApiSignalsDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSignalsDelete>>, {data: Def38}> = (props) => {
          const {data} = props ?? {};

          return  postApiSignalsDelete(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSignalsDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSignalsDelete>>>
    export type PostApiSignalsDeleteMutationBody = Def38
    export type PostApiSignalsDeleteMutationError = unknown

    /**
 * @summary Delete signal messages
 */
export const usePostApiSignalsDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSignalsDelete>>, TError,{data: Def38}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSignalsDelete>>,
        TError,
        {data: Def38},
        TContext
      > => {

      const mutationOptions = getPostApiSignalsDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    