import { env } from "../../config/env";

export const MEMBERSHIP_DELETION_DAYS = env.MEMBERSHIP_DELETION_DAYS;
export const MEMBERSHIP_EXPIRE_EVERY_MINUTES = env.MEMBERSHIP_EXPIRE_EVERY_MINUTES;
export const MEMBERSHIP_COMPRESS_EVERY_MINUTES = env.MEMBERSHIP_COMPRESS_EVERY_MINUTES;
