/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NexxaTrade API
 * API documentation for NexxaTrade
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiPaymentsInvoices200,
  GetApiPaymentsInvoicesParams,
  GetApiPaymentsPaymentId200,
  PostApiPaymentsAddress200,
  PostApiPaymentsAddressBody
} from '../generated.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List membership payment invoices for the current user
 */
export const getApiPaymentsInvoices = (
    params?: GetApiPaymentsInvoicesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiPaymentsInvoices200>(
      {url: `/api/payments/invoices`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiPaymentsInvoicesQueryKey = (params?: GetApiPaymentsInvoicesParams,) => {
    return [
    `/api/payments/invoices`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiPaymentsInvoicesQueryOptions = <TData = Awaited<ReturnType<typeof getApiPaymentsInvoices>>, TError = unknown>(params?: GetApiPaymentsInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsInvoices>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPaymentsInvoicesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPaymentsInvoices>>> = ({ signal }) => getApiPaymentsInvoices(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsInvoices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPaymentsInvoicesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPaymentsInvoices>>>
export type GetApiPaymentsInvoicesQueryError = unknown


export function useGetApiPaymentsInvoices<TData = Awaited<ReturnType<typeof getApiPaymentsInvoices>>, TError = unknown>(
 params: undefined |  GetApiPaymentsInvoicesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsInvoices>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPaymentsInvoices>>,
          TError,
          Awaited<ReturnType<typeof getApiPaymentsInvoices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPaymentsInvoices<TData = Awaited<ReturnType<typeof getApiPaymentsInvoices>>, TError = unknown>(
 params?: GetApiPaymentsInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsInvoices>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPaymentsInvoices>>,
          TError,
          Awaited<ReturnType<typeof getApiPaymentsInvoices>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPaymentsInvoices<TData = Awaited<ReturnType<typeof getApiPaymentsInvoices>>, TError = unknown>(
 params?: GetApiPaymentsInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsInvoices>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List membership payment invoices for the current user
 */

export function useGetApiPaymentsInvoices<TData = Awaited<ReturnType<typeof getApiPaymentsInvoices>>, TError = unknown>(
 params?: GetApiPaymentsInvoicesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsInvoices>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPaymentsInvoicesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a payment intent and reserve a deposit address
 */
export const postApiPaymentsAddress = (
    postApiPaymentsAddressBody: PostApiPaymentsAddressBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostApiPaymentsAddress200>(
      {url: `/api/payments/address`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiPaymentsAddressBody, signal
    },
      options);
    }
  


export const getPostApiPaymentsAddressMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPaymentsAddress>>, TError,{data: PostApiPaymentsAddressBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPaymentsAddress>>, TError,{data: PostApiPaymentsAddressBody}, TContext> => {

const mutationKey = ['postApiPaymentsAddress'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPaymentsAddress>>, {data: PostApiPaymentsAddressBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiPaymentsAddress(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiPaymentsAddressMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPaymentsAddress>>>
    export type PostApiPaymentsAddressMutationBody = PostApiPaymentsAddressBody
    export type PostApiPaymentsAddressMutationError = unknown

    /**
 * @summary Create a payment intent and reserve a deposit address
 */
export const usePostApiPaymentsAddress = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPaymentsAddress>>, TError,{data: PostApiPaymentsAddressBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPaymentsAddress>>,
        TError,
        {data: PostApiPaymentsAddressBody},
        TContext
      > => {

      const mutationOptions = getPostApiPaymentsAddressMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get payment status
 */
export const getApiPaymentsPaymentId = (
    paymentId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiPaymentsPaymentId200>(
      {url: `/api/payments/${paymentId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiPaymentsPaymentIdQueryKey = (paymentId?: string,) => {
    return [
    `/api/payments/${paymentId}`
    ] as const;
    }

    
export const getGetApiPaymentsPaymentIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiPaymentsPaymentId>>, TError = unknown>(paymentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsPaymentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPaymentsPaymentIdQueryKey(paymentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPaymentsPaymentId>>> = ({ signal }) => getApiPaymentsPaymentId(paymentId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(paymentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsPaymentId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPaymentsPaymentIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPaymentsPaymentId>>>
export type GetApiPaymentsPaymentIdQueryError = unknown


export function useGetApiPaymentsPaymentId<TData = Awaited<ReturnType<typeof getApiPaymentsPaymentId>>, TError = unknown>(
 paymentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsPaymentId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPaymentsPaymentId>>,
          TError,
          Awaited<ReturnType<typeof getApiPaymentsPaymentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPaymentsPaymentId<TData = Awaited<ReturnType<typeof getApiPaymentsPaymentId>>, TError = unknown>(
 paymentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsPaymentId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPaymentsPaymentId>>,
          TError,
          Awaited<ReturnType<typeof getApiPaymentsPaymentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPaymentsPaymentId<TData = Awaited<ReturnType<typeof getApiPaymentsPaymentId>>, TError = unknown>(
 paymentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsPaymentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get payment status
 */

export function useGetApiPaymentsPaymentId<TData = Awaited<ReturnType<typeof getApiPaymentsPaymentId>>, TError = unknown>(
 paymentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPaymentsPaymentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPaymentsPaymentIdQueryOptions(paymentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




