/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NexxaTrade API
 * API documentation for NexxaTrade
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BanUser200,
  BanUser400,
  BanUser401,
  BanUser403,
  BanUser404,
  BanUser429,
  BanUser500,
  BanUserBody,
  CreateUser200,
  CreateUser400,
  CreateUser401,
  CreateUser403,
  CreateUser404,
  CreateUser429,
  CreateUser500,
  CreateUserBody,
  GetUser200,
  GetUser400,
  GetUser401,
  GetUser403,
  GetUser404,
  GetUser429,
  GetUser500,
  GetUserParams,
  ImpersonateUser200,
  ImpersonateUser400,
  ImpersonateUser401,
  ImpersonateUser403,
  ImpersonateUser404,
  ImpersonateUser429,
  ImpersonateUser500,
  ImpersonateUserBody,
  ListUserSessionsPostApiAuthAdminListUserSessions200,
  ListUserSessionsPostApiAuthAdminListUserSessions400,
  ListUserSessionsPostApiAuthAdminListUserSessions401,
  ListUserSessionsPostApiAuthAdminListUserSessions403,
  ListUserSessionsPostApiAuthAdminListUserSessions404,
  ListUserSessionsPostApiAuthAdminListUserSessions429,
  ListUserSessionsPostApiAuthAdminListUserSessions500,
  ListUserSessionsPostApiAuthAdminListUserSessionsBody,
  ListUsers200,
  ListUsers400,
  ListUsers401,
  ListUsers403,
  ListUsers404,
  ListUsers429,
  ListUsers500,
  ListUsersParams,
  PostApiAuthAdminHasPermission200,
  PostApiAuthAdminHasPermission400,
  PostApiAuthAdminHasPermission401,
  PostApiAuthAdminHasPermission403,
  PostApiAuthAdminHasPermission404,
  PostApiAuthAdminHasPermission429,
  PostApiAuthAdminHasPermission500,
  PostApiAuthAdminHasPermissionBody,
  PostApiAuthAdminStopImpersonating400,
  PostApiAuthAdminStopImpersonating401,
  PostApiAuthAdminStopImpersonating403,
  PostApiAuthAdminStopImpersonating404,
  PostApiAuthAdminStopImpersonating429,
  PostApiAuthAdminStopImpersonating500,
  RemoveUser200,
  RemoveUser400,
  RemoveUser401,
  RemoveUser403,
  RemoveUser404,
  RemoveUser429,
  RemoveUser500,
  RemoveUserBody,
  RevokeUserSession200,
  RevokeUserSession400,
  RevokeUserSession401,
  RevokeUserSession403,
  RevokeUserSession404,
  RevokeUserSession429,
  RevokeUserSession500,
  RevokeUserSessionBody,
  RevokeUserSessions200,
  RevokeUserSessions400,
  RevokeUserSessions401,
  RevokeUserSessions403,
  RevokeUserSessions404,
  RevokeUserSessions429,
  RevokeUserSessions500,
  RevokeUserSessionsBody,
  SetUserPassword200,
  SetUserPassword400,
  SetUserPassword401,
  SetUserPassword403,
  SetUserPassword404,
  SetUserPassword429,
  SetUserPassword500,
  SetUserPasswordBody,
  SetUserRole200,
  SetUserRole400,
  SetUserRole401,
  SetUserRole403,
  SetUserRole404,
  SetUserRole429,
  SetUserRole500,
  SetUserRoleBody,
  UnbanUser200,
  UnbanUser400,
  UnbanUser401,
  UnbanUser403,
  UnbanUser404,
  UnbanUser429,
  UnbanUser500,
  UnbanUserBody,
  UpdateUserPostApiAuthAdminUpdateUser200,
  UpdateUserPostApiAuthAdminUpdateUser400,
  UpdateUserPostApiAuthAdminUpdateUser401,
  UpdateUserPostApiAuthAdminUpdateUser403,
  UpdateUserPostApiAuthAdminUpdateUser404,
  UpdateUserPostApiAuthAdminUpdateUser429,
  UpdateUserPostApiAuthAdminUpdateUser500,
  UpdateUserPostApiAuthAdminUpdateUserBody
} from '../generated.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Set the role of a user
 */
export const setUserRole = (
    setUserRoleBody: SetUserRoleBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SetUserRole200>(
      {url: `/api/auth/admin/set-role`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setUserRoleBody, signal
    },
      options);
    }
  


export const getSetUserRoleMutationOptions = <TError = SetUserRole400 | SetUserRole401 | SetUserRole403 | SetUserRole404 | SetUserRole429 | SetUserRole500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setUserRole>>, TError,{data: SetUserRoleBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof setUserRole>>, TError,{data: SetUserRoleBody}, TContext> => {

const mutationKey = ['setUserRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setUserRole>>, {data: SetUserRoleBody}> = (props) => {
          const {data} = props ?? {};

          return  setUserRole(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SetUserRoleMutationResult = NonNullable<Awaited<ReturnType<typeof setUserRole>>>
    export type SetUserRoleMutationBody = SetUserRoleBody
    export type SetUserRoleMutationError = SetUserRole400 | SetUserRole401 | SetUserRole403 | SetUserRole404 | SetUserRole429 | SetUserRole500

    export const useSetUserRole = <TError = SetUserRole400 | SetUserRole401 | SetUserRole403 | SetUserRole404 | SetUserRole429 | SetUserRole500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setUserRole>>, TError,{data: SetUserRoleBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setUserRole>>,
        TError,
        {data: SetUserRoleBody},
        TContext
      > => {

      const mutationOptions = getSetUserRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get an existing user
 */
export const getUser = (
    params?: GetUserParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUser200>(
      {url: `/api/auth/admin/get-user`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetUserQueryKey = (params?: GetUserParams,) => {
    return [
    `/api/auth/admin/get-user`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = GetUser400 | GetUser401 | GetUser403 | GetUser404 | GetUser429 | GetUser500>(params?: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = GetUser400 | GetUser401 | GetUser403 | GetUser404 | GetUser429 | GetUser500


export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = GetUser400 | GetUser401 | GetUser403 | GetUser404 | GetUser429 | GetUser500>(
 params: undefined |  GetUserParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = GetUser400 | GetUser401 | GetUser403 | GetUser404 | GetUser429 | GetUser500>(
 params?: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = GetUser400 | GetUser401 | GetUser403 | GetUser404 | GetUser429 | GetUser500>(
 params?: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = GetUser400 | GetUser401 | GetUser403 | GetUser404 | GetUser429 | GetUser500>(
 params?: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new user
 */
export const createUser = (
    createUserBody: CreateUserBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateUser200>(
      {url: `/api/auth/admin/create-user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserBody, signal
    },
      options);
    }
  


export const getCreateUserMutationOptions = <TError = CreateUser400 | CreateUser401 | CreateUser403 | CreateUser404 | CreateUser429 | CreateUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: CreateUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: CreateUserBody}, TContext> => {

const mutationKey = ['createUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, {data: CreateUserBody}> = (props) => {
          const {data} = props ?? {};

          return  createUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
    export type CreateUserMutationBody = CreateUserBody
    export type CreateUserMutationError = CreateUser400 | CreateUser401 | CreateUser403 | CreateUser404 | CreateUser429 | CreateUser500

    export const useCreateUser = <TError = CreateUser400 | CreateUser401 | CreateUser403 | CreateUser404 | CreateUser429 | CreateUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: CreateUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {data: CreateUserBody},
        TContext
      > => {

      const mutationOptions = getCreateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Update a user's details
 */
export const updateUserPostApiAuthAdminUpdateUser = (
    updateUserPostApiAuthAdminUpdateUserBody: UpdateUserPostApiAuthAdminUpdateUserBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UpdateUserPostApiAuthAdminUpdateUser200>(
      {url: `/api/auth/admin/update-user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateUserPostApiAuthAdminUpdateUserBody, signal
    },
      options);
    }
  


export const getUpdateUserPostApiAuthAdminUpdateUserMutationOptions = <TError = UpdateUserPostApiAuthAdminUpdateUser400 | UpdateUserPostApiAuthAdminUpdateUser401 | UpdateUserPostApiAuthAdminUpdateUser403 | UpdateUserPostApiAuthAdminUpdateUser404 | UpdateUserPostApiAuthAdminUpdateUser429 | UpdateUserPostApiAuthAdminUpdateUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserPostApiAuthAdminUpdateUser>>, TError,{data: UpdateUserPostApiAuthAdminUpdateUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserPostApiAuthAdminUpdateUser>>, TError,{data: UpdateUserPostApiAuthAdminUpdateUserBody}, TContext> => {

const mutationKey = ['updateUserPostApiAuthAdminUpdateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserPostApiAuthAdminUpdateUser>>, {data: UpdateUserPostApiAuthAdminUpdateUserBody}> = (props) => {
          const {data} = props ?? {};

          return  updateUserPostApiAuthAdminUpdateUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserPostApiAuthAdminUpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserPostApiAuthAdminUpdateUser>>>
    export type UpdateUserPostApiAuthAdminUpdateUserMutationBody = UpdateUserPostApiAuthAdminUpdateUserBody
    export type UpdateUserPostApiAuthAdminUpdateUserMutationError = UpdateUserPostApiAuthAdminUpdateUser400 | UpdateUserPostApiAuthAdminUpdateUser401 | UpdateUserPostApiAuthAdminUpdateUser403 | UpdateUserPostApiAuthAdminUpdateUser404 | UpdateUserPostApiAuthAdminUpdateUser429 | UpdateUserPostApiAuthAdminUpdateUser500

    export const useUpdateUserPostApiAuthAdminUpdateUser = <TError = UpdateUserPostApiAuthAdminUpdateUser400 | UpdateUserPostApiAuthAdminUpdateUser401 | UpdateUserPostApiAuthAdminUpdateUser403 | UpdateUserPostApiAuthAdminUpdateUser404 | UpdateUserPostApiAuthAdminUpdateUser429 | UpdateUserPostApiAuthAdminUpdateUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserPostApiAuthAdminUpdateUser>>, TError,{data: UpdateUserPostApiAuthAdminUpdateUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUserPostApiAuthAdminUpdateUser>>,
        TError,
        {data: UpdateUserPostApiAuthAdminUpdateUserBody},
        TContext
      > => {

      const mutationOptions = getUpdateUserPostApiAuthAdminUpdateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List users
 */
export const listUsers = (
    params?: ListUsersParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListUsers200>(
      {url: `/api/auth/admin/list-users`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListUsersQueryKey = (params?: ListUsersParams,) => {
    return [
    `/api/auth/admin/list-users`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListUsersQueryOptions = <TData = Awaited<ReturnType<typeof listUsers>>, TError = ListUsers400 | ListUsers401 | ListUsers403 | ListUsers404 | ListUsers429 | ListUsers500>(params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({ signal }) => listUsers(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof listUsers>>>
export type ListUsersQueryError = ListUsers400 | ListUsers401 | ListUsers403 | ListUsers404 | ListUsers429 | ListUsers500


export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ListUsers400 | ListUsers401 | ListUsers403 | ListUsers404 | ListUsers429 | ListUsers500>(
 params: undefined |  ListUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ListUsers400 | ListUsers401 | ListUsers403 | ListUsers404 | ListUsers429 | ListUsers500>(
 params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ListUsers400 | ListUsers401 | ListUsers403 | ListUsers404 | ListUsers429 | ListUsers500>(
 params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ListUsers400 | ListUsers401 | ListUsers403 | ListUsers404 | ListUsers429 | ListUsers500>(
 params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * List user sessions
 */
export const listUserSessionsPostApiAuthAdminListUserSessions = (
    listUserSessionsPostApiAuthAdminListUserSessionsBody: ListUserSessionsPostApiAuthAdminListUserSessionsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListUserSessionsPostApiAuthAdminListUserSessions200>(
      {url: `/api/auth/admin/list-user-sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: listUserSessionsPostApiAuthAdminListUserSessionsBody, signal
    },
      options);
    }
  


export const getListUserSessionsPostApiAuthAdminListUserSessionsMutationOptions = <TError = ListUserSessionsPostApiAuthAdminListUserSessions400 | ListUserSessionsPostApiAuthAdminListUserSessions401 | ListUserSessionsPostApiAuthAdminListUserSessions403 | ListUserSessionsPostApiAuthAdminListUserSessions404 | ListUserSessionsPostApiAuthAdminListUserSessions429 | ListUserSessionsPostApiAuthAdminListUserSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listUserSessionsPostApiAuthAdminListUserSessions>>, TError,{data: ListUserSessionsPostApiAuthAdminListUserSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof listUserSessionsPostApiAuthAdminListUserSessions>>, TError,{data: ListUserSessionsPostApiAuthAdminListUserSessionsBody}, TContext> => {

const mutationKey = ['listUserSessionsPostApiAuthAdminListUserSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listUserSessionsPostApiAuthAdminListUserSessions>>, {data: ListUserSessionsPostApiAuthAdminListUserSessionsBody}> = (props) => {
          const {data} = props ?? {};

          return  listUserSessionsPostApiAuthAdminListUserSessions(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ListUserSessionsPostApiAuthAdminListUserSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof listUserSessionsPostApiAuthAdminListUserSessions>>>
    export type ListUserSessionsPostApiAuthAdminListUserSessionsMutationBody = ListUserSessionsPostApiAuthAdminListUserSessionsBody
    export type ListUserSessionsPostApiAuthAdminListUserSessionsMutationError = ListUserSessionsPostApiAuthAdminListUserSessions400 | ListUserSessionsPostApiAuthAdminListUserSessions401 | ListUserSessionsPostApiAuthAdminListUserSessions403 | ListUserSessionsPostApiAuthAdminListUserSessions404 | ListUserSessionsPostApiAuthAdminListUserSessions429 | ListUserSessionsPostApiAuthAdminListUserSessions500

    export const useListUserSessionsPostApiAuthAdminListUserSessions = <TError = ListUserSessionsPostApiAuthAdminListUserSessions400 | ListUserSessionsPostApiAuthAdminListUserSessions401 | ListUserSessionsPostApiAuthAdminListUserSessions403 | ListUserSessionsPostApiAuthAdminListUserSessions404 | ListUserSessionsPostApiAuthAdminListUserSessions429 | ListUserSessionsPostApiAuthAdminListUserSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listUserSessionsPostApiAuthAdminListUserSessions>>, TError,{data: ListUserSessionsPostApiAuthAdminListUserSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listUserSessionsPostApiAuthAdminListUserSessions>>,
        TError,
        {data: ListUserSessionsPostApiAuthAdminListUserSessionsBody},
        TContext
      > => {

      const mutationOptions = getListUserSessionsPostApiAuthAdminListUserSessionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Unban a user
 */
export const unbanUser = (
    unbanUserBody: UnbanUserBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UnbanUser200>(
      {url: `/api/auth/admin/unban-user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: unbanUserBody, signal
    },
      options);
    }
  


export const getUnbanUserMutationOptions = <TError = UnbanUser400 | UnbanUser401 | UnbanUser403 | UnbanUser404 | UnbanUser429 | UnbanUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unbanUser>>, TError,{data: UnbanUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof unbanUser>>, TError,{data: UnbanUserBody}, TContext> => {

const mutationKey = ['unbanUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unbanUser>>, {data: UnbanUserBody}> = (props) => {
          const {data} = props ?? {};

          return  unbanUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnbanUserMutationResult = NonNullable<Awaited<ReturnType<typeof unbanUser>>>
    export type UnbanUserMutationBody = UnbanUserBody
    export type UnbanUserMutationError = UnbanUser400 | UnbanUser401 | UnbanUser403 | UnbanUser404 | UnbanUser429 | UnbanUser500

    export const useUnbanUser = <TError = UnbanUser400 | UnbanUser401 | UnbanUser403 | UnbanUser404 | UnbanUser429 | UnbanUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unbanUser>>, TError,{data: UnbanUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unbanUser>>,
        TError,
        {data: UnbanUserBody},
        TContext
      > => {

      const mutationOptions = getUnbanUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Ban a user
 */
export const banUser = (
    banUserBody: BanUserBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BanUser200>(
      {url: `/api/auth/admin/ban-user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: banUserBody, signal
    },
      options);
    }
  


export const getBanUserMutationOptions = <TError = BanUser400 | BanUser401 | BanUser403 | BanUser404 | BanUser429 | BanUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof banUser>>, TError,{data: BanUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof banUser>>, TError,{data: BanUserBody}, TContext> => {

const mutationKey = ['banUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof banUser>>, {data: BanUserBody}> = (props) => {
          const {data} = props ?? {};

          return  banUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BanUserMutationResult = NonNullable<Awaited<ReturnType<typeof banUser>>>
    export type BanUserMutationBody = BanUserBody
    export type BanUserMutationError = BanUser400 | BanUser401 | BanUser403 | BanUser404 | BanUser429 | BanUser500

    export const useBanUser = <TError = BanUser400 | BanUser401 | BanUser403 | BanUser404 | BanUser429 | BanUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof banUser>>, TError,{data: BanUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof banUser>>,
        TError,
        {data: BanUserBody},
        TContext
      > => {

      const mutationOptions = getBanUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Impersonate a user
 */
export const impersonateUser = (
    impersonateUserBody: ImpersonateUserBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ImpersonateUser200>(
      {url: `/api/auth/admin/impersonate-user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: impersonateUserBody, signal
    },
      options);
    }
  


export const getImpersonateUserMutationOptions = <TError = ImpersonateUser400 | ImpersonateUser401 | ImpersonateUser403 | ImpersonateUser404 | ImpersonateUser429 | ImpersonateUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof impersonateUser>>, TError,{data: ImpersonateUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof impersonateUser>>, TError,{data: ImpersonateUserBody}, TContext> => {

const mutationKey = ['impersonateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof impersonateUser>>, {data: ImpersonateUserBody}> = (props) => {
          const {data} = props ?? {};

          return  impersonateUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ImpersonateUserMutationResult = NonNullable<Awaited<ReturnType<typeof impersonateUser>>>
    export type ImpersonateUserMutationBody = ImpersonateUserBody
    export type ImpersonateUserMutationError = ImpersonateUser400 | ImpersonateUser401 | ImpersonateUser403 | ImpersonateUser404 | ImpersonateUser429 | ImpersonateUser500

    export const useImpersonateUser = <TError = ImpersonateUser400 | ImpersonateUser401 | ImpersonateUser403 | ImpersonateUser404 | ImpersonateUser429 | ImpersonateUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof impersonateUser>>, TError,{data: ImpersonateUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof impersonateUser>>,
        TError,
        {data: ImpersonateUserBody},
        TContext
      > => {

      const mutationOptions = getImpersonateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const postApiAuthAdminStopImpersonating = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/auth/admin/stop-impersonating`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiAuthAdminStopImpersonatingMutationOptions = <TError = PostApiAuthAdminStopImpersonating400 | PostApiAuthAdminStopImpersonating401 | PostApiAuthAdminStopImpersonating403 | PostApiAuthAdminStopImpersonating404 | PostApiAuthAdminStopImpersonating429 | PostApiAuthAdminStopImpersonating500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthAdminStopImpersonating>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthAdminStopImpersonating>>, TError,void, TContext> => {

const mutationKey = ['postApiAuthAdminStopImpersonating'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthAdminStopImpersonating>>, void> = () => {
          

          return  postApiAuthAdminStopImpersonating(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthAdminStopImpersonatingMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthAdminStopImpersonating>>>
    
    export type PostApiAuthAdminStopImpersonatingMutationError = PostApiAuthAdminStopImpersonating400 | PostApiAuthAdminStopImpersonating401 | PostApiAuthAdminStopImpersonating403 | PostApiAuthAdminStopImpersonating404 | PostApiAuthAdminStopImpersonating429 | PostApiAuthAdminStopImpersonating500

    export const usePostApiAuthAdminStopImpersonating = <TError = PostApiAuthAdminStopImpersonating400 | PostApiAuthAdminStopImpersonating401 | PostApiAuthAdminStopImpersonating403 | PostApiAuthAdminStopImpersonating404 | PostApiAuthAdminStopImpersonating429 | PostApiAuthAdminStopImpersonating500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthAdminStopImpersonating>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthAdminStopImpersonating>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiAuthAdminStopImpersonatingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Revoke a user session
 */
export const revokeUserSession = (
    revokeUserSessionBody: RevokeUserSessionBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RevokeUserSession200>(
      {url: `/api/auth/admin/revoke-user-session`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: revokeUserSessionBody, signal
    },
      options);
    }
  


export const getRevokeUserSessionMutationOptions = <TError = RevokeUserSession400 | RevokeUserSession401 | RevokeUserSession403 | RevokeUserSession404 | RevokeUserSession429 | RevokeUserSession500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeUserSession>>, TError,{data: RevokeUserSessionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeUserSession>>, TError,{data: RevokeUserSessionBody}, TContext> => {

const mutationKey = ['revokeUserSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeUserSession>>, {data: RevokeUserSessionBody}> = (props) => {
          const {data} = props ?? {};

          return  revokeUserSession(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RevokeUserSessionMutationResult = NonNullable<Awaited<ReturnType<typeof revokeUserSession>>>
    export type RevokeUserSessionMutationBody = RevokeUserSessionBody
    export type RevokeUserSessionMutationError = RevokeUserSession400 | RevokeUserSession401 | RevokeUserSession403 | RevokeUserSession404 | RevokeUserSession429 | RevokeUserSession500

    export const useRevokeUserSession = <TError = RevokeUserSession400 | RevokeUserSession401 | RevokeUserSession403 | RevokeUserSession404 | RevokeUserSession429 | RevokeUserSession500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeUserSession>>, TError,{data: RevokeUserSessionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeUserSession>>,
        TError,
        {data: RevokeUserSessionBody},
        TContext
      > => {

      const mutationOptions = getRevokeUserSessionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Revoke all user sessions
 */
export const revokeUserSessions = (
    revokeUserSessionsBody: RevokeUserSessionsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RevokeUserSessions200>(
      {url: `/api/auth/admin/revoke-user-sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: revokeUserSessionsBody, signal
    },
      options);
    }
  


export const getRevokeUserSessionsMutationOptions = <TError = RevokeUserSessions400 | RevokeUserSessions401 | RevokeUserSessions403 | RevokeUserSessions404 | RevokeUserSessions429 | RevokeUserSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeUserSessions>>, TError,{data: RevokeUserSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeUserSessions>>, TError,{data: RevokeUserSessionsBody}, TContext> => {

const mutationKey = ['revokeUserSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeUserSessions>>, {data: RevokeUserSessionsBody}> = (props) => {
          const {data} = props ?? {};

          return  revokeUserSessions(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RevokeUserSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof revokeUserSessions>>>
    export type RevokeUserSessionsMutationBody = RevokeUserSessionsBody
    export type RevokeUserSessionsMutationError = RevokeUserSessions400 | RevokeUserSessions401 | RevokeUserSessions403 | RevokeUserSessions404 | RevokeUserSessions429 | RevokeUserSessions500

    export const useRevokeUserSessions = <TError = RevokeUserSessions400 | RevokeUserSessions401 | RevokeUserSessions403 | RevokeUserSessions404 | RevokeUserSessions429 | RevokeUserSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeUserSessions>>, TError,{data: RevokeUserSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeUserSessions>>,
        TError,
        {data: RevokeUserSessionsBody},
        TContext
      > => {

      const mutationOptions = getRevokeUserSessionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a user and all their sessions and accounts. Cannot be undone.
 */
export const removeUser = (
    removeUserBody: RemoveUserBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RemoveUser200>(
      {url: `/api/auth/admin/remove-user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: removeUserBody, signal
    },
      options);
    }
  


export const getRemoveUserMutationOptions = <TError = RemoveUser400 | RemoveUser401 | RemoveUser403 | RemoveUser404 | RemoveUser429 | RemoveUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeUser>>, TError,{data: RemoveUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeUser>>, TError,{data: RemoveUserBody}, TContext> => {

const mutationKey = ['removeUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeUser>>, {data: RemoveUserBody}> = (props) => {
          const {data} = props ?? {};

          return  removeUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveUserMutationResult = NonNullable<Awaited<ReturnType<typeof removeUser>>>
    export type RemoveUserMutationBody = RemoveUserBody
    export type RemoveUserMutationError = RemoveUser400 | RemoveUser401 | RemoveUser403 | RemoveUser404 | RemoveUser429 | RemoveUser500

    export const useRemoveUser = <TError = RemoveUser400 | RemoveUser401 | RemoveUser403 | RemoveUser404 | RemoveUser429 | RemoveUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeUser>>, TError,{data: RemoveUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeUser>>,
        TError,
        {data: RemoveUserBody},
        TContext
      > => {

      const mutationOptions = getRemoveUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Set a user's password
 */
export const setUserPassword = (
    setUserPasswordBody: SetUserPasswordBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SetUserPassword200>(
      {url: `/api/auth/admin/set-user-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setUserPasswordBody, signal
    },
      options);
    }
  


export const getSetUserPasswordMutationOptions = <TError = SetUserPassword400 | SetUserPassword401 | SetUserPassword403 | SetUserPassword404 | SetUserPassword429 | SetUserPassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setUserPassword>>, TError,{data: SetUserPasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof setUserPassword>>, TError,{data: SetUserPasswordBody}, TContext> => {

const mutationKey = ['setUserPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setUserPassword>>, {data: SetUserPasswordBody}> = (props) => {
          const {data} = props ?? {};

          return  setUserPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SetUserPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof setUserPassword>>>
    export type SetUserPasswordMutationBody = SetUserPasswordBody
    export type SetUserPasswordMutationError = SetUserPassword400 | SetUserPassword401 | SetUserPassword403 | SetUserPassword404 | SetUserPassword429 | SetUserPassword500

    export const useSetUserPassword = <TError = SetUserPassword400 | SetUserPassword401 | SetUserPassword403 | SetUserPassword404 | SetUserPassword429 | SetUserPassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setUserPassword>>, TError,{data: SetUserPasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setUserPassword>>,
        TError,
        {data: SetUserPasswordBody},
        TContext
      > => {

      const mutationOptions = getSetUserPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Check if the user has permission
 */
export const postApiAuthAdminHasPermission = (
    postApiAuthAdminHasPermissionBody: PostApiAuthAdminHasPermissionBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostApiAuthAdminHasPermission200>(
      {url: `/api/auth/admin/has-permission`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthAdminHasPermissionBody, signal
    },
      options);
    }
  


export const getPostApiAuthAdminHasPermissionMutationOptions = <TError = PostApiAuthAdminHasPermission400 | PostApiAuthAdminHasPermission401 | PostApiAuthAdminHasPermission403 | PostApiAuthAdminHasPermission404 | PostApiAuthAdminHasPermission429 | PostApiAuthAdminHasPermission500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthAdminHasPermission>>, TError,{data: PostApiAuthAdminHasPermissionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthAdminHasPermission>>, TError,{data: PostApiAuthAdminHasPermissionBody}, TContext> => {

const mutationKey = ['postApiAuthAdminHasPermission'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthAdminHasPermission>>, {data: PostApiAuthAdminHasPermissionBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthAdminHasPermission(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthAdminHasPermissionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthAdminHasPermission>>>
    export type PostApiAuthAdminHasPermissionMutationBody = PostApiAuthAdminHasPermissionBody
    export type PostApiAuthAdminHasPermissionMutationError = PostApiAuthAdminHasPermission400 | PostApiAuthAdminHasPermission401 | PostApiAuthAdminHasPermission403 | PostApiAuthAdminHasPermission404 | PostApiAuthAdminHasPermission429 | PostApiAuthAdminHasPermission500

    export const usePostApiAuthAdminHasPermission = <TError = PostApiAuthAdminHasPermission400 | PostApiAuthAdminHasPermission401 | PostApiAuthAdminHasPermission403 | PostApiAuthAdminHasPermission404 | PostApiAuthAdminHasPermission429 | PostApiAuthAdminHasPermission500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthAdminHasPermission>>, TError,{data: PostApiAuthAdminHasPermissionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthAdminHasPermission>>,
        TError,
        {data: PostApiAuthAdminHasPermissionBody},
        TContext
      > => {

      const mutationOptions = getPostApiAuthAdminHasPermissionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    