/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NexxaTrade API
 * API documentation for NexxaTrade
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangeEmail200,
  ChangeEmail400,
  ChangeEmail401,
  ChangeEmail403,
  ChangeEmail404,
  ChangeEmail422,
  ChangeEmail429,
  ChangeEmail500,
  ChangeEmailBody,
  ChangePassword200,
  ChangePassword400,
  ChangePassword401,
  ChangePassword403,
  ChangePassword404,
  ChangePassword429,
  ChangePassword500,
  ChangePasswordBody,
  DeleteUser200,
  DeleteUser400,
  DeleteUser401,
  DeleteUser403,
  DeleteUser404,
  DeleteUser429,
  DeleteUser500,
  DeleteUserBody,
  GetApiAuthAccountInfo200,
  GetApiAuthAccountInfo400,
  GetApiAuthAccountInfo401,
  GetApiAuthAccountInfo403,
  GetApiAuthAccountInfo404,
  GetApiAuthAccountInfo429,
  GetApiAuthAccountInfo500,
  GetApiAuthDeleteUserCallback200,
  GetApiAuthDeleteUserCallback400,
  GetApiAuthDeleteUserCallback401,
  GetApiAuthDeleteUserCallback403,
  GetApiAuthDeleteUserCallback404,
  GetApiAuthDeleteUserCallback429,
  GetApiAuthDeleteUserCallback500,
  GetApiAuthDeleteUserCallbackParams,
  GetApiAuthError400,
  GetApiAuthError401,
  GetApiAuthError403,
  GetApiAuthError404,
  GetApiAuthError429,
  GetApiAuthError500,
  GetApiAuthOk200,
  GetApiAuthOk400,
  GetApiAuthOk401,
  GetApiAuthOk403,
  GetApiAuthOk404,
  GetApiAuthOk429,
  GetApiAuthOk500,
  GetApiAuthVerifyEmail200,
  GetApiAuthVerifyEmail400,
  GetApiAuthVerifyEmail401,
  GetApiAuthVerifyEmail403,
  GetApiAuthVerifyEmail404,
  GetApiAuthVerifyEmail429,
  GetApiAuthVerifyEmail500,
  GetApiAuthVerifyEmailParams,
  GetSession200,
  GetSession400,
  GetSession401,
  GetSession403,
  GetSession404,
  GetSession429,
  GetSession500,
  LinkSocialAccount200,
  LinkSocialAccount400,
  LinkSocialAccount401,
  LinkSocialAccount403,
  LinkSocialAccount404,
  LinkSocialAccount429,
  LinkSocialAccount500,
  LinkSocialAccountBody,
  ListUserAccounts200Item,
  ListUserAccounts400,
  ListUserAccounts401,
  ListUserAccounts403,
  ListUserAccounts404,
  ListUserAccounts429,
  ListUserAccounts500,
  PostApiAuthGetAccessToken200,
  PostApiAuthGetAccessToken401,
  PostApiAuthGetAccessToken403,
  PostApiAuthGetAccessToken404,
  PostApiAuthGetAccessToken429,
  PostApiAuthGetAccessToken500,
  PostApiAuthGetAccessTokenBody,
  PostApiAuthRefreshToken200,
  PostApiAuthRefreshToken401,
  PostApiAuthRefreshToken403,
  PostApiAuthRefreshToken404,
  PostApiAuthRefreshToken429,
  PostApiAuthRefreshToken500,
  PostApiAuthRefreshTokenBody,
  PostApiAuthRevokeOtherSessions200,
  PostApiAuthRevokeOtherSessions400,
  PostApiAuthRevokeOtherSessions401,
  PostApiAuthRevokeOtherSessions403,
  PostApiAuthRevokeOtherSessions404,
  PostApiAuthRevokeOtherSessions429,
  PostApiAuthRevokeOtherSessions500,
  PostApiAuthRevokeOtherSessionsBody,
  PostApiAuthRevokeSession200,
  PostApiAuthRevokeSession400,
  PostApiAuthRevokeSession401,
  PostApiAuthRevokeSession403,
  PostApiAuthRevokeSession404,
  PostApiAuthRevokeSession429,
  PostApiAuthRevokeSession500,
  PostApiAuthRevokeSessionBody,
  PostApiAuthRevokeSessions200,
  PostApiAuthRevokeSessions400,
  PostApiAuthRevokeSessions401,
  PostApiAuthRevokeSessions403,
  PostApiAuthRevokeSessions404,
  PostApiAuthRevokeSessions429,
  PostApiAuthRevokeSessions500,
  PostApiAuthRevokeSessionsBody,
  PostApiAuthUnlinkAccount200,
  PostApiAuthUnlinkAccount400,
  PostApiAuthUnlinkAccount401,
  PostApiAuthUnlinkAccount403,
  PostApiAuthUnlinkAccount404,
  PostApiAuthUnlinkAccount429,
  PostApiAuthUnlinkAccount500,
  PostApiAuthUnlinkAccountBody,
  RequestPasswordReset200,
  RequestPasswordReset400,
  RequestPasswordReset401,
  RequestPasswordReset403,
  RequestPasswordReset404,
  RequestPasswordReset429,
  RequestPasswordReset500,
  RequestPasswordResetBody,
  ResetPassword200,
  ResetPassword400,
  ResetPassword401,
  ResetPassword403,
  ResetPassword404,
  ResetPassword429,
  ResetPassword500,
  ResetPasswordBody,
  ResetPasswordCallback200,
  ResetPasswordCallback400,
  ResetPasswordCallback401,
  ResetPasswordCallback403,
  ResetPasswordCallback404,
  ResetPasswordCallback429,
  ResetPasswordCallback500,
  ResetPasswordCallbackParams,
  SendVerificationEmail200,
  SendVerificationEmail400,
  SendVerificationEmail401,
  SendVerificationEmail403,
  SendVerificationEmail404,
  SendVerificationEmail429,
  SendVerificationEmail500,
  SendVerificationEmailBody,
  SignInEmail200,
  SignInEmail400,
  SignInEmail401,
  SignInEmail403,
  SignInEmail404,
  SignInEmail429,
  SignInEmail500,
  SignInEmailBody,
  SignOut200,
  SignOut400,
  SignOut401,
  SignOut403,
  SignOut404,
  SignOut429,
  SignOut500,
  SignOutBody,
  SignUpWithEmailAndPassword200,
  SignUpWithEmailAndPassword400,
  SignUpWithEmailAndPassword401,
  SignUpWithEmailAndPassword403,
  SignUpWithEmailAndPassword404,
  SignUpWithEmailAndPassword422,
  SignUpWithEmailAndPassword429,
  SignUpWithEmailAndPassword500,
  SignUpWithEmailAndPasswordBody,
  SocialSignIn200,
  SocialSignIn400,
  SocialSignIn401,
  SocialSignIn403,
  SocialSignIn404,
  SocialSignIn429,
  SocialSignIn500,
  SocialSignInBody
} from '../generated.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Sign in with a social provider
 */
export const socialSignIn = (
    socialSignInBody: SocialSignInBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SocialSignIn200>(
      {url: `/api/auth/sign-in/social`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: socialSignInBody, signal
    },
      options);
    }
  


export const getSocialSignInMutationOptions = <TError = SocialSignIn400 | SocialSignIn401 | SocialSignIn403 | SocialSignIn404 | SocialSignIn429 | SocialSignIn500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialSignIn>>, TError,{data: SocialSignInBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof socialSignIn>>, TError,{data: SocialSignInBody}, TContext> => {

const mutationKey = ['socialSignIn'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof socialSignIn>>, {data: SocialSignInBody}> = (props) => {
          const {data} = props ?? {};

          return  socialSignIn(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SocialSignInMutationResult = NonNullable<Awaited<ReturnType<typeof socialSignIn>>>
    export type SocialSignInMutationBody = SocialSignInBody
    export type SocialSignInMutationError = SocialSignIn400 | SocialSignIn401 | SocialSignIn403 | SocialSignIn404 | SocialSignIn429 | SocialSignIn500

    export const useSocialSignIn = <TError = SocialSignIn400 | SocialSignIn401 | SocialSignIn403 | SocialSignIn404 | SocialSignIn429 | SocialSignIn500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialSignIn>>, TError,{data: SocialSignInBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof socialSignIn>>,
        TError,
        {data: SocialSignInBody},
        TContext
      > => {

      const mutationOptions = getSocialSignInMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get the current session
 */
export const getSession = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSession200>(
      {url: `/api/auth/get-session`, method: 'GET', signal
    },
      options);
    }
  



export const getGetSessionQueryKey = () => {
    return [
    `/api/auth/get-session`
    ] as const;
    }

    
export const getGetSessionQueryOptions = <TData = Awaited<ReturnType<typeof getSession>>, TError = GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({ signal }) => getSession(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getSession>>>
export type GetSessionQueryError = GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500


export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSession>>,
          TError,
          Awaited<ReturnType<typeof getSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSession>>,
          TError,
          Awaited<ReturnType<typeof getSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSessionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey }
}




/**
 * Sign out the current user
 */
export const signOut = (
    signOutBody: SignOutBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SignOut200>(
      {url: `/api/auth/sign-out`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signOutBody, signal
    },
      options);
    }
  


export const getSignOutMutationOptions = <TError = SignOut400 | SignOut401 | SignOut403 | SignOut404 | SignOut429 | SignOut500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError,{data: SignOutBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError,{data: SignOutBody}, TContext> => {

const mutationKey = ['signOut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signOut>>, {data: SignOutBody}> = (props) => {
          const {data} = props ?? {};

          return  signOut(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignOutMutationResult = NonNullable<Awaited<ReturnType<typeof signOut>>>
    export type SignOutMutationBody = SignOutBody
    export type SignOutMutationError = SignOut400 | SignOut401 | SignOut403 | SignOut404 | SignOut429 | SignOut500

    export const useSignOut = <TError = SignOut400 | SignOut401 | SignOut403 | SignOut404 | SignOut429 | SignOut500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError,{data: SignOutBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signOut>>,
        TError,
        {data: SignOutBody},
        TContext
      > => {

      const mutationOptions = getSignOutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Sign up a user using email and password
 */
export const signUpWithEmailAndPassword = (
    signUpWithEmailAndPasswordBody: SignUpWithEmailAndPasswordBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SignUpWithEmailAndPassword200>(
      {url: `/api/auth/sign-up/email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signUpWithEmailAndPasswordBody, signal
    },
      options);
    }
  


export const getSignUpWithEmailAndPasswordMutationOptions = <TError = SignUpWithEmailAndPassword400 | SignUpWithEmailAndPassword401 | SignUpWithEmailAndPassword403 | SignUpWithEmailAndPassword404 | SignUpWithEmailAndPassword422 | SignUpWithEmailAndPassword429 | SignUpWithEmailAndPassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signUpWithEmailAndPassword>>, TError,{data: SignUpWithEmailAndPasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof signUpWithEmailAndPassword>>, TError,{data: SignUpWithEmailAndPasswordBody}, TContext> => {

const mutationKey = ['signUpWithEmailAndPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signUpWithEmailAndPassword>>, {data: SignUpWithEmailAndPasswordBody}> = (props) => {
          const {data} = props ?? {};

          return  signUpWithEmailAndPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignUpWithEmailAndPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof signUpWithEmailAndPassword>>>
    export type SignUpWithEmailAndPasswordMutationBody = SignUpWithEmailAndPasswordBody
    export type SignUpWithEmailAndPasswordMutationError = SignUpWithEmailAndPassword400 | SignUpWithEmailAndPassword401 | SignUpWithEmailAndPassword403 | SignUpWithEmailAndPassword404 | SignUpWithEmailAndPassword422 | SignUpWithEmailAndPassword429 | SignUpWithEmailAndPassword500

    export const useSignUpWithEmailAndPassword = <TError = SignUpWithEmailAndPassword400 | SignUpWithEmailAndPassword401 | SignUpWithEmailAndPassword403 | SignUpWithEmailAndPassword404 | SignUpWithEmailAndPassword422 | SignUpWithEmailAndPassword429 | SignUpWithEmailAndPassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signUpWithEmailAndPassword>>, TError,{data: SignUpWithEmailAndPasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signUpWithEmailAndPassword>>,
        TError,
        {data: SignUpWithEmailAndPasswordBody},
        TContext
      > => {

      const mutationOptions = getSignUpWithEmailAndPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Sign in with email and password
 */
export const signInEmail = (
    signInEmailBody: SignInEmailBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SignInEmail200>(
      {url: `/api/auth/sign-in/email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signInEmailBody, signal
    },
      options);
    }
  


export const getSignInEmailMutationOptions = <TError = SignInEmail400 | SignInEmail401 | SignInEmail403 | SignInEmail404 | SignInEmail429 | SignInEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signInEmail>>, TError,{data: SignInEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof signInEmail>>, TError,{data: SignInEmailBody}, TContext> => {

const mutationKey = ['signInEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signInEmail>>, {data: SignInEmailBody}> = (props) => {
          const {data} = props ?? {};

          return  signInEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignInEmailMutationResult = NonNullable<Awaited<ReturnType<typeof signInEmail>>>
    export type SignInEmailMutationBody = SignInEmailBody
    export type SignInEmailMutationError = SignInEmail400 | SignInEmail401 | SignInEmail403 | SignInEmail404 | SignInEmail429 | SignInEmail500

    export const useSignInEmail = <TError = SignInEmail400 | SignInEmail401 | SignInEmail403 | SignInEmail404 | SignInEmail429 | SignInEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signInEmail>>, TError,{data: SignInEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signInEmail>>,
        TError,
        {data: SignInEmailBody},
        TContext
      > => {

      const mutationOptions = getSignInEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Reset the password for a user
 */
export const resetPassword = (
    resetPasswordBody: ResetPasswordBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ResetPassword200>(
      {url: `/api/auth/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordBody, signal
    },
      options);
    }
  


export const getResetPasswordMutationOptions = <TError = ResetPassword400 | ResetPassword401 | ResetPassword403 | ResetPassword404 | ResetPassword429 | ResetPassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordBody}, TContext> => {

const mutationKey = ['resetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetPassword>>, {data: ResetPasswordBody}> = (props) => {
          const {data} = props ?? {};

          return  resetPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>
    export type ResetPasswordMutationBody = ResetPasswordBody
    export type ResetPasswordMutationError = ResetPassword400 | ResetPassword401 | ResetPassword403 | ResetPassword404 | ResetPassword429 | ResetPassword500

    export const useResetPassword = <TError = ResetPassword400 | ResetPassword401 | ResetPassword403 | ResetPassword404 | ResetPassword429 | ResetPassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetPassword>>,
        TError,
        {data: ResetPasswordBody},
        TContext
      > => {

      const mutationOptions = getResetPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Verify the email of the user
 */
export const getApiAuthVerifyEmail = (
    params: GetApiAuthVerifyEmailParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiAuthVerifyEmail200>(
      {url: `/api/auth/verify-email`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiAuthVerifyEmailQueryKey = (params?: GetApiAuthVerifyEmailParams,) => {
    return [
    `/api/auth/verify-email`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAuthVerifyEmailQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError = GetApiAuthVerifyEmail400 | GetApiAuthVerifyEmail401 | GetApiAuthVerifyEmail403 | GetApiAuthVerifyEmail404 | GetApiAuthVerifyEmail429 | GetApiAuthVerifyEmail500>(params: GetApiAuthVerifyEmailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthVerifyEmailQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>> = ({ signal }) => getApiAuthVerifyEmail(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthVerifyEmailQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>>
export type GetApiAuthVerifyEmailQueryError = GetApiAuthVerifyEmail400 | GetApiAuthVerifyEmail401 | GetApiAuthVerifyEmail403 | GetApiAuthVerifyEmail404 | GetApiAuthVerifyEmail429 | GetApiAuthVerifyEmail500


export function useGetApiAuthVerifyEmail<TData = Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError = GetApiAuthVerifyEmail400 | GetApiAuthVerifyEmail401 | GetApiAuthVerifyEmail403 | GetApiAuthVerifyEmail404 | GetApiAuthVerifyEmail429 | GetApiAuthVerifyEmail500>(
 params: GetApiAuthVerifyEmailParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthVerifyEmail>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthVerifyEmail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthVerifyEmail<TData = Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError = GetApiAuthVerifyEmail400 | GetApiAuthVerifyEmail401 | GetApiAuthVerifyEmail403 | GetApiAuthVerifyEmail404 | GetApiAuthVerifyEmail429 | GetApiAuthVerifyEmail500>(
 params: GetApiAuthVerifyEmailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthVerifyEmail>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthVerifyEmail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthVerifyEmail<TData = Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError = GetApiAuthVerifyEmail400 | GetApiAuthVerifyEmail401 | GetApiAuthVerifyEmail403 | GetApiAuthVerifyEmail404 | GetApiAuthVerifyEmail429 | GetApiAuthVerifyEmail500>(
 params: GetApiAuthVerifyEmailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthVerifyEmail<TData = Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError = GetApiAuthVerifyEmail400 | GetApiAuthVerifyEmail401 | GetApiAuthVerifyEmail403 | GetApiAuthVerifyEmail404 | GetApiAuthVerifyEmail429 | GetApiAuthVerifyEmail500>(
 params: GetApiAuthVerifyEmailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthVerifyEmail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthVerifyEmailQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey }
}




/**
 * Send a verification email to the user
 */
export const sendVerificationEmail = (
    sendVerificationEmailBody: SendVerificationEmailBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SendVerificationEmail200>(
      {url: `/api/auth/send-verification-email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendVerificationEmailBody, signal
    },
      options);
    }
  


export const getSendVerificationEmailMutationOptions = <TError = SendVerificationEmail400 | SendVerificationEmail401 | SendVerificationEmail403 | SendVerificationEmail404 | SendVerificationEmail429 | SendVerificationEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendVerificationEmail>>, TError,{data: SendVerificationEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendVerificationEmail>>, TError,{data: SendVerificationEmailBody}, TContext> => {

const mutationKey = ['sendVerificationEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendVerificationEmail>>, {data: SendVerificationEmailBody}> = (props) => {
          const {data} = props ?? {};

          return  sendVerificationEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SendVerificationEmailMutationResult = NonNullable<Awaited<ReturnType<typeof sendVerificationEmail>>>
    export type SendVerificationEmailMutationBody = SendVerificationEmailBody
    export type SendVerificationEmailMutationError = SendVerificationEmail400 | SendVerificationEmail401 | SendVerificationEmail403 | SendVerificationEmail404 | SendVerificationEmail429 | SendVerificationEmail500

    export const useSendVerificationEmail = <TError = SendVerificationEmail400 | SendVerificationEmail401 | SendVerificationEmail403 | SendVerificationEmail404 | SendVerificationEmail429 | SendVerificationEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendVerificationEmail>>, TError,{data: SendVerificationEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendVerificationEmail>>,
        TError,
        {data: SendVerificationEmailBody},
        TContext
      > => {

      const mutationOptions = getSendVerificationEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const changeEmail = (
    changeEmailBody: ChangeEmailBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ChangeEmail200>(
      {url: `/api/auth/change-email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changeEmailBody, signal
    },
      options);
    }
  


export const getChangeEmailMutationOptions = <TError = ChangeEmail400 | ChangeEmail401 | ChangeEmail403 | ChangeEmail404 | ChangeEmail422 | ChangeEmail429 | ChangeEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeEmail>>, TError,{data: ChangeEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof changeEmail>>, TError,{data: ChangeEmailBody}, TContext> => {

const mutationKey = ['changeEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeEmail>>, {data: ChangeEmailBody}> = (props) => {
          const {data} = props ?? {};

          return  changeEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeEmailMutationResult = NonNullable<Awaited<ReturnType<typeof changeEmail>>>
    export type ChangeEmailMutationBody = ChangeEmailBody
    export type ChangeEmailMutationError = ChangeEmail400 | ChangeEmail401 | ChangeEmail403 | ChangeEmail404 | ChangeEmail422 | ChangeEmail429 | ChangeEmail500

    export const useChangeEmail = <TError = ChangeEmail400 | ChangeEmail401 | ChangeEmail403 | ChangeEmail404 | ChangeEmail422 | ChangeEmail429 | ChangeEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeEmail>>, TError,{data: ChangeEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeEmail>>,
        TError,
        {data: ChangeEmailBody},
        TContext
      > => {

      const mutationOptions = getChangeEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Change the password of the user
 */
export const changePassword = (
    changePasswordBody: ChangePasswordBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ChangePassword200>(
      {url: `/api/auth/change-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordBody, signal
    },
      options);
    }
  


export const getChangePasswordMutationOptions = <TError = ChangePassword400 | ChangePassword401 | ChangePassword403 | ChangePassword404 | ChangePassword429 | ChangePassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordBody}, TContext> => {

const mutationKey = ['changePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePassword>>, {data: ChangePasswordBody}> = (props) => {
          const {data} = props ?? {};

          return  changePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
    export type ChangePasswordMutationBody = ChangePasswordBody
    export type ChangePasswordMutationError = ChangePassword400 | ChangePassword401 | ChangePassword403 | ChangePassword404 | ChangePassword429 | ChangePassword500

    export const useChangePassword = <TError = ChangePassword400 | ChangePassword401 | ChangePassword403 | ChangePassword404 | ChangePassword429 | ChangePassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changePassword>>,
        TError,
        {data: ChangePasswordBody},
        TContext
      > => {

      const mutationOptions = getChangePasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete the user
 */
export const deleteUser = (
    deleteUserBody: DeleteUserBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DeleteUser200>(
      {url: `/api/auth/delete-user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteUserBody, signal
    },
      options);
    }
  


export const getDeleteUserMutationOptions = <TError = DeleteUser400 | DeleteUser401 | DeleteUser403 | DeleteUser404 | DeleteUser429 | DeleteUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: DeleteUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: DeleteUserBody}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {data: DeleteUserBody}> = (props) => {
          const {data} = props ?? {};

          return  deleteUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    export type DeleteUserMutationBody = DeleteUserBody
    export type DeleteUserMutationError = DeleteUser400 | DeleteUser401 | DeleteUser403 | DeleteUser404 | DeleteUser429 | DeleteUser500

    export const useDeleteUser = <TError = DeleteUser400 | DeleteUser401 | DeleteUser403 | DeleteUser404 | DeleteUser429 | DeleteUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: DeleteUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {data: DeleteUserBody},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Send a password reset email to the user
 */
export const requestPasswordReset = (
    requestPasswordResetBody: RequestPasswordResetBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RequestPasswordReset200>(
      {url: `/api/auth/request-password-reset`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestPasswordResetBody, signal
    },
      options);
    }
  


export const getRequestPasswordResetMutationOptions = <TError = RequestPasswordReset400 | RequestPasswordReset401 | RequestPasswordReset403 | RequestPasswordReset404 | RequestPasswordReset429 | RequestPasswordReset500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError,{data: RequestPasswordResetBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError,{data: RequestPasswordResetBody}, TContext> => {

const mutationKey = ['requestPasswordReset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestPasswordReset>>, {data: RequestPasswordResetBody}> = (props) => {
          const {data} = props ?? {};

          return  requestPasswordReset(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RequestPasswordResetMutationResult = NonNullable<Awaited<ReturnType<typeof requestPasswordReset>>>
    export type RequestPasswordResetMutationBody = RequestPasswordResetBody
    export type RequestPasswordResetMutationError = RequestPasswordReset400 | RequestPasswordReset401 | RequestPasswordReset403 | RequestPasswordReset404 | RequestPasswordReset429 | RequestPasswordReset500

    export const useRequestPasswordReset = <TError = RequestPasswordReset400 | RequestPasswordReset401 | RequestPasswordReset403 | RequestPasswordReset404 | RequestPasswordReset429 | RequestPasswordReset500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError,{data: RequestPasswordResetBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof requestPasswordReset>>,
        TError,
        {data: RequestPasswordResetBody},
        TContext
      > => {

      const mutationOptions = getRequestPasswordResetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Redirects the user to the callback URL with the token
 */
export const resetPasswordCallback = (
    token: string,
    params: ResetPasswordCallbackParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ResetPasswordCallback200>(
      {url: `/api/auth/reset-password/${token}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getResetPasswordCallbackQueryKey = (token?: string,
    params?: ResetPasswordCallbackParams,) => {
    return [
    `/api/auth/reset-password/${token}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getResetPasswordCallbackQueryOptions = <TData = Awaited<ReturnType<typeof resetPasswordCallback>>, TError = ResetPasswordCallback400 | ResetPasswordCallback401 | ResetPasswordCallback403 | ResetPasswordCallback404 | ResetPasswordCallback429 | ResetPasswordCallback500>(token: string,
    params: ResetPasswordCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResetPasswordCallbackQueryKey(token,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof resetPasswordCallback>>> = ({ signal }) => resetPasswordCallback(token,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResetPasswordCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof resetPasswordCallback>>>
export type ResetPasswordCallbackQueryError = ResetPasswordCallback400 | ResetPasswordCallback401 | ResetPasswordCallback403 | ResetPasswordCallback404 | ResetPasswordCallback429 | ResetPasswordCallback500


export function useResetPasswordCallback<TData = Awaited<ReturnType<typeof resetPasswordCallback>>, TError = ResetPasswordCallback400 | ResetPasswordCallback401 | ResetPasswordCallback403 | ResetPasswordCallback404 | ResetPasswordCallback429 | ResetPasswordCallback500>(
 token: string,
    params: ResetPasswordCallbackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resetPasswordCallback>>,
          TError,
          Awaited<ReturnType<typeof resetPasswordCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResetPasswordCallback<TData = Awaited<ReturnType<typeof resetPasswordCallback>>, TError = ResetPasswordCallback400 | ResetPasswordCallback401 | ResetPasswordCallback403 | ResetPasswordCallback404 | ResetPasswordCallback429 | ResetPasswordCallback500>(
 token: string,
    params: ResetPasswordCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resetPasswordCallback>>,
          TError,
          Awaited<ReturnType<typeof resetPasswordCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResetPasswordCallback<TData = Awaited<ReturnType<typeof resetPasswordCallback>>, TError = ResetPasswordCallback400 | ResetPasswordCallback401 | ResetPasswordCallback403 | ResetPasswordCallback404 | ResetPasswordCallback429 | ResetPasswordCallback500>(
 token: string,
    params: ResetPasswordCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useResetPasswordCallback<TData = Awaited<ReturnType<typeof resetPasswordCallback>>, TError = ResetPasswordCallback400 | ResetPasswordCallback401 | ResetPasswordCallback403 | ResetPasswordCallback404 | ResetPasswordCallback429 | ResetPasswordCallback500>(
 token: string,
    params: ResetPasswordCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResetPasswordCallbackQueryOptions(token,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey }
}




/**
 * Revoke a single session
 */
export const postApiAuthRevokeSession = (
    postApiAuthRevokeSessionBody: PostApiAuthRevokeSessionBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostApiAuthRevokeSession200>(
      {url: `/api/auth/revoke-session`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthRevokeSessionBody, signal
    },
      options);
    }
  


export const getPostApiAuthRevokeSessionMutationOptions = <TError = PostApiAuthRevokeSession400 | PostApiAuthRevokeSession401 | PostApiAuthRevokeSession403 | PostApiAuthRevokeSession404 | PostApiAuthRevokeSession429 | PostApiAuthRevokeSession500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRevokeSession>>, TError,{data: PostApiAuthRevokeSessionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRevokeSession>>, TError,{data: PostApiAuthRevokeSessionBody}, TContext> => {

const mutationKey = ['postApiAuthRevokeSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRevokeSession>>, {data: PostApiAuthRevokeSessionBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRevokeSession(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRevokeSessionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRevokeSession>>>
    export type PostApiAuthRevokeSessionMutationBody = PostApiAuthRevokeSessionBody
    export type PostApiAuthRevokeSessionMutationError = PostApiAuthRevokeSession400 | PostApiAuthRevokeSession401 | PostApiAuthRevokeSession403 | PostApiAuthRevokeSession404 | PostApiAuthRevokeSession429 | PostApiAuthRevokeSession500

    export const usePostApiAuthRevokeSession = <TError = PostApiAuthRevokeSession400 | PostApiAuthRevokeSession401 | PostApiAuthRevokeSession403 | PostApiAuthRevokeSession404 | PostApiAuthRevokeSession429 | PostApiAuthRevokeSession500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRevokeSession>>, TError,{data: PostApiAuthRevokeSessionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRevokeSession>>,
        TError,
        {data: PostApiAuthRevokeSessionBody},
        TContext
      > => {

      const mutationOptions = getPostApiAuthRevokeSessionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Revoke all sessions for the user
 */
export const postApiAuthRevokeSessions = (
    postApiAuthRevokeSessionsBody: PostApiAuthRevokeSessionsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostApiAuthRevokeSessions200>(
      {url: `/api/auth/revoke-sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthRevokeSessionsBody, signal
    },
      options);
    }
  


export const getPostApiAuthRevokeSessionsMutationOptions = <TError = PostApiAuthRevokeSessions400 | PostApiAuthRevokeSessions401 | PostApiAuthRevokeSessions403 | PostApiAuthRevokeSessions404 | PostApiAuthRevokeSessions429 | PostApiAuthRevokeSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRevokeSessions>>, TError,{data: PostApiAuthRevokeSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRevokeSessions>>, TError,{data: PostApiAuthRevokeSessionsBody}, TContext> => {

const mutationKey = ['postApiAuthRevokeSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRevokeSessions>>, {data: PostApiAuthRevokeSessionsBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRevokeSessions(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRevokeSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRevokeSessions>>>
    export type PostApiAuthRevokeSessionsMutationBody = PostApiAuthRevokeSessionsBody
    export type PostApiAuthRevokeSessionsMutationError = PostApiAuthRevokeSessions400 | PostApiAuthRevokeSessions401 | PostApiAuthRevokeSessions403 | PostApiAuthRevokeSessions404 | PostApiAuthRevokeSessions429 | PostApiAuthRevokeSessions500

    export const usePostApiAuthRevokeSessions = <TError = PostApiAuthRevokeSessions400 | PostApiAuthRevokeSessions401 | PostApiAuthRevokeSessions403 | PostApiAuthRevokeSessions404 | PostApiAuthRevokeSessions429 | PostApiAuthRevokeSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRevokeSessions>>, TError,{data: PostApiAuthRevokeSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRevokeSessions>>,
        TError,
        {data: PostApiAuthRevokeSessionsBody},
        TContext
      > => {

      const mutationOptions = getPostApiAuthRevokeSessionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Revoke all other sessions for the user except the current one
 */
export const postApiAuthRevokeOtherSessions = (
    postApiAuthRevokeOtherSessionsBody: PostApiAuthRevokeOtherSessionsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostApiAuthRevokeOtherSessions200>(
      {url: `/api/auth/revoke-other-sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthRevokeOtherSessionsBody, signal
    },
      options);
    }
  


export const getPostApiAuthRevokeOtherSessionsMutationOptions = <TError = PostApiAuthRevokeOtherSessions400 | PostApiAuthRevokeOtherSessions401 | PostApiAuthRevokeOtherSessions403 | PostApiAuthRevokeOtherSessions404 | PostApiAuthRevokeOtherSessions429 | PostApiAuthRevokeOtherSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>, TError,{data: PostApiAuthRevokeOtherSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>, TError,{data: PostApiAuthRevokeOtherSessionsBody}, TContext> => {

const mutationKey = ['postApiAuthRevokeOtherSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>, {data: PostApiAuthRevokeOtherSessionsBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRevokeOtherSessions(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRevokeOtherSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>>
    export type PostApiAuthRevokeOtherSessionsMutationBody = PostApiAuthRevokeOtherSessionsBody
    export type PostApiAuthRevokeOtherSessionsMutationError = PostApiAuthRevokeOtherSessions400 | PostApiAuthRevokeOtherSessions401 | PostApiAuthRevokeOtherSessions403 | PostApiAuthRevokeOtherSessions404 | PostApiAuthRevokeOtherSessions429 | PostApiAuthRevokeOtherSessions500

    export const usePostApiAuthRevokeOtherSessions = <TError = PostApiAuthRevokeOtherSessions400 | PostApiAuthRevokeOtherSessions401 | PostApiAuthRevokeOtherSessions403 | PostApiAuthRevokeOtherSessions404 | PostApiAuthRevokeOtherSessions429 | PostApiAuthRevokeOtherSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>, TError,{data: PostApiAuthRevokeOtherSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRevokeOtherSessions>>,
        TError,
        {data: PostApiAuthRevokeOtherSessionsBody},
        TContext
      > => {

      const mutationOptions = getPostApiAuthRevokeOtherSessionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Link a social account to the user
 */
export const linkSocialAccount = (
    linkSocialAccountBody: LinkSocialAccountBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LinkSocialAccount200>(
      {url: `/api/auth/link-social`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linkSocialAccountBody, signal
    },
      options);
    }
  


export const getLinkSocialAccountMutationOptions = <TError = LinkSocialAccount400 | LinkSocialAccount401 | LinkSocialAccount403 | LinkSocialAccount404 | LinkSocialAccount429 | LinkSocialAccount500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkSocialAccount>>, TError,{data: LinkSocialAccountBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof linkSocialAccount>>, TError,{data: LinkSocialAccountBody}, TContext> => {

const mutationKey = ['linkSocialAccount'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof linkSocialAccount>>, {data: LinkSocialAccountBody}> = (props) => {
          const {data} = props ?? {};

          return  linkSocialAccount(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LinkSocialAccountMutationResult = NonNullable<Awaited<ReturnType<typeof linkSocialAccount>>>
    export type LinkSocialAccountMutationBody = LinkSocialAccountBody
    export type LinkSocialAccountMutationError = LinkSocialAccount400 | LinkSocialAccount401 | LinkSocialAccount403 | LinkSocialAccount404 | LinkSocialAccount429 | LinkSocialAccount500

    export const useLinkSocialAccount = <TError = LinkSocialAccount400 | LinkSocialAccount401 | LinkSocialAccount403 | LinkSocialAccount404 | LinkSocialAccount429 | LinkSocialAccount500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkSocialAccount>>, TError,{data: LinkSocialAccountBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof linkSocialAccount>>,
        TError,
        {data: LinkSocialAccountBody},
        TContext
      > => {

      const mutationOptions = getLinkSocialAccountMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List all accounts linked to the user
 */
export const listUserAccounts = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListUserAccounts200Item[]>(
      {url: `/api/auth/list-accounts`, method: 'GET', signal
    },
      options);
    }
  



export const getListUserAccountsQueryKey = () => {
    return [
    `/api/auth/list-accounts`
    ] as const;
    }

    
export const getListUserAccountsQueryOptions = <TData = Awaited<ReturnType<typeof listUserAccounts>>, TError = ListUserAccounts400 | ListUserAccounts401 | ListUserAccounts403 | ListUserAccounts404 | ListUserAccounts429 | ListUserAccounts500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUserAccountsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUserAccounts>>> = ({ signal }) => listUserAccounts(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUserAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof listUserAccounts>>>
export type ListUserAccountsQueryError = ListUserAccounts400 | ListUserAccounts401 | ListUserAccounts403 | ListUserAccounts404 | ListUserAccounts429 | ListUserAccounts500


export function useListUserAccounts<TData = Awaited<ReturnType<typeof listUserAccounts>>, TError = ListUserAccounts400 | ListUserAccounts401 | ListUserAccounts403 | ListUserAccounts404 | ListUserAccounts429 | ListUserAccounts500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUserAccounts>>,
          TError,
          Awaited<ReturnType<typeof listUserAccounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUserAccounts<TData = Awaited<ReturnType<typeof listUserAccounts>>, TError = ListUserAccounts400 | ListUserAccounts401 | ListUserAccounts403 | ListUserAccounts404 | ListUserAccounts429 | ListUserAccounts500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUserAccounts>>,
          TError,
          Awaited<ReturnType<typeof listUserAccounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUserAccounts<TData = Awaited<ReturnType<typeof listUserAccounts>>, TError = ListUserAccounts400 | ListUserAccounts401 | ListUserAccounts403 | ListUserAccounts404 | ListUserAccounts429 | ListUserAccounts500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListUserAccounts<TData = Awaited<ReturnType<typeof listUserAccounts>>, TError = ListUserAccounts400 | ListUserAccounts401 | ListUserAccounts403 | ListUserAccounts404 | ListUserAccounts429 | ListUserAccounts500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUserAccountsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey }
}




/**
 * Callback to complete user deletion with verification token
 */
export const getApiAuthDeleteUserCallback = (
    params?: GetApiAuthDeleteUserCallbackParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiAuthDeleteUserCallback200>(
      {url: `/api/auth/delete-user/callback`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiAuthDeleteUserCallbackQueryKey = (params?: GetApiAuthDeleteUserCallbackParams,) => {
    return [
    `/api/auth/delete-user/callback`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAuthDeleteUserCallbackQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError = GetApiAuthDeleteUserCallback400 | GetApiAuthDeleteUserCallback401 | GetApiAuthDeleteUserCallback403 | GetApiAuthDeleteUserCallback404 | GetApiAuthDeleteUserCallback429 | GetApiAuthDeleteUserCallback500>(params?: GetApiAuthDeleteUserCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthDeleteUserCallbackQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>> = ({ signal }) => getApiAuthDeleteUserCallback(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthDeleteUserCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>>
export type GetApiAuthDeleteUserCallbackQueryError = GetApiAuthDeleteUserCallback400 | GetApiAuthDeleteUserCallback401 | GetApiAuthDeleteUserCallback403 | GetApiAuthDeleteUserCallback404 | GetApiAuthDeleteUserCallback429 | GetApiAuthDeleteUserCallback500


export function useGetApiAuthDeleteUserCallback<TData = Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError = GetApiAuthDeleteUserCallback400 | GetApiAuthDeleteUserCallback401 | GetApiAuthDeleteUserCallback403 | GetApiAuthDeleteUserCallback404 | GetApiAuthDeleteUserCallback429 | GetApiAuthDeleteUserCallback500>(
 params: undefined |  GetApiAuthDeleteUserCallbackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthDeleteUserCallback<TData = Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError = GetApiAuthDeleteUserCallback400 | GetApiAuthDeleteUserCallback401 | GetApiAuthDeleteUserCallback403 | GetApiAuthDeleteUserCallback404 | GetApiAuthDeleteUserCallback429 | GetApiAuthDeleteUserCallback500>(
 params?: GetApiAuthDeleteUserCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthDeleteUserCallback<TData = Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError = GetApiAuthDeleteUserCallback400 | GetApiAuthDeleteUserCallback401 | GetApiAuthDeleteUserCallback403 | GetApiAuthDeleteUserCallback404 | GetApiAuthDeleteUserCallback429 | GetApiAuthDeleteUserCallback500>(
 params?: GetApiAuthDeleteUserCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthDeleteUserCallback<TData = Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError = GetApiAuthDeleteUserCallback400 | GetApiAuthDeleteUserCallback401 | GetApiAuthDeleteUserCallback403 | GetApiAuthDeleteUserCallback404 | GetApiAuthDeleteUserCallback429 | GetApiAuthDeleteUserCallback500>(
 params?: GetApiAuthDeleteUserCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthDeleteUserCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthDeleteUserCallbackQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey }
}




/**
 * Unlink an account
 */
export const postApiAuthUnlinkAccount = (
    postApiAuthUnlinkAccountBody: PostApiAuthUnlinkAccountBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostApiAuthUnlinkAccount200>(
      {url: `/api/auth/unlink-account`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthUnlinkAccountBody, signal
    },
      options);
    }
  


export const getPostApiAuthUnlinkAccountMutationOptions = <TError = PostApiAuthUnlinkAccount400 | PostApiAuthUnlinkAccount401 | PostApiAuthUnlinkAccount403 | PostApiAuthUnlinkAccount404 | PostApiAuthUnlinkAccount429 | PostApiAuthUnlinkAccount500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>, TError,{data: PostApiAuthUnlinkAccountBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>, TError,{data: PostApiAuthUnlinkAccountBody}, TContext> => {

const mutationKey = ['postApiAuthUnlinkAccount'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>, {data: PostApiAuthUnlinkAccountBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthUnlinkAccount(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthUnlinkAccountMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>>
    export type PostApiAuthUnlinkAccountMutationBody = PostApiAuthUnlinkAccountBody
    export type PostApiAuthUnlinkAccountMutationError = PostApiAuthUnlinkAccount400 | PostApiAuthUnlinkAccount401 | PostApiAuthUnlinkAccount403 | PostApiAuthUnlinkAccount404 | PostApiAuthUnlinkAccount429 | PostApiAuthUnlinkAccount500

    export const usePostApiAuthUnlinkAccount = <TError = PostApiAuthUnlinkAccount400 | PostApiAuthUnlinkAccount401 | PostApiAuthUnlinkAccount403 | PostApiAuthUnlinkAccount404 | PostApiAuthUnlinkAccount429 | PostApiAuthUnlinkAccount500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>, TError,{data: PostApiAuthUnlinkAccountBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthUnlinkAccount>>,
        TError,
        {data: PostApiAuthUnlinkAccountBody},
        TContext
      > => {

      const mutationOptions = getPostApiAuthUnlinkAccountMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Refresh the access token using a refresh token
 */
export const postApiAuthRefreshToken = (
    postApiAuthRefreshTokenBody: PostApiAuthRefreshTokenBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostApiAuthRefreshToken200>(
      {url: `/api/auth/refresh-token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthRefreshTokenBody, signal
    },
      options);
    }
  


export const getPostApiAuthRefreshTokenMutationOptions = <TError = void | PostApiAuthRefreshToken401 | PostApiAuthRefreshToken403 | PostApiAuthRefreshToken404 | PostApiAuthRefreshToken429 | PostApiAuthRefreshToken500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefreshToken>>, TError,{data: PostApiAuthRefreshTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefreshToken>>, TError,{data: PostApiAuthRefreshTokenBody}, TContext> => {

const mutationKey = ['postApiAuthRefreshToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRefreshToken>>, {data: PostApiAuthRefreshTokenBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRefreshToken(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRefreshToken>>>
    export type PostApiAuthRefreshTokenMutationBody = PostApiAuthRefreshTokenBody
    export type PostApiAuthRefreshTokenMutationError = void | PostApiAuthRefreshToken401 | PostApiAuthRefreshToken403 | PostApiAuthRefreshToken404 | PostApiAuthRefreshToken429 | PostApiAuthRefreshToken500

    export const usePostApiAuthRefreshToken = <TError = void | PostApiAuthRefreshToken401 | PostApiAuthRefreshToken403 | PostApiAuthRefreshToken404 | PostApiAuthRefreshToken429 | PostApiAuthRefreshToken500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefreshToken>>, TError,{data: PostApiAuthRefreshTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRefreshToken>>,
        TError,
        {data: PostApiAuthRefreshTokenBody},
        TContext
      > => {

      const mutationOptions = getPostApiAuthRefreshTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get a valid access token, doing a refresh if needed
 */
export const postApiAuthGetAccessToken = (
    postApiAuthGetAccessTokenBody: PostApiAuthGetAccessTokenBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostApiAuthGetAccessToken200>(
      {url: `/api/auth/get-access-token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthGetAccessTokenBody, signal
    },
      options);
    }
  


export const getPostApiAuthGetAccessTokenMutationOptions = <TError = void | PostApiAuthGetAccessToken401 | PostApiAuthGetAccessToken403 | PostApiAuthGetAccessToken404 | PostApiAuthGetAccessToken429 | PostApiAuthGetAccessToken500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthGetAccessToken>>, TError,{data: PostApiAuthGetAccessTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthGetAccessToken>>, TError,{data: PostApiAuthGetAccessTokenBody}, TContext> => {

const mutationKey = ['postApiAuthGetAccessToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthGetAccessToken>>, {data: PostApiAuthGetAccessTokenBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthGetAccessToken(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthGetAccessTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthGetAccessToken>>>
    export type PostApiAuthGetAccessTokenMutationBody = PostApiAuthGetAccessTokenBody
    export type PostApiAuthGetAccessTokenMutationError = void | PostApiAuthGetAccessToken401 | PostApiAuthGetAccessToken403 | PostApiAuthGetAccessToken404 | PostApiAuthGetAccessToken429 | PostApiAuthGetAccessToken500

    export const usePostApiAuthGetAccessToken = <TError = void | PostApiAuthGetAccessToken401 | PostApiAuthGetAccessToken403 | PostApiAuthGetAccessToken404 | PostApiAuthGetAccessToken429 | PostApiAuthGetAccessToken500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthGetAccessToken>>, TError,{data: PostApiAuthGetAccessTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthGetAccessToken>>,
        TError,
        {data: PostApiAuthGetAccessTokenBody},
        TContext
      > => {

      const mutationOptions = getPostApiAuthGetAccessTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get the account info provided by the provider
 */
export const getApiAuthAccountInfo = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiAuthAccountInfo200>(
      {url: `/api/auth/account-info`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAuthAccountInfoQueryKey = () => {
    return [
    `/api/auth/account-info`
    ] as const;
    }

    
export const getGetApiAuthAccountInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError = GetApiAuthAccountInfo400 | GetApiAuthAccountInfo401 | GetApiAuthAccountInfo403 | GetApiAuthAccountInfo404 | GetApiAuthAccountInfo429 | GetApiAuthAccountInfo500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthAccountInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthAccountInfo>>> = ({ signal }) => getApiAuthAccountInfo(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthAccountInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthAccountInfo>>>
export type GetApiAuthAccountInfoQueryError = GetApiAuthAccountInfo400 | GetApiAuthAccountInfo401 | GetApiAuthAccountInfo403 | GetApiAuthAccountInfo404 | GetApiAuthAccountInfo429 | GetApiAuthAccountInfo500


export function useGetApiAuthAccountInfo<TData = Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError = GetApiAuthAccountInfo400 | GetApiAuthAccountInfo401 | GetApiAuthAccountInfo403 | GetApiAuthAccountInfo404 | GetApiAuthAccountInfo429 | GetApiAuthAccountInfo500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthAccountInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthAccountInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthAccountInfo<TData = Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError = GetApiAuthAccountInfo400 | GetApiAuthAccountInfo401 | GetApiAuthAccountInfo403 | GetApiAuthAccountInfo404 | GetApiAuthAccountInfo429 | GetApiAuthAccountInfo500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthAccountInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthAccountInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthAccountInfo<TData = Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError = GetApiAuthAccountInfo400 | GetApiAuthAccountInfo401 | GetApiAuthAccountInfo403 | GetApiAuthAccountInfo404 | GetApiAuthAccountInfo429 | GetApiAuthAccountInfo500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthAccountInfo<TData = Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError = GetApiAuthAccountInfo400 | GetApiAuthAccountInfo401 | GetApiAuthAccountInfo403 | GetApiAuthAccountInfo404 | GetApiAuthAccountInfo429 | GetApiAuthAccountInfo500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthAccountInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthAccountInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey }
}




/**
 * Check if the API is working
 */
export const getApiAuthOk = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetApiAuthOk200>(
      {url: `/api/auth/ok`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAuthOkQueryKey = () => {
    return [
    `/api/auth/ok`
    ] as const;
    }

    
export const getGetApiAuthOkQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthOk>>, TError = GetApiAuthOk400 | GetApiAuthOk401 | GetApiAuthOk403 | GetApiAuthOk404 | GetApiAuthOk429 | GetApiAuthOk500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthOkQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthOk>>> = ({ signal }) => getApiAuthOk(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthOkQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthOk>>>
export type GetApiAuthOkQueryError = GetApiAuthOk400 | GetApiAuthOk401 | GetApiAuthOk403 | GetApiAuthOk404 | GetApiAuthOk429 | GetApiAuthOk500


export function useGetApiAuthOk<TData = Awaited<ReturnType<typeof getApiAuthOk>>, TError = GetApiAuthOk400 | GetApiAuthOk401 | GetApiAuthOk403 | GetApiAuthOk404 | GetApiAuthOk429 | GetApiAuthOk500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthOk>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthOk>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthOk<TData = Awaited<ReturnType<typeof getApiAuthOk>>, TError = GetApiAuthOk400 | GetApiAuthOk401 | GetApiAuthOk403 | GetApiAuthOk404 | GetApiAuthOk429 | GetApiAuthOk500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthOk>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthOk>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthOk<TData = Awaited<ReturnType<typeof getApiAuthOk>>, TError = GetApiAuthOk400 | GetApiAuthOk401 | GetApiAuthOk403 | GetApiAuthOk404 | GetApiAuthOk429 | GetApiAuthOk500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthOk<TData = Awaited<ReturnType<typeof getApiAuthOk>>, TError = GetApiAuthOk400 | GetApiAuthOk401 | GetApiAuthOk403 | GetApiAuthOk404 | GetApiAuthOk429 | GetApiAuthOk500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthOk>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthOkQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey }
}




/**
 * Displays an error page
 */
export const getApiAuthError = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/auth/error`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAuthErrorQueryKey = () => {
    return [
    `/api/auth/error`
    ] as const;
    }

    
export const getGetApiAuthErrorQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthError>>, TError = GetApiAuthError400 | GetApiAuthError401 | GetApiAuthError403 | GetApiAuthError404 | GetApiAuthError429 | GetApiAuthError500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthError>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthErrorQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthError>>> = ({ signal }) => getApiAuthError(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthError>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthErrorQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthError>>>
export type GetApiAuthErrorQueryError = GetApiAuthError400 | GetApiAuthError401 | GetApiAuthError403 | GetApiAuthError404 | GetApiAuthError429 | GetApiAuthError500


export function useGetApiAuthError<TData = Awaited<ReturnType<typeof getApiAuthError>>, TError = GetApiAuthError400 | GetApiAuthError401 | GetApiAuthError403 | GetApiAuthError404 | GetApiAuthError429 | GetApiAuthError500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthError>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthError>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthError<TData = Awaited<ReturnType<typeof getApiAuthError>>, TError = GetApiAuthError400 | GetApiAuthError401 | GetApiAuthError403 | GetApiAuthError404 | GetApiAuthError429 | GetApiAuthError500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthError>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthError>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthError<TData = Awaited<ReturnType<typeof getApiAuthError>>, TError = GetApiAuthError400 | GetApiAuthError401 | GetApiAuthError403 | GetApiAuthError404 | GetApiAuthError429 | GetApiAuthError500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthError>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthError<TData = Awaited<ReturnType<typeof getApiAuthError>>, TError = GetApiAuthError400 | GetApiAuthError401 | GetApiAuthError403 | GetApiAuthError404 | GetApiAuthError429 | GetApiAuthError500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthError>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthErrorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey }
}




