/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Better Auth
 * API Reference for your Better Auth Instance
 * OpenAPI spec version: 1.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangeEmail200,
  ChangeEmail400,
  ChangeEmail401,
  ChangeEmail403,
  ChangeEmail404,
  ChangeEmail422,
  ChangeEmail429,
  ChangeEmail500,
  ChangeEmailBody,
  ChangePassword200,
  ChangePassword400,
  ChangePassword401,
  ChangePassword403,
  ChangePassword404,
  ChangePassword429,
  ChangePassword500,
  ChangePasswordBody,
  DeleteUser200,
  DeleteUser400,
  DeleteUser401,
  DeleteUser403,
  DeleteUser404,
  DeleteUser429,
  DeleteUser500,
  DeleteUserBody,
  GetAccountInfo200,
  GetAccountInfo400,
  GetAccountInfo401,
  GetAccountInfo403,
  GetAccountInfo404,
  GetAccountInfo429,
  GetAccountInfo500,
  GetDeleteUserCallback200,
  GetDeleteUserCallback400,
  GetDeleteUserCallback401,
  GetDeleteUserCallback403,
  GetDeleteUserCallback404,
  GetDeleteUserCallback429,
  GetDeleteUserCallback500,
  GetDeleteUserCallbackParams,
  GetError400,
  GetError401,
  GetError403,
  GetError404,
  GetError429,
  GetError500,
  GetOk200,
  GetOk400,
  GetOk401,
  GetOk403,
  GetOk404,
  GetOk429,
  GetOk500,
  GetSession200,
  GetSession400,
  GetSession401,
  GetSession403,
  GetSession404,
  GetSession429,
  GetSession500,
  GetVerifyEmail200,
  GetVerifyEmail400,
  GetVerifyEmail401,
  GetVerifyEmail403,
  GetVerifyEmail404,
  GetVerifyEmail429,
  GetVerifyEmail500,
  GetVerifyEmailParams,
  LinkSocialAccount200,
  LinkSocialAccount400,
  LinkSocialAccount401,
  LinkSocialAccount403,
  LinkSocialAccount404,
  LinkSocialAccount429,
  LinkSocialAccount500,
  LinkSocialAccountBody,
  ListUserAccounts200Item,
  ListUserAccounts400,
  ListUserAccounts401,
  ListUserAccounts403,
  ListUserAccounts404,
  ListUserAccounts429,
  ListUserAccounts500,
  ListUserSessions400,
  ListUserSessions401,
  ListUserSessions403,
  ListUserSessions404,
  ListUserSessions429,
  ListUserSessions500,
  PostGetAccessToken200,
  PostGetAccessToken401,
  PostGetAccessToken403,
  PostGetAccessToken404,
  PostGetAccessToken429,
  PostGetAccessToken500,
  PostGetAccessTokenBody,
  PostRefreshToken200,
  PostRefreshToken401,
  PostRefreshToken403,
  PostRefreshToken404,
  PostRefreshToken429,
  PostRefreshToken500,
  PostRefreshTokenBody,
  PostRevokeOtherSessions200,
  PostRevokeOtherSessions400,
  PostRevokeOtherSessions401,
  PostRevokeOtherSessions403,
  PostRevokeOtherSessions404,
  PostRevokeOtherSessions429,
  PostRevokeOtherSessions500,
  PostRevokeOtherSessionsBody,
  PostRevokeSession200,
  PostRevokeSession400,
  PostRevokeSession401,
  PostRevokeSession403,
  PostRevokeSession404,
  PostRevokeSession429,
  PostRevokeSession500,
  PostRevokeSessionBody,
  PostRevokeSessions200,
  PostRevokeSessions400,
  PostRevokeSessions401,
  PostRevokeSessions403,
  PostRevokeSessions404,
  PostRevokeSessions429,
  PostRevokeSessions500,
  PostRevokeSessionsBody,
  PostUnlinkAccount200,
  PostUnlinkAccount400,
  PostUnlinkAccount401,
  PostUnlinkAccount403,
  PostUnlinkAccount404,
  PostUnlinkAccount429,
  PostUnlinkAccount500,
  PostUnlinkAccountBody,
  RequestPasswordReset200,
  RequestPasswordReset400,
  RequestPasswordReset401,
  RequestPasswordReset403,
  RequestPasswordReset404,
  RequestPasswordReset429,
  RequestPasswordReset500,
  RequestPasswordResetBody,
  ResetPassword200,
  ResetPassword400,
  ResetPassword401,
  ResetPassword403,
  ResetPassword404,
  ResetPassword429,
  ResetPassword500,
  ResetPasswordBody,
  ResetPasswordCallback200,
  ResetPasswordCallback400,
  ResetPasswordCallback401,
  ResetPasswordCallback403,
  ResetPasswordCallback404,
  ResetPasswordCallback429,
  ResetPasswordCallback500,
  ResetPasswordCallbackParams,
  SendVerificationEmail200,
  SendVerificationEmail400,
  SendVerificationEmail401,
  SendVerificationEmail403,
  SendVerificationEmail404,
  SendVerificationEmail429,
  SendVerificationEmail500,
  SendVerificationEmailBody,
  Session,
  SignInEmail200,
  SignInEmail400,
  SignInEmail401,
  SignInEmail403,
  SignInEmail404,
  SignInEmail429,
  SignInEmail500,
  SignInEmailBody,
  SignOut200,
  SignOut400,
  SignOut401,
  SignOut403,
  SignOut404,
  SignOut429,
  SignOut500,
  SignOutBody,
  SignUpWithEmailAndPassword200,
  SignUpWithEmailAndPassword400,
  SignUpWithEmailAndPassword401,
  SignUpWithEmailAndPassword403,
  SignUpWithEmailAndPassword404,
  SignUpWithEmailAndPassword422,
  SignUpWithEmailAndPassword429,
  SignUpWithEmailAndPassword500,
  SignUpWithEmailAndPasswordBody,
  SocialSignIn200,
  SocialSignIn400,
  SocialSignIn401,
  SocialSignIn403,
  SocialSignIn404,
  SocialSignIn429,
  SocialSignIn500,
  SocialSignInBody,
  UpdateUser200,
  UpdateUser400,
  UpdateUser401,
  UpdateUser403,
  UpdateUser404,
  UpdateUser429,
  UpdateUser500,
  UpdateUserBody
} from '../generated.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Sign in with a social provider
 */
export const socialSignIn = (
    socialSignInBody: SocialSignInBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SocialSignIn200>(
      {url: `/sign-in/social`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: socialSignInBody, signal
    },
      options);
    }
  


export const getSocialSignInMutationOptions = <TError = SocialSignIn400 | SocialSignIn401 | SocialSignIn403 | SocialSignIn404 | SocialSignIn429 | SocialSignIn500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialSignIn>>, TError,{data: SocialSignInBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof socialSignIn>>, TError,{data: SocialSignInBody}, TContext> => {

const mutationKey = ['socialSignIn'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof socialSignIn>>, {data: SocialSignInBody}> = (props) => {
          const {data} = props ?? {};

          return  socialSignIn(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SocialSignInMutationResult = NonNullable<Awaited<ReturnType<typeof socialSignIn>>>
    export type SocialSignInMutationBody = SocialSignInBody
    export type SocialSignInMutationError = SocialSignIn400 | SocialSignIn401 | SocialSignIn403 | SocialSignIn404 | SocialSignIn429 | SocialSignIn500

    export const useSocialSignIn = <TError = SocialSignIn400 | SocialSignIn401 | SocialSignIn403 | SocialSignIn404 | SocialSignIn429 | SocialSignIn500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialSignIn>>, TError,{data: SocialSignInBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof socialSignIn>>,
        TError,
        {data: SocialSignInBody},
        TContext
      > => {

      const mutationOptions = getSocialSignInMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get the current session
 */
export const getSession = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSession200>(
      {url: `/get-session`, method: 'GET', signal
    },
      options);
    }
  



export const getGetSessionQueryKey = () => {
    return [
    `/get-session`
    ] as const;
    }

    
export const getGetSessionQueryOptions = <TData = Awaited<ReturnType<typeof getSession>>, TError = GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({ signal }) => getSession(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getSession>>>
export type GetSessionQueryError = GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500



export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = GetSession400 | GetSession401 | GetSession403 | GetSession404 | GetSession429 | GetSession500>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSessionQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Sign out the current user
 */
export const signOut = (
    signOutBody: SignOutBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SignOut200>(
      {url: `/sign-out`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signOutBody, signal
    },
      options);
    }
  


export const getSignOutMutationOptions = <TError = SignOut400 | SignOut401 | SignOut403 | SignOut404 | SignOut429 | SignOut500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError,{data: SignOutBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError,{data: SignOutBody}, TContext> => {

const mutationKey = ['signOut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signOut>>, {data: SignOutBody}> = (props) => {
          const {data} = props ?? {};

          return  signOut(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignOutMutationResult = NonNullable<Awaited<ReturnType<typeof signOut>>>
    export type SignOutMutationBody = SignOutBody
    export type SignOutMutationError = SignOut400 | SignOut401 | SignOut403 | SignOut404 | SignOut429 | SignOut500

    export const useSignOut = <TError = SignOut400 | SignOut401 | SignOut403 | SignOut404 | SignOut429 | SignOut500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError,{data: SignOutBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof signOut>>,
        TError,
        {data: SignOutBody},
        TContext
      > => {

      const mutationOptions = getSignOutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Sign up a user using email and password
 */
export const signUpWithEmailAndPassword = (
    signUpWithEmailAndPasswordBody: SignUpWithEmailAndPasswordBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SignUpWithEmailAndPassword200>(
      {url: `/sign-up/email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signUpWithEmailAndPasswordBody, signal
    },
      options);
    }
  


export const getSignUpWithEmailAndPasswordMutationOptions = <TError = SignUpWithEmailAndPassword400 | SignUpWithEmailAndPassword401 | SignUpWithEmailAndPassword403 | SignUpWithEmailAndPassword404 | SignUpWithEmailAndPassword422 | SignUpWithEmailAndPassword429 | SignUpWithEmailAndPassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signUpWithEmailAndPassword>>, TError,{data: SignUpWithEmailAndPasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof signUpWithEmailAndPassword>>, TError,{data: SignUpWithEmailAndPasswordBody}, TContext> => {

const mutationKey = ['signUpWithEmailAndPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signUpWithEmailAndPassword>>, {data: SignUpWithEmailAndPasswordBody}> = (props) => {
          const {data} = props ?? {};

          return  signUpWithEmailAndPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignUpWithEmailAndPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof signUpWithEmailAndPassword>>>
    export type SignUpWithEmailAndPasswordMutationBody = SignUpWithEmailAndPasswordBody
    export type SignUpWithEmailAndPasswordMutationError = SignUpWithEmailAndPassword400 | SignUpWithEmailAndPassword401 | SignUpWithEmailAndPassword403 | SignUpWithEmailAndPassword404 | SignUpWithEmailAndPassword422 | SignUpWithEmailAndPassword429 | SignUpWithEmailAndPassword500

    export const useSignUpWithEmailAndPassword = <TError = SignUpWithEmailAndPassword400 | SignUpWithEmailAndPassword401 | SignUpWithEmailAndPassword403 | SignUpWithEmailAndPassword404 | SignUpWithEmailAndPassword422 | SignUpWithEmailAndPassword429 | SignUpWithEmailAndPassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signUpWithEmailAndPassword>>, TError,{data: SignUpWithEmailAndPasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof signUpWithEmailAndPassword>>,
        TError,
        {data: SignUpWithEmailAndPasswordBody},
        TContext
      > => {

      const mutationOptions = getSignUpWithEmailAndPasswordMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Sign in with email and password
 */
export const signInEmail = (
    signInEmailBody: SignInEmailBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SignInEmail200>(
      {url: `/sign-in/email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signInEmailBody, signal
    },
      options);
    }
  


export const getSignInEmailMutationOptions = <TError = SignInEmail400 | SignInEmail401 | SignInEmail403 | SignInEmail404 | SignInEmail429 | SignInEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signInEmail>>, TError,{data: SignInEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof signInEmail>>, TError,{data: SignInEmailBody}, TContext> => {

const mutationKey = ['signInEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signInEmail>>, {data: SignInEmailBody}> = (props) => {
          const {data} = props ?? {};

          return  signInEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignInEmailMutationResult = NonNullable<Awaited<ReturnType<typeof signInEmail>>>
    export type SignInEmailMutationBody = SignInEmailBody
    export type SignInEmailMutationError = SignInEmail400 | SignInEmail401 | SignInEmail403 | SignInEmail404 | SignInEmail429 | SignInEmail500

    export const useSignInEmail = <TError = SignInEmail400 | SignInEmail401 | SignInEmail403 | SignInEmail404 | SignInEmail429 | SignInEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signInEmail>>, TError,{data: SignInEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof signInEmail>>,
        TError,
        {data: SignInEmailBody},
        TContext
      > => {

      const mutationOptions = getSignInEmailMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Reset the password for a user
 */
export const resetPassword = (
    resetPasswordBody: ResetPasswordBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ResetPassword200>(
      {url: `/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordBody, signal
    },
      options);
    }
  


export const getResetPasswordMutationOptions = <TError = ResetPassword400 | ResetPassword401 | ResetPassword403 | ResetPassword404 | ResetPassword429 | ResetPassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordBody}, TContext> => {

const mutationKey = ['resetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetPassword>>, {data: ResetPasswordBody}> = (props) => {
          const {data} = props ?? {};

          return  resetPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>
    export type ResetPasswordMutationBody = ResetPasswordBody
    export type ResetPasswordMutationError = ResetPassword400 | ResetPassword401 | ResetPassword403 | ResetPassword404 | ResetPassword429 | ResetPassword500

    export const useResetPassword = <TError = ResetPassword400 | ResetPassword401 | ResetPassword403 | ResetPassword404 | ResetPassword429 | ResetPassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof resetPassword>>,
        TError,
        {data: ResetPasswordBody},
        TContext
      > => {

      const mutationOptions = getResetPasswordMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Verify the email of the user
 */
export const getVerifyEmail = (
    params: GetVerifyEmailParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetVerifyEmail200>(
      {url: `/verify-email`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetVerifyEmailQueryKey = (params?: GetVerifyEmailParams,) => {
    return [
    `/verify-email`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetVerifyEmailQueryOptions = <TData = Awaited<ReturnType<typeof getVerifyEmail>>, TError = GetVerifyEmail400 | GetVerifyEmail401 | GetVerifyEmail403 | GetVerifyEmail404 | GetVerifyEmail429 | GetVerifyEmail500>(params: GetVerifyEmailParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getVerifyEmail>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVerifyEmailQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVerifyEmail>>> = ({ signal }) => getVerifyEmail(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVerifyEmail>>, TError, TData> & { queryKey: QueryKey }
}

export type GetVerifyEmailQueryResult = NonNullable<Awaited<ReturnType<typeof getVerifyEmail>>>
export type GetVerifyEmailQueryError = GetVerifyEmail400 | GetVerifyEmail401 | GetVerifyEmail403 | GetVerifyEmail404 | GetVerifyEmail429 | GetVerifyEmail500



export function useGetVerifyEmail<TData = Awaited<ReturnType<typeof getVerifyEmail>>, TError = GetVerifyEmail400 | GetVerifyEmail401 | GetVerifyEmail403 | GetVerifyEmail404 | GetVerifyEmail429 | GetVerifyEmail500>(
 params: GetVerifyEmailParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getVerifyEmail>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetVerifyEmailQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Send a verification email to the user
 */
export const sendVerificationEmail = (
    sendVerificationEmailBody: SendVerificationEmailBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SendVerificationEmail200>(
      {url: `/send-verification-email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendVerificationEmailBody, signal
    },
      options);
    }
  


export const getSendVerificationEmailMutationOptions = <TError = SendVerificationEmail400 | SendVerificationEmail401 | SendVerificationEmail403 | SendVerificationEmail404 | SendVerificationEmail429 | SendVerificationEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendVerificationEmail>>, TError,{data: SendVerificationEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendVerificationEmail>>, TError,{data: SendVerificationEmailBody}, TContext> => {

const mutationKey = ['sendVerificationEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendVerificationEmail>>, {data: SendVerificationEmailBody}> = (props) => {
          const {data} = props ?? {};

          return  sendVerificationEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SendVerificationEmailMutationResult = NonNullable<Awaited<ReturnType<typeof sendVerificationEmail>>>
    export type SendVerificationEmailMutationBody = SendVerificationEmailBody
    export type SendVerificationEmailMutationError = SendVerificationEmail400 | SendVerificationEmail401 | SendVerificationEmail403 | SendVerificationEmail404 | SendVerificationEmail429 | SendVerificationEmail500

    export const useSendVerificationEmail = <TError = SendVerificationEmail400 | SendVerificationEmail401 | SendVerificationEmail403 | SendVerificationEmail404 | SendVerificationEmail429 | SendVerificationEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendVerificationEmail>>, TError,{data: SendVerificationEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof sendVerificationEmail>>,
        TError,
        {data: SendVerificationEmailBody},
        TContext
      > => {

      const mutationOptions = getSendVerificationEmailMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const changeEmail = (
    changeEmailBody: ChangeEmailBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ChangeEmail200>(
      {url: `/change-email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changeEmailBody, signal
    },
      options);
    }
  


export const getChangeEmailMutationOptions = <TError = ChangeEmail400 | ChangeEmail401 | ChangeEmail403 | ChangeEmail404 | ChangeEmail422 | ChangeEmail429 | ChangeEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeEmail>>, TError,{data: ChangeEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof changeEmail>>, TError,{data: ChangeEmailBody}, TContext> => {

const mutationKey = ['changeEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeEmail>>, {data: ChangeEmailBody}> = (props) => {
          const {data} = props ?? {};

          return  changeEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeEmailMutationResult = NonNullable<Awaited<ReturnType<typeof changeEmail>>>
    export type ChangeEmailMutationBody = ChangeEmailBody
    export type ChangeEmailMutationError = ChangeEmail400 | ChangeEmail401 | ChangeEmail403 | ChangeEmail404 | ChangeEmail422 | ChangeEmail429 | ChangeEmail500

    export const useChangeEmail = <TError = ChangeEmail400 | ChangeEmail401 | ChangeEmail403 | ChangeEmail404 | ChangeEmail422 | ChangeEmail429 | ChangeEmail500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeEmail>>, TError,{data: ChangeEmailBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof changeEmail>>,
        TError,
        {data: ChangeEmailBody},
        TContext
      > => {

      const mutationOptions = getChangeEmailMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Change the password of the user
 */
export const changePassword = (
    changePasswordBody: ChangePasswordBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ChangePassword200>(
      {url: `/change-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordBody, signal
    },
      options);
    }
  


export const getChangePasswordMutationOptions = <TError = ChangePassword400 | ChangePassword401 | ChangePassword403 | ChangePassword404 | ChangePassword429 | ChangePassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordBody}, TContext> => {

const mutationKey = ['changePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePassword>>, {data: ChangePasswordBody}> = (props) => {
          const {data} = props ?? {};

          return  changePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
    export type ChangePasswordMutationBody = ChangePasswordBody
    export type ChangePasswordMutationError = ChangePassword400 | ChangePassword401 | ChangePassword403 | ChangePassword404 | ChangePassword429 | ChangePassword500

    export const useChangePassword = <TError = ChangePassword400 | ChangePassword401 | ChangePassword403 | ChangePassword404 | ChangePassword429 | ChangePassword500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof changePassword>>,
        TError,
        {data: ChangePasswordBody},
        TContext
      > => {

      const mutationOptions = getChangePasswordMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Update the current user
 */
export const updateUser = (
    updateUserBody: UpdateUserBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UpdateUser200>(
      {url: `/update-user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateUserBody, signal
    },
      options);
    }
  


export const getUpdateUserMutationOptions = <TError = UpdateUser400 | UpdateUser401 | UpdateUser403 | UpdateUser404 | UpdateUser429 | UpdateUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{data: UpdateUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{data: UpdateUserBody}, TContext> => {

const mutationKey = ['updateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {data: UpdateUserBody}> = (props) => {
          const {data} = props ?? {};

          return  updateUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = UpdateUserBody
    export type UpdateUserMutationError = UpdateUser400 | UpdateUser401 | UpdateUser403 | UpdateUser404 | UpdateUser429 | UpdateUser500

    export const useUpdateUser = <TError = UpdateUser400 | UpdateUser401 | UpdateUser403 | UpdateUser404 | UpdateUser429 | UpdateUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{data: UpdateUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {data: UpdateUserBody},
        TContext
      > => {

      const mutationOptions = getUpdateUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Delete the user
 */
export const deleteUser = (
    deleteUserBody: DeleteUserBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DeleteUser200>(
      {url: `/delete-user`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteUserBody, signal
    },
      options);
    }
  


export const getDeleteUserMutationOptions = <TError = DeleteUser400 | DeleteUser401 | DeleteUser403 | DeleteUser404 | DeleteUser429 | DeleteUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: DeleteUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: DeleteUserBody}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {data: DeleteUserBody}> = (props) => {
          const {data} = props ?? {};

          return  deleteUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    export type DeleteUserMutationBody = DeleteUserBody
    export type DeleteUserMutationError = DeleteUser400 | DeleteUser401 | DeleteUser403 | DeleteUser404 | DeleteUser429 | DeleteUser500

    export const useDeleteUser = <TError = DeleteUser400 | DeleteUser401 | DeleteUser403 | DeleteUser404 | DeleteUser429 | DeleteUser500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: DeleteUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {data: DeleteUserBody},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Send a password reset email to the user
 */
export const requestPasswordReset = (
    requestPasswordResetBody: RequestPasswordResetBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RequestPasswordReset200>(
      {url: `/request-password-reset`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestPasswordResetBody, signal
    },
      options);
    }
  


export const getRequestPasswordResetMutationOptions = <TError = RequestPasswordReset400 | RequestPasswordReset401 | RequestPasswordReset403 | RequestPasswordReset404 | RequestPasswordReset429 | RequestPasswordReset500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError,{data: RequestPasswordResetBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError,{data: RequestPasswordResetBody}, TContext> => {

const mutationKey = ['requestPasswordReset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestPasswordReset>>, {data: RequestPasswordResetBody}> = (props) => {
          const {data} = props ?? {};

          return  requestPasswordReset(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RequestPasswordResetMutationResult = NonNullable<Awaited<ReturnType<typeof requestPasswordReset>>>
    export type RequestPasswordResetMutationBody = RequestPasswordResetBody
    export type RequestPasswordResetMutationError = RequestPasswordReset400 | RequestPasswordReset401 | RequestPasswordReset403 | RequestPasswordReset404 | RequestPasswordReset429 | RequestPasswordReset500

    export const useRequestPasswordReset = <TError = RequestPasswordReset400 | RequestPasswordReset401 | RequestPasswordReset403 | RequestPasswordReset404 | RequestPasswordReset429 | RequestPasswordReset500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError,{data: RequestPasswordResetBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof requestPasswordReset>>,
        TError,
        {data: RequestPasswordResetBody},
        TContext
      > => {

      const mutationOptions = getRequestPasswordResetMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Redirects the user to the callback URL with the token
 */
export const resetPasswordCallback = (
    token: string,
    params: ResetPasswordCallbackParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ResetPasswordCallback200>(
      {url: `/reset-password/${token}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getResetPasswordCallbackQueryKey = (token?: string,
    params?: ResetPasswordCallbackParams,) => {
    return [
    `/reset-password/${token}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getResetPasswordCallbackQueryOptions = <TData = Awaited<ReturnType<typeof resetPasswordCallback>>, TError = ResetPasswordCallback400 | ResetPasswordCallback401 | ResetPasswordCallback403 | ResetPasswordCallback404 | ResetPasswordCallback429 | ResetPasswordCallback500>(token: string,
    params: ResetPasswordCallbackParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResetPasswordCallbackQueryKey(token,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof resetPasswordCallback>>> = ({ signal }) => resetPasswordCallback(token,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData> & { queryKey: QueryKey }
}

export type ResetPasswordCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof resetPasswordCallback>>>
export type ResetPasswordCallbackQueryError = ResetPasswordCallback400 | ResetPasswordCallback401 | ResetPasswordCallback403 | ResetPasswordCallback404 | ResetPasswordCallback429 | ResetPasswordCallback500



export function useResetPasswordCallback<TData = Awaited<ReturnType<typeof resetPasswordCallback>>, TError = ResetPasswordCallback400 | ResetPasswordCallback401 | ResetPasswordCallback403 | ResetPasswordCallback404 | ResetPasswordCallback429 | ResetPasswordCallback500>(
 token: string,
    params: ResetPasswordCallbackParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof resetPasswordCallback>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getResetPasswordCallbackQueryOptions(token,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * List all active sessions for the user
 */
export const listUserSessions = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Session[]>(
      {url: `/list-sessions`, method: 'GET', signal
    },
      options);
    }
  



export const getListUserSessionsQueryKey = () => {
    return [
    `/list-sessions`
    ] as const;
    }

    
export const getListUserSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listUserSessions>>, TError = ListUserSessions400 | ListUserSessions401 | ListUserSessions403 | ListUserSessions404 | ListUserSessions429 | ListUserSessions500>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUserSessions>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUserSessionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUserSessions>>> = ({ signal }) => listUserSessions(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUserSessions>>, TError, TData> & { queryKey: QueryKey }
}

export type ListUserSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listUserSessions>>>
export type ListUserSessionsQueryError = ListUserSessions400 | ListUserSessions401 | ListUserSessions403 | ListUserSessions404 | ListUserSessions429 | ListUserSessions500



export function useListUserSessions<TData = Awaited<ReturnType<typeof listUserSessions>>, TError = ListUserSessions400 | ListUserSessions401 | ListUserSessions403 | ListUserSessions404 | ListUserSessions429 | ListUserSessions500>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUserSessions>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListUserSessionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Revoke a single session
 */
export const postRevokeSession = (
    postRevokeSessionBody: PostRevokeSessionBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostRevokeSession200>(
      {url: `/revoke-session`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRevokeSessionBody, signal
    },
      options);
    }
  


export const getPostRevokeSessionMutationOptions = <TError = PostRevokeSession400 | PostRevokeSession401 | PostRevokeSession403 | PostRevokeSession404 | PostRevokeSession429 | PostRevokeSession500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRevokeSession>>, TError,{data: PostRevokeSessionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postRevokeSession>>, TError,{data: PostRevokeSessionBody}, TContext> => {

const mutationKey = ['postRevokeSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRevokeSession>>, {data: PostRevokeSessionBody}> = (props) => {
          const {data} = props ?? {};

          return  postRevokeSession(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRevokeSessionMutationResult = NonNullable<Awaited<ReturnType<typeof postRevokeSession>>>
    export type PostRevokeSessionMutationBody = PostRevokeSessionBody
    export type PostRevokeSessionMutationError = PostRevokeSession400 | PostRevokeSession401 | PostRevokeSession403 | PostRevokeSession404 | PostRevokeSession429 | PostRevokeSession500

    export const usePostRevokeSession = <TError = PostRevokeSession400 | PostRevokeSession401 | PostRevokeSession403 | PostRevokeSession404 | PostRevokeSession429 | PostRevokeSession500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRevokeSession>>, TError,{data: PostRevokeSessionBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postRevokeSession>>,
        TError,
        {data: PostRevokeSessionBody},
        TContext
      > => {

      const mutationOptions = getPostRevokeSessionMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Revoke all sessions for the user
 */
export const postRevokeSessions = (
    postRevokeSessionsBody: PostRevokeSessionsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostRevokeSessions200>(
      {url: `/revoke-sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRevokeSessionsBody, signal
    },
      options);
    }
  


export const getPostRevokeSessionsMutationOptions = <TError = PostRevokeSessions400 | PostRevokeSessions401 | PostRevokeSessions403 | PostRevokeSessions404 | PostRevokeSessions429 | PostRevokeSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRevokeSessions>>, TError,{data: PostRevokeSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postRevokeSessions>>, TError,{data: PostRevokeSessionsBody}, TContext> => {

const mutationKey = ['postRevokeSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRevokeSessions>>, {data: PostRevokeSessionsBody}> = (props) => {
          const {data} = props ?? {};

          return  postRevokeSessions(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRevokeSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postRevokeSessions>>>
    export type PostRevokeSessionsMutationBody = PostRevokeSessionsBody
    export type PostRevokeSessionsMutationError = PostRevokeSessions400 | PostRevokeSessions401 | PostRevokeSessions403 | PostRevokeSessions404 | PostRevokeSessions429 | PostRevokeSessions500

    export const usePostRevokeSessions = <TError = PostRevokeSessions400 | PostRevokeSessions401 | PostRevokeSessions403 | PostRevokeSessions404 | PostRevokeSessions429 | PostRevokeSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRevokeSessions>>, TError,{data: PostRevokeSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postRevokeSessions>>,
        TError,
        {data: PostRevokeSessionsBody},
        TContext
      > => {

      const mutationOptions = getPostRevokeSessionsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Revoke all other sessions for the user except the current one
 */
export const postRevokeOtherSessions = (
    postRevokeOtherSessionsBody: PostRevokeOtherSessionsBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostRevokeOtherSessions200>(
      {url: `/revoke-other-sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRevokeOtherSessionsBody, signal
    },
      options);
    }
  


export const getPostRevokeOtherSessionsMutationOptions = <TError = PostRevokeOtherSessions400 | PostRevokeOtherSessions401 | PostRevokeOtherSessions403 | PostRevokeOtherSessions404 | PostRevokeOtherSessions429 | PostRevokeOtherSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRevokeOtherSessions>>, TError,{data: PostRevokeOtherSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postRevokeOtherSessions>>, TError,{data: PostRevokeOtherSessionsBody}, TContext> => {

const mutationKey = ['postRevokeOtherSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRevokeOtherSessions>>, {data: PostRevokeOtherSessionsBody}> = (props) => {
          const {data} = props ?? {};

          return  postRevokeOtherSessions(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRevokeOtherSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postRevokeOtherSessions>>>
    export type PostRevokeOtherSessionsMutationBody = PostRevokeOtherSessionsBody
    export type PostRevokeOtherSessionsMutationError = PostRevokeOtherSessions400 | PostRevokeOtherSessions401 | PostRevokeOtherSessions403 | PostRevokeOtherSessions404 | PostRevokeOtherSessions429 | PostRevokeOtherSessions500

    export const usePostRevokeOtherSessions = <TError = PostRevokeOtherSessions400 | PostRevokeOtherSessions401 | PostRevokeOtherSessions403 | PostRevokeOtherSessions404 | PostRevokeOtherSessions429 | PostRevokeOtherSessions500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRevokeOtherSessions>>, TError,{data: PostRevokeOtherSessionsBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postRevokeOtherSessions>>,
        TError,
        {data: PostRevokeOtherSessionsBody},
        TContext
      > => {

      const mutationOptions = getPostRevokeOtherSessionsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Link a social account to the user
 */
export const linkSocialAccount = (
    linkSocialAccountBody: LinkSocialAccountBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LinkSocialAccount200>(
      {url: `/link-social`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linkSocialAccountBody, signal
    },
      options);
    }
  


export const getLinkSocialAccountMutationOptions = <TError = LinkSocialAccount400 | LinkSocialAccount401 | LinkSocialAccount403 | LinkSocialAccount404 | LinkSocialAccount429 | LinkSocialAccount500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkSocialAccount>>, TError,{data: LinkSocialAccountBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof linkSocialAccount>>, TError,{data: LinkSocialAccountBody}, TContext> => {

const mutationKey = ['linkSocialAccount'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof linkSocialAccount>>, {data: LinkSocialAccountBody}> = (props) => {
          const {data} = props ?? {};

          return  linkSocialAccount(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LinkSocialAccountMutationResult = NonNullable<Awaited<ReturnType<typeof linkSocialAccount>>>
    export type LinkSocialAccountMutationBody = LinkSocialAccountBody
    export type LinkSocialAccountMutationError = LinkSocialAccount400 | LinkSocialAccount401 | LinkSocialAccount403 | LinkSocialAccount404 | LinkSocialAccount429 | LinkSocialAccount500

    export const useLinkSocialAccount = <TError = LinkSocialAccount400 | LinkSocialAccount401 | LinkSocialAccount403 | LinkSocialAccount404 | LinkSocialAccount429 | LinkSocialAccount500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkSocialAccount>>, TError,{data: LinkSocialAccountBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof linkSocialAccount>>,
        TError,
        {data: LinkSocialAccountBody},
        TContext
      > => {

      const mutationOptions = getLinkSocialAccountMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * List all accounts linked to the user
 */
export const listUserAccounts = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListUserAccounts200Item[]>(
      {url: `/list-accounts`, method: 'GET', signal
    },
      options);
    }
  



export const getListUserAccountsQueryKey = () => {
    return [
    `/list-accounts`
    ] as const;
    }

    
export const getListUserAccountsQueryOptions = <TData = Awaited<ReturnType<typeof listUserAccounts>>, TError = ListUserAccounts400 | ListUserAccounts401 | ListUserAccounts403 | ListUserAccounts404 | ListUserAccounts429 | ListUserAccounts500>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUserAccountsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUserAccounts>>> = ({ signal }) => listUserAccounts(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData> & { queryKey: QueryKey }
}

export type ListUserAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof listUserAccounts>>>
export type ListUserAccountsQueryError = ListUserAccounts400 | ListUserAccounts401 | ListUserAccounts403 | ListUserAccounts404 | ListUserAccounts429 | ListUserAccounts500



export function useListUserAccounts<TData = Awaited<ReturnType<typeof listUserAccounts>>, TError = ListUserAccounts400 | ListUserAccounts401 | ListUserAccounts403 | ListUserAccounts404 | ListUserAccounts429 | ListUserAccounts500>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUserAccounts>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListUserAccountsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Callback to complete user deletion with verification token
 */
export const getDeleteUserCallback = (
    params?: GetDeleteUserCallbackParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetDeleteUserCallback200>(
      {url: `/delete-user/callback`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetDeleteUserCallbackQueryKey = (params?: GetDeleteUserCallbackParams,) => {
    return [
    `/delete-user/callback`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetDeleteUserCallbackQueryOptions = <TData = Awaited<ReturnType<typeof getDeleteUserCallback>>, TError = GetDeleteUserCallback400 | GetDeleteUserCallback401 | GetDeleteUserCallback403 | GetDeleteUserCallback404 | GetDeleteUserCallback429 | GetDeleteUserCallback500>(params?: GetDeleteUserCallbackParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDeleteUserCallback>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeleteUserCallbackQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeleteUserCallback>>> = ({ signal }) => getDeleteUserCallback(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeleteUserCallback>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDeleteUserCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getDeleteUserCallback>>>
export type GetDeleteUserCallbackQueryError = GetDeleteUserCallback400 | GetDeleteUserCallback401 | GetDeleteUserCallback403 | GetDeleteUserCallback404 | GetDeleteUserCallback429 | GetDeleteUserCallback500



export function useGetDeleteUserCallback<TData = Awaited<ReturnType<typeof getDeleteUserCallback>>, TError = GetDeleteUserCallback400 | GetDeleteUserCallback401 | GetDeleteUserCallback403 | GetDeleteUserCallback404 | GetDeleteUserCallback429 | GetDeleteUserCallback500>(
 params?: GetDeleteUserCallbackParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDeleteUserCallback>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDeleteUserCallbackQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Unlink an account
 */
export const postUnlinkAccount = (
    postUnlinkAccountBody: PostUnlinkAccountBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostUnlinkAccount200>(
      {url: `/unlink-account`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postUnlinkAccountBody, signal
    },
      options);
    }
  


export const getPostUnlinkAccountMutationOptions = <TError = PostUnlinkAccount400 | PostUnlinkAccount401 | PostUnlinkAccount403 | PostUnlinkAccount404 | PostUnlinkAccount429 | PostUnlinkAccount500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUnlinkAccount>>, TError,{data: PostUnlinkAccountBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postUnlinkAccount>>, TError,{data: PostUnlinkAccountBody}, TContext> => {

const mutationKey = ['postUnlinkAccount'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUnlinkAccount>>, {data: PostUnlinkAccountBody}> = (props) => {
          const {data} = props ?? {};

          return  postUnlinkAccount(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostUnlinkAccountMutationResult = NonNullable<Awaited<ReturnType<typeof postUnlinkAccount>>>
    export type PostUnlinkAccountMutationBody = PostUnlinkAccountBody
    export type PostUnlinkAccountMutationError = PostUnlinkAccount400 | PostUnlinkAccount401 | PostUnlinkAccount403 | PostUnlinkAccount404 | PostUnlinkAccount429 | PostUnlinkAccount500

    export const usePostUnlinkAccount = <TError = PostUnlinkAccount400 | PostUnlinkAccount401 | PostUnlinkAccount403 | PostUnlinkAccount404 | PostUnlinkAccount429 | PostUnlinkAccount500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUnlinkAccount>>, TError,{data: PostUnlinkAccountBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postUnlinkAccount>>,
        TError,
        {data: PostUnlinkAccountBody},
        TContext
      > => {

      const mutationOptions = getPostUnlinkAccountMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Refresh the access token using a refresh token
 */
export const postRefreshToken = (
    postRefreshTokenBody: PostRefreshTokenBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostRefreshToken200>(
      {url: `/refresh-token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRefreshTokenBody, signal
    },
      options);
    }
  


export const getPostRefreshTokenMutationOptions = <TError = void | PostRefreshToken401 | PostRefreshToken403 | PostRefreshToken404 | PostRefreshToken429 | PostRefreshToken500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRefreshToken>>, TError,{data: PostRefreshTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postRefreshToken>>, TError,{data: PostRefreshTokenBody}, TContext> => {

const mutationKey = ['postRefreshToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRefreshToken>>, {data: PostRefreshTokenBody}> = (props) => {
          const {data} = props ?? {};

          return  postRefreshToken(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postRefreshToken>>>
    export type PostRefreshTokenMutationBody = PostRefreshTokenBody
    export type PostRefreshTokenMutationError = void | PostRefreshToken401 | PostRefreshToken403 | PostRefreshToken404 | PostRefreshToken429 | PostRefreshToken500

    export const usePostRefreshToken = <TError = void | PostRefreshToken401 | PostRefreshToken403 | PostRefreshToken404 | PostRefreshToken429 | PostRefreshToken500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRefreshToken>>, TError,{data: PostRefreshTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postRefreshToken>>,
        TError,
        {data: PostRefreshTokenBody},
        TContext
      > => {

      const mutationOptions = getPostRefreshTokenMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get a valid access token, doing a refresh if needed
 */
export const postGetAccessToken = (
    postGetAccessTokenBody: PostGetAccessTokenBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostGetAccessToken200>(
      {url: `/get-access-token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postGetAccessTokenBody, signal
    },
      options);
    }
  


export const getPostGetAccessTokenMutationOptions = <TError = void | PostGetAccessToken401 | PostGetAccessToken403 | PostGetAccessToken404 | PostGetAccessToken429 | PostGetAccessToken500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postGetAccessToken>>, TError,{data: PostGetAccessTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postGetAccessToken>>, TError,{data: PostGetAccessTokenBody}, TContext> => {

const mutationKey = ['postGetAccessToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postGetAccessToken>>, {data: PostGetAccessTokenBody}> = (props) => {
          const {data} = props ?? {};

          return  postGetAccessToken(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostGetAccessTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postGetAccessToken>>>
    export type PostGetAccessTokenMutationBody = PostGetAccessTokenBody
    export type PostGetAccessTokenMutationError = void | PostGetAccessToken401 | PostGetAccessToken403 | PostGetAccessToken404 | PostGetAccessToken429 | PostGetAccessToken500

    export const usePostGetAccessToken = <TError = void | PostGetAccessToken401 | PostGetAccessToken403 | PostGetAccessToken404 | PostGetAccessToken429 | PostGetAccessToken500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postGetAccessToken>>, TError,{data: PostGetAccessTokenBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postGetAccessToken>>,
        TError,
        {data: PostGetAccessTokenBody},
        TContext
      > => {

      const mutationOptions = getPostGetAccessTokenMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get the account info provided by the provider
 */
export const getAccountInfo = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetAccountInfo200>(
      {url: `/account-info`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAccountInfoQueryKey = () => {
    return [
    `/account-info`
    ] as const;
    }

    
export const getGetAccountInfoQueryOptions = <TData = Awaited<ReturnType<typeof getAccountInfo>>, TError = GetAccountInfo400 | GetAccountInfo401 | GetAccountInfo403 | GetAccountInfo404 | GetAccountInfo429 | GetAccountInfo500>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAccountInfo>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAccountInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccountInfo>>> = ({ signal }) => getAccountInfo(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAccountInfo>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAccountInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getAccountInfo>>>
export type GetAccountInfoQueryError = GetAccountInfo400 | GetAccountInfo401 | GetAccountInfo403 | GetAccountInfo404 | GetAccountInfo429 | GetAccountInfo500



export function useGetAccountInfo<TData = Awaited<ReturnType<typeof getAccountInfo>>, TError = GetAccountInfo400 | GetAccountInfo401 | GetAccountInfo403 | GetAccountInfo404 | GetAccountInfo429 | GetAccountInfo500>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAccountInfo>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAccountInfoQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Check if the API is working
 */
export const getOk = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetOk200>(
      {url: `/ok`, method: 'GET', signal
    },
      options);
    }
  



export const getGetOkQueryKey = () => {
    return [
    `/ok`
    ] as const;
    }

    
export const getGetOkQueryOptions = <TData = Awaited<ReturnType<typeof getOk>>, TError = GetOk400 | GetOk401 | GetOk403 | GetOk404 | GetOk429 | GetOk500>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOk>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOkQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOk>>> = ({ signal }) => getOk(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOk>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOkQueryResult = NonNullable<Awaited<ReturnType<typeof getOk>>>
export type GetOkQueryError = GetOk400 | GetOk401 | GetOk403 | GetOk404 | GetOk429 | GetOk500



export function useGetOk<TData = Awaited<ReturnType<typeof getOk>>, TError = GetOk400 | GetOk401 | GetOk403 | GetOk404 | GetOk429 | GetOk500>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOk>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOkQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Displays an error page
 */
export const getError = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/error`, method: 'GET', signal
    },
      options);
    }
  



export const getGetErrorQueryKey = () => {
    return [
    `/error`
    ] as const;
    }

    
export const getGetErrorQueryOptions = <TData = Awaited<ReturnType<typeof getError>>, TError = GetError400 | GetError401 | GetError403 | GetError404 | GetError429 | GetError500>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getError>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetErrorQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getError>>> = ({ signal }) => getError(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getError>>, TError, TData> & { queryKey: QueryKey }
}

export type GetErrorQueryResult = NonNullable<Awaited<ReturnType<typeof getError>>>
export type GetErrorQueryError = GetError400 | GetError401 | GetError403 | GetError404 | GetError429 | GetError500



export function useGetError<TData = Awaited<ReturnType<typeof getError>>, TError = GetError400 | GetError401 | GetError403 | GetError404 | GetError429 | GetError500>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getError>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetErrorQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




