/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * NexxaTrade API
 * API documentation for NexxaTrade
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const postApiUploadsProfilePicture = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/uploads/profile-picture`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiUploadsProfilePictureMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUploadsProfilePicture>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUploadsProfilePicture>>, TError,void, TContext> => {

const mutationKey = ['postApiUploadsProfilePicture'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUploadsProfilePicture>>, void> = () => {
          

          return  postApiUploadsProfilePicture(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiUploadsProfilePictureMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUploadsProfilePicture>>>
    
    export type PostApiUploadsProfilePictureMutationError = unknown

    export const usePostApiUploadsProfilePicture = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUploadsProfilePicture>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUploadsProfilePicture>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiUploadsProfilePictureMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getStorageProfilePicturesFilename = (
    filename: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/storage/profile-pictures/${filename}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetStorageProfilePicturesFilenameQueryKey = (filename?: string,) => {
    return [
    `/storage/profile-pictures/${filename}`
    ] as const;
    }

    
export const getGetStorageProfilePicturesFilenameQueryOptions = <TData = Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>, TError = unknown>(filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStorageProfilePicturesFilenameQueryKey(filename);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>> = ({ signal }) => getStorageProfilePicturesFilename(filename, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(filename), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStorageProfilePicturesFilenameQueryResult = NonNullable<Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>>
export type GetStorageProfilePicturesFilenameQueryError = unknown


export function useGetStorageProfilePicturesFilename<TData = Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>, TError = unknown>(
 filename: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>,
          TError,
          Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStorageProfilePicturesFilename<TData = Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>, TError = unknown>(
 filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>,
          TError,
          Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStorageProfilePicturesFilename<TData = Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>, TError = unknown>(
 filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStorageProfilePicturesFilename<TData = Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>, TError = unknown>(
 filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorageProfilePicturesFilename>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStorageProfilePicturesFilenameQueryOptions(filename,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




